### ISSUE TITLE
on the fly searches

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#100]
Quentin Schoemaker sent in a patch to improve the searching features. These should enable "on the fly searches" within Poweradmin. These patches are against version 1.2.7.

**Comment by edmondas** [comment]
Looks like this is outdated and I don't know where to find patch, also it is against some really old version. Closing this.

**Comment by SebTM** [comment]
You are right, the ticket is outdated. I added this subject to our ideas-list because it should be in mind if we construct our new theme. There really have to be a possibility to search from anywhere.
