### ISSUE TITLE
Hack in for kicking off a Notify for pdns

### ISSUE THREAD

**Issue by zooptwo** [poweradmin/poweradmin#109]
I hacked in a call so when an Zone is updated it will kick of a notify to slaves.  Pasting below.

In record.inc.php  line 161

function update_soa_serial($domain_id) {
        $soa_rec = get_soa_record($domain_id);
    if ($soa_rec == NULL) {
        return false;
    }

```
    $curr_serial = get_soa_serial($soa_rec);
    $new_serial = get_next_serial($curr_serial);

    if ($curr_serial != $new_serial) {
            $soa_rec = set_soa_serial($soa_rec, $new_serial);
```
-                return update_soa_record($domain_id, $soa_rec);
-                $ret = update_soa_record($domain_id, $soa_rec);
-               if ($ret) {
-                        $tmp_domainname = get_zone_name_from_id($domain_id);
-                        exec("sudo /usr/bin/pdns_control notify ".$tmp_domainname);
-                }
      }

So of course you would need to have Sudo installed and configured so that the Web server UserID can execute the command via sudo.

I am sure there might be a better way, but it works.

Again thought I would share.

**Comment by SebTM** [comment]
As @stasic said and I found in the docs powerdns does this automatically. If there is no other reason to do this I will close the issue.

**Comment by edmondas** [comment]
I'm closing this because it is a hack and not a typical use case. Not sure what make it useful and what the benefits are.
