### ISSUE TITLE
Error statement when adding IPv6 slave.

### ISSUE THREAD

**Issue by DLDLightwave** [poweradmin/poweradmin#111]
When adding a slave with an IPv6 address, you get two results:
Error: This is not a valid IPv4 address.
Zone has been added successfully.

Similarly, the delete_zone page will again show:
Error: This is not a valid IPv4 address.
if a slave has an ipv6 address.

There should also possibly be at least the option to restrict slave zones further via:
filter_var  FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE
since in most cases, the master server wouldn't be able to reach the slave.

**Comment by SebTM** [comment]
Needs to be checked with current master-branch if there is still a problem

**Comment by edmondas** [comment]
@DLDLightwave now adding of ipv6 slave works fine. But the option to restrict slaves with ip from private network I will leave for next release.

**Comment by edmondas** [comment]
Adding slaves with IPv6 addresses has been resolved for a long time.
