### ISSUE TITLE
Reverse DNS records are broken

### ISSUE THREAD

**Issue by siberian1967** [poweradmin/poweradmin#127]
Reverse delegated zone example: 171.110.38.in-addr.arpa.

Records are PTR like this:

2.171.110.38.in-addr.arpa
and
2.171.110.38.in-addr.arpa.

When you 'Commit' changes dns.inc.php munges them

```
	if (!(preg_match("/$zone$/i", $name))) {
		if (isset($name) && $name != "") {
			$name = $name . "." . $zone;
		} else {
			$name = $zone;
		}
	}
```

What this does is change the above examples to:

2.171.110.38.in-addr.arpa.171.110.38.in-addr.arpa  (it added the name)
and
2.171.110.38.in-addr.arpa   (It stripped the period)

Change nothing and hit commit again and they become
2.171.110.38.in-addr.arpa.171.110.38.in-addr.arpa.171.110.38.in-addr.arpa  (it added the name again)
and
2.171.110.38.in-addr.arpa.171.110.38.in-addr.arpa   (It added the name)

And so on and so forth forever.

A quick fix for this is to change the above codeblock to ignore this munging if its an in-addr.arpa record. 

Before I submitted a PR for this I wanted to me sure this was not intentional and that I was not missing a bigger picture.

Tx (this broke our network something fierce today, 2000 upset customers. sigh.).

**Comment by SebTM** [comment]
Merged #247 so can be closed
