### ISSUE TITLE
PowerAdmin should have an option to use bcrypted hashses for password storage

### ISSUE THREAD

**Issue by jacques** [poweradmin/poweradmin#147]
Perhaps with a way to upgrade old passwords to using a bcrypt hash as well?

**Comment by lifeofguenter** [comment]
see #227, if it gets merged I will actually implement "needs_rehash" which is pretty trivial:
-> md5 is always 32chars a-f0-9
-> md5salt is md5 + 6 chars (which is also preconfigured)

So basically the next time a user logs in, the password will be rehashed and updated in the database.

**Comment by SebTM** [comment]
@edmondas You implemented this, is it finished?
