### ISSUE TITLE
Move to an MVC setup

### ISSUE THREAD

**Issue by paulstuffins** [poweradmin/poweradmin#148]
Whilst this is not an a major issue, I think that PowerAdmin should move to an MVC based setup, perhaps for the next major update.

What are peoples thoughts on this? Of course, I am happy to work on this if enough people want it.

**Comment by SebTM** [comment]
For now we have decided to focus on fixing bugs, doing cleanup and implement important new features. I will leave this ticket open with the hope that sometimes, our team is big enough to make a complete rewrite on MVC basis.

**Comment by edmondas** [comment]
As a result of my refactoring, view and logic were separated in MVC fashion. Of course the code still requires polishing but I consider that this is done. The idea was to avoid using a heavy framework and have a limited amount of dependencies.
