### ISSUE TITLE
sort by owner on the list zones page 

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#15]
Currently it's not possible to sort by owner on the list zones page, because existing implementation initially fetches the list of zones and only later gets info on owner. Another thing is that every zone can have more than one owner. There is workaround for sorting by owner, but it works properly only when zones have one owner:
https://github.com/poweradmin/poweradmin/tree/order_by_single_owner

**Comment by edmondas** [comment]
The owner-based sorting works as expected.
