### ISSUE TITLE
RFE: RESTful API

### ISSUE THREAD

**Issue by djzort** [poweradmin/poweradmin#153]
It would be neato to have a RESTful API (or if you like... SOAP. Just depends if you like pain).

This would be extremely useful for integrating scripted changes etc

**Comment by BioPhoton** [comment]
There is a git project for a PHP API => https://github.com/jeremib/Pdns-PhpApi

is it compatible?

**Comment by djzort** [comment]
powerdns now has its very own inbuilt api (albeit... not suited to multitenancy) this is no longer needed.
