### ISSUE TITLE
URL and FRAME records

### ISSUE THREAD

**Issue by ciscllc** [poweradmin/poweradmin#159]
Hi,

would  be great having the old url record back (as it is a simple A record with redirector script).

Regards

**Comment by SebTM** [comment]
I thought about this feature and don't think that it has much todo with DNS / PowerDNS. If we implement it, we would need a special vHost to catch all domains. In the document-root we have to install a script which reads out the data from db where to redirect.

But lately I don't think we should implement this!

**Comment by Vaskata84** [comment]
Hi how can i do bind multiple domains to redirect to a domain It's about bet sites where it will be redirected will write will write that they are stopped by the law

**Comment by edmondas** [comment]
The URL record type has been supported for a long time.
