### ISSUE TITLE
Error: You are using an invalid top level domain

### ISSUE THREAD

**Issue by BenKennish** [poweradmin/poweradmin#161]
If I try adding a record my my xxxxxx.sexy domain, I get the error "Error: You are using an invalid top level domain."

I am not.  ".sexy" is a valid TLD and even if it wasn't a globally recognised domain, is it actually up to poweradmin to forbid using such domains when I could be using PowerDNS for an internal-only DNS?

using: poweradmin v 2.1.6

**Comment by edmondas** [comment]
Currently the list of valid TLD is updated from time to time, but in my opinion this must be moved to database and anyone with admin rights will be able to update it.

**Comment by susanin-ivan** [comment]
Why you need a list of valid TLD's at all? 
It is really up to DNS admin what TLD he creating, you should not interfere with this :)

**Comment by BlastFM** [comment]
I found the list of valid TLD's under $valid_tlds in the toolkit.inc.php file, located in /var/www/html/poweradmin/inc by default for anyone else who comes across this issue. This seems a pretty useless check to me as if it was not a valid TLD the DNS zone would just not work.

**Comment by edmondas** [comment]
Strict DNS domain validation is disabled by default in the current release.
