### ISSUE TITLE
Bootstrap theme?

### ISSUE THREAD

**Issue by markc** [poweradmin/poweradmin#168]
Is anyone interested in a Bootstrap 3 interface?

**Comment by blueflow** [comment]
Any news on this?

**Comment by markc** [comment]
@blueflow unfortunately I'm not aware of anything official. My personal thoughts are to use the same database schema and poweradmin, as is, to start with then start again from scratch with another bootstrap only interface. Just get the most used pages up and running first and gradually add more pages as time permits while using the current version to fill in the gaps.

@eraserewind apologies for not helping out and building on your initial port to bootstrap.

**Comment by basilgohar** [comment]
@markc I've been playing with poweradmin for my own needs myself, and found some bugs in relation to using SQLite as a database backend, so if I have time, I'm planning to put my hands into it.  I *may* then be willing to help with some implementation details, but I don't want to overpromise anything at this time.  But I do want to encourage you, if that'll work. :)

**Comment by JonasGroeger** [comment]
Related: #148

**Comment by markc** [comment]
@JonasGroeger it could be related but see my comment above concerning the problem of which MVC framework to chose and code bloat. All that is really needed is to pull out all HTML producing code into their own class methods that return strings instead of that typical insane echo mess everywhere. That's a change that could happen incrementally with the current codebase and could actually make the codebase smaller in the process. Anything to do with composer will double and treble the codebase size in the first iteration. Another theme approach I am tinkering with is to pull out the essential part of PowerAdmin, including the above separate HTML-return-string functions, and create a Wordpress plugin, then there are 10s of 1000s of drop in themes to chose from. If the HTML presentation was isolated properly then it would only take a dozen lines of code to switch between standalone **or** WP plugin output. As crazy as a WP plugin might sound that would naturally lead to associated WP-CLI plugins to EASILY manage PowerAdmin from the command line and remotely via SSH and also via WPs emerging API... and that would truly be useful.

**Comment by HaibaneNero** [comment]
@markc I can't think of a valid reason to include the DNS management into a frontend blog system.

**Comment by JonasGroeger** [comment]
Me neither.

**Comment by markc** [comment]
@HaibaneNero Wordpress is a development platform. Most people just happen to use it as a blog. Anyway you probably missed my main points, that if the codebase was refactored a little then the frontend could be either standalone (as it is now) **OR** a Wordpress plugin **OR** AJAX driven so that the page contents could be included in ANY OTHER PHP APPLICATION. A Wordpress plugin could be one case.

If when using it as a Wordpress plugin then the awesome payoff would then be the ability to take advantage of using the WP-CLI eco-system and Wordpress's emerging API. Both of these points interest me greatly and are the TWO main reasons to justify considering PowerAdmin as a Wordpress plugin. Having access to 10,000 themes to skin a WP-plugin PowerAdmin interface just happens to also solve that other irksome problem of how to best get a mobile friendly interface for PowerAdmin (Bootstrap being one most likely candidate.)

**Comment by JonasGroeger** [comment]
> @JonasGroeger Anything to do with composer will double and treble the codebase size in the first iteration.

The Key here IMHO is readability, extensibility and maintainability, not code size or composer.

**Comment by markc** [comment]
@JonasGroeger Worthy goals and, for me, if the codebase is smaller then that helps enable those goals.

A Wordpress plugin is not my main point but if the codebase was refactored so that all echo statements were converted to functions returning strings then various frontends, such as a pure AJAX system or a WP plugin interface, could far more easily be implemented. it doesn't take a complete rebuild of the project in laravel/whatever to achieve the kind of extensibility I'm thinking of.

**Comment by JonasGroeger** [comment]
@markc Additionally, I would like to see some object orientation, a nicely working permission system which doesen't require you to litter hooks with business logic everywhere and a sane error handling system.

**Comment by markc** [comment]
@JonasGroeger yeah, I'd love to see a php7-only version ready by the end of the year, including your points.

There are "only" 66 PHP files with 14,088 LOC at 506,119 bytes. It's not a huge codebase so I wish I could drop everything and spend 40 man hours on it and at least get it to the point where I could at least further tweak it the way I'd like. The main thing I would do is reduce the 1489 echo and 91 print statements down to 1 top-level echo by wrapping all HTML code in functions (or methods) that return strings, extracting inline logic from the HTML partials, so that at the end of this process all (major) HTML producing functions could easily be moved into it's own area (regardless whether that is a separate folder, includes, classes and/or namespaces). That would resolve the number one pain point of intermixed logic and presentation. This refactoring doesn't require any kind of MVC framework. THEN improving the feature set and general functionality could proceed in a sane manner.

**Comment by glardone** [comment]
Hi all!
I did a test: I have converted the template with Bootstrap standard CSS:

https://github.com/glardone/poweradmin/tree/poweradmin-bootstrap

There is someone who wants to help me in improving it? :-)

**Comment by markc** [comment]
@glardone well done, I'll be forking your repo and testing it out in a few days.

**Comment by markc** [comment]
@glardone I forked your fork and checked out the poweradmin-bootstrap branch but when I tried to run it I got this error below. The master branch seems to work okay. Would you mind turning on issues for your fork so I can continue working on this with you?
```
PHP Fatal error:  Uncaught Error: Call to undefined function add_listener() in /var/www/poweradmin/inc/auth.inc.php:36
Stack trace:
#0 /var/www/poweradmin/inc/toolkit.inc.php(271): require_once()
#1 /var/www/poweradmin/index.php(32): require_once('/var/www/...')
#2 {main}
  thrown in /var/www/poweradmin/inc/auth.inc.php on line 36
```

**Comment by glardone** [comment]
@markc Yes, sure: issue activated!
I tried to replicate your problem but I did not succeed

**Comment by SebTM** [comment]
I will have a look at this, but can't ensure that it will be shipped with v2.1.8. But from my personal side it's a goal for the near future.

**Comment by SebTM** [comment]
I had a look on the work done by @glardone and decided to skip this feature for v2.1.8 - I hope it's possible to implement it into the next release.

**Comment by edmondas** [comment]
Finally, I removed all the old themes and added Bootstrap. The code still needs polishing and refactoring, bug fixing, and mobile adaptation.
