### ISSUE TITLE
Display proper message when wrong authentication mode is used

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#17]
Currently Poweradmin can encrypt user passwords using MD5 or MD5SALT algorithms. Encryption mode is defined in configuration file, but there is no way for users how to migrate from one mode to another. Right now just add some informative message instead of authentication failed. Implementation of Migration is set to other milestone (separate task).

**Comment by edmondas** [comment]
No need to fix this issue if #147 will be implemented.
