### ISSUE TITLE
Implement migration of encrypted password between different algorithms

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#18]
Currently Poweradmin can encrypt user passwords using MD5 or MD5SALT algorithms. Encryption mode is defined in configuration file, but there is no way for users how to migrate from one mode to another. Implement interface which will allow to user to migrate their password to different encryption mode. It can be somehow controlled from config.inc.php (allow users to update passwords).

**Comment by edmondas** [comment]
Same as #147.
