### ISSUE TITLE
An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.

### ISSUE THREAD

**Issue by t3log** [poweradmin/poweradmin#187]
Hi ;
Today I installed a powerAdmin from git but when i want to find some records I have a error :

An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.
The following query generated an error:
SELECT
			domains.id AS zid,

			domains.name AS name,

			domains.type AS type,

			domains.master AS master,

                        zones.owner AS owner
			
FROM domains,
 zones,
 users 
			
WHERE  domains.name LIKE '%%' 
AND zones.domain_id = domains.id 
AND users.id = '1'
                        
ORDER BY count_records

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_records' in 'order clause'

**Comment by multichill** [comment]
I ran into this bug too. Steps to reproduce.
* Login to Poweradmin
* Go to search (search.php) and search something
* No problem
* Go to list zones (list_zones.php)
* Sort it by number of records (list_zones.php?zone_sort_by=count_records)
* Go to search (search.php)
* Search for anything
* Tada, a nice database error:

The following query generated an error:

SELECT
			domains.id AS zid,

			domains.name AS name,

			domains.type AS type,

			domains.master AS master,

                        zones.owner AS owner
			
FROM domains,
 zones,
 users 
			
WHERE  domains.name LIKE '%bla%' 
AND zones.domain_id = domains.id 
AND users.id = '5'
                        
ORDER BY count_records

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'count_records' in 'order clause'

If you go back to list zones and sort it by name it's possible to search again.

**Comment by SebTM** [comment]
This is causes by that code from "toolkit.inc.php":

```php
if (isset($_GET["zone_sort_by"]) && preg_match("/^[a-z_]+$/", $_GET["zone_sort_by"])) {
    define('ZONE_SORT_BY', $_GET["zone_sort_by"]);
    $_SESSION["zone_sort_by"] = $_GET["zone_sort_by"];
} elseif (isset($_POST["zone_sort_by"]) && preg_match("/^[a-z_]+$/", $_POST["zone_sort_by"])) {
    define('ZONE_SORT_BY', $_POST["zone_sort_by"]);
    $_SESSION["zone_sort_by"] = $_POST["zone_sort_by"];
} elseif (isset($_SESSION["zone_sort_by"])) {
    define('ZONE_SORT_BY', $_SESSION["zone_sort_by"]);
} else {
    /** Field to sort zone by
     */
    define('ZONE_SORT_BY', "name");
}
```

I will think about whats the best solution and make a pull-request for it.
