### ISSUE TITLE
Integrate portable PHP password hashing framework

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#19]
Integrate portable PHP password hashing framework:
http://www.openwall.com/phpass/
http://www.openwall.com/articles/PHP-Users-Passwords

Proposal: bcrypt could be default encryption (requires php 5.3+)
http://en.wikipedia.org/wiki/Bcrypt

**Comment by lifeofguenter** [comment]
see #227

**Comment by edmondas** [comment]
I'm closing this, because bcrypt hashing was implemented and merged to master, there's still no way to upgrade old hashed, but it's not difficult to implemented
