### ISSUE TITLE
include fail2ban filter config

### ISSUE THREAD

**Issue by lp86** [poweradmin/poweradmin#191]
Glad to see support for logging failed auths to syslog, if someone could include a filter config for fail2ban that would be great. Here is what the failed login looks like with the default settings:

`Jul 30 16:24:34 hostname poweradmin: Failed authentication attempt from [1.2.4.5]`

I tried to create one, but my regex fu is not strong!

**Comment by SebTM** [comment]
I don't see the need to ship a config-file with poweradmin as file2ban allows to use such easy regex. For me it would be enough to include that hint to documentation.
