### ISSUE TITLE
LDAP auth doesn't require a password

### ISSUE THREAD

**Issue by jsumners** [poweradmin/poweradmin#193]
This issue is for 2.1.7 (at least).

If I add a user and specify that he should use LDAP authentication, that user does not require a password to login. I can simply enter the username and press enter at the login form to successfully authenticate.

Looking at the `LDAPAuthenticate` function, there is a check for a password being available in the session before even attempting any LDAP functions. However, this check will _always_ succeed because you are storing an encrypted set of data in that session variable (encrypting an empty string still results in encrypted data). Thus, the check for an empty password fails (i.e. returns true for a password being set).

The following should be inserted into auth.inc.php at line 147 to fix this major security flaw:

``` php
if (strlen($session_pass) == 0) {
  if (isset($_POST['authenticate'])) {
    log_warn(sprintf('Failed LDAP authentication attempte from [%s] for user \'%s\' Reason: Incorrect password', $_SERVER['REMOTE_ADDR'], $_SESSION['userlogin']));
  }
  auth(_('LDAP Authentication failed!'), 'error');
  return;
}
```

**Comment by SebTM** [comment]
@jsumners Can you provide us a Step-by-Step guide to reproduce the bug? If this problem still exists for your please respond until 15.04.2016 otherwise I will close the issue.

**Comment by jsumners** [comment]
@SebTM what else do you want me to say? My bug report _is_ a step-by-step guide.

**Comment by thechile** [comment]
I have this issue as well.. i'll give step-by-step ASAP. But as you can read [here](http://stackoverflow.com/questions/12359831/java-ldap-make-it-not-ignore-blank-passwords) this is a characteristic of LDAP that poweradmin should introduce a configurable flag or make it default that blank passwords are not accepted.

**Comment by edmondas** [comment]
Currently, I am unsure if anyone uses passwordless authentication, so I have added a requirement for non-empty passwords and other checks.
