### ISSUE TITLE
Zone templates not showing

### ISSUE THREAD

**Issue by jangrewe** [poweradmin/poweradmin#197]
I just upgrade my installation from a ~March 2012 version to the current master, did all the db schema updates also checked the structure against the sql files - it seemed correct.
I tried to run "201405302318_add_relations_to_zone_templates.php", but that told me  "Error: Zone does not exist." for each zone.
I'm not sure if that's related, but my main zone template is also missing, i can't select it in the dropdown. If i try to add a new template with the same name, it tells me "Error: Zone template with this name already exists, please choose another one.", so i guess it is using the right table.

It would be great if you have any hint on how to fix this, thanks! ;-)

**Comment by edmondas** [comment]
This has been fixed in commit https://github.com/poweradmin/poweradmin/commit/2d5311f332aa2fd547e70ede8fdcf906ecbbde2b
