### ISSUE TITLE
search zones does not find zones without owner

### ISSUE THREAD

**Issue by packetpusher** [poweradmin/poweradmin#198]
The "Search zones and records" function does not find any zone where no owner in the zones table exists. As some PDNS installations do not solely relay on PowerAdmin some zones were also created with other tools that do not know the owner table. The SQL query within the function search_zone_and_record in inc/record.inc.php should be modified so that would also return results without an owner.

**Comment by SebTM** [comment]
I've tried to reproduce this bug to provide a pull-request but it seems not present anymore.

1. Create domain
2. Modify column "owner" in table "zones" to an id which does not exist e.g. 0 - NULL is not valid!
3. Use "search.php" and search for domain

Domain gets listed in results. There is an error-message

> Error: User does not exist.
> Error: Invalid argument(s) given to function %s" 

shown what I appreciate.
