### ISSUE TITLE
CNAME Problem during zone-transfer

### ISSUE THREAD

**Issue by fager** [poweradmin/poweradmin#2]
As Described in http://rfc-ref.org/RFC-TEXTS/1912/chapter2.html#sub4 CNAMEs should not coexists with other Records.

Poweradmin ignores this rule while saving new or modified records.

New Versions of ISC-Bind (used as public Slave Servers) reject this zones with "failed while receiving responses: CNAME and other data". A lot of Records are ignored until a new zone without this error will be transfered.

It would be a nice feature, if poweradmin would reject this zonemodifications.

**Comment by edmondas** [comment]
Sorry but it seems that we will not be able to fix in current release. Moved to 2.1.9

**Comment by edmondas** [comment]
This was fixed after this pull request was merged https://github.com/poweradmin/poweradmin/pull/334
