### ISSUE TITLE
"get_zone_name_from_id" actually takes a domain id, not a zone id

### ISSUE THREAD

**Issue by oxc** [poweradmin/poweradmin#206]
The get_zone_name_from_id function claims to take a zone ID, but indeed uses the input parameter as a domain ID (selecting directly from the domains table, instead of joining with zones first).

This breaks amongst others the record_templ migration, and probably a lot of other places, if zone-ids and domain-ids are not indentical for each zone (as in my case).

**Comment by edmondas** [comment]
The code mixes terms of zones and domains, which is a bit nasty. The fix has been added.
