### ISSUE TITLE
SRV creation is preventing use of _ character

### ISSUE THREAD

**Issue by jsumners** [poweradmin/poweradmin#218]
https://github.com/poweradmin/poweradmin/blob/master/inc/dns.inc.php#L714
and
https://github.com/poweradmin/poweradmin/blob/master/inc/dns.inc.php#L718

Have invalid regexes. The underscore character should be allowed. See

http://stackoverflow.com/a/2183140
and
https://gothambus.wordpress.com/2012/07/25/autodiscover-srv-record-in-powerdns-with-powe/

**Comment by lifeofguenter** [comment]
Does not seem to be broken - works here. But still the whole dns.inc.php needs a major cleanup.

1. WHY is a subdomain being treated differently depending on the record type? A subdomain (technically "label") is a subdomain - there is no such thing as "special case subdomain" - also ridiculously to allow "any" form of data if it is a TXT record..

2. What you _might_ want to check is if the "convention" is correct (e.g. _service._proto) - but as said, this is only a convention and the NS could care less about it (so if ever should only be displayed as guidance for users) - EVEN then, the label must be validated according to RFC first

**Comment by SebTM** [comment]
So is there still a real bug or is it "we need to cleanup the validation and change them to follow RFC"?

**Comment by jsumners** [comment]
@SebTM since I don't have to add the record more than once, I don't really know. But if the validation isn't following the RFC then I would say it most certainly should.

**Comment by SebTM** [comment]
I created a new issue for that so I will close this.
