### ISSUE TITLE
Rebuild poweradmin

### ISSUE THREAD

**Issue by BlueManLine** [poweradmin/poweradmin#221]
Hi there,

What do you think about rewrite the Poweradmin2 to modern framework? Something like Laravel?
@edmondas on Nov 2014 created an experiment repo [poweradmin/poweradmin3](https://github.com/poweradmin/poweradmin3) and because he didnt change anything on that repo I made a fork at https://github.com/BlueManLine/poweradmin3 .

Because ed isn't so active last weeks we should develope the project to speed up rewriting it.

What do you think?
Are you with me? :stuck_out_tongue_winking_eye:

**Comment by stbuehler** [comment]
I think a new pdns frontend should have two parts:

* server side: a web api, wrapping the pdns web api with added user management
* client side: a UI build with javascript

https://github.com/tuxis-ie/nsedit is a start imho, at least for the first part.

https://github.com/powerdns/pdnscontrol has a login, but no real user management so far. no idea how it looks (didn't try it yet).

**Comment by basilgohar** [comment]
It shouldn't be ridiculously difficult.  I wrote a really, really basic frontend to dpns myself before I ever knew about poweradmin.

**Comment by SebTM** [comment]
As we are trying to reactivate the project I will close the ticket as it don't have a real task. There are many things to do but currently there is no free alternative project which is further with development.
