### ISSUE TITLE
domains table missing?

### ISSUE THREAD

**Issue by ciroiriarte** [poweradmin/poweradmin#230]
Hi!, just installed latest snapshot (as of yesterday) and the mysql schema creation file doesn't have a "domains" table definition. I'm currently seeing this:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'authdns.domains' doesn't exist' in /var/www/html/auth/inc/PDOCommon.class.php:224\nStack trace:\n#0 /var/www/html/auth/inc/PDOCommon.class.php(224): PDO->query('SELECT id FROM ...')\n#1 /var/www/html/auth/inc/record.inc.php(1150): PDOCommon->queryRow('SELECT id FROM ...')\n#2 /var/www/html/auth/add_zone_master.php(87): domain_exists('blah.it')\n#3 {main}\n  thrown in /var/www/html/auth/inc/PDOCommon.class.php on line 224

Any ideas?

**Comment by ciroiriarte** [comment]
Weird, the installer created these tables:

+--------------------+
| Tables_in_authdns  |
+--------------------+
| migrations         |
| perm_items         |
| perm_templ         |
| perm_templ_items   |
| records_zone_templ |
| users              |
| zone_templ         |
| zone_templ_records |
| zones              |
+--------------------+

The tables included in powerdns-mysql-db-structure.sql are not created, is this expected?

**Comment by stasic** [comment]
the table domains should be created by pdns (=powerdns)
poweradmin just creates the tables it self needs!

**Comment by ciroiriarte** [comment]
Thanks!

**Comment by SamTzu** [comment]
Where in this setup does PowerDNS install Database server or any tables?
apt-get install pdns-server

**Comment by alainwolf** [comment]
PowerDNS supports over a dozen different back-ends, and MySQL is only one of them.
Some installations even mix different backends together. There is no way for apt-get to know which you want.
You find the MySQL scripts to prepare your tables in the relevant back-end documentation.
https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/

**Comment by tellnes** [comment]
Maybe we change the installer to create those tables if they are missing?

**Comment by SebTM** [comment]
In my opinion, it's not a good idea to ship the tables from powerdns with poweradmin.

1. There are too many backends which have to be maintained (checked for updates, provide update-script)
2. There are too many different powerdns-versions which (partly) need different schema's so - we would have to react of users version

At this time poweradmin does not modify the powerdns tables just make relations (code based). So if the basic needed columns exist we are flexible to support very different schema's.

**Comment by edmondas** [comment]
As previously mentioned, those tables belong to PowerDNS, so maintaining different schema versions would be difficult.
