### ISSUE TITLE
Adding DNSSEC keys as admin for zones not owned by admin

### ISSUE THREAD

**Issue by lsbbs** [poweradmin/poweradmin#232]
poweradmin version 2.1.8

I can edit records of any zone as admin (UID 1) but if I want to add a DNSSEC key to a zone not owned by admin I get:
Error: You do not have the permission to view this zone.
Notice: Undefined variable: perm_meta_edit /poweradmin/dnssec.php on line 53 Call Stack: 0.0380 367280 1. {main}() /poweradmin/dnssec.php:0 Notice: Undefined variable: perm_meta_edit in /poweradmin/dnssec.php on line 53 Call Stack: 0.0380 367280 1. {main}() /poweradmin/dnssec.php:0 Notice: Undefined variable: perm_view in /poweradmin/dnssec.php on line 61 Call Stack: 0.0380 367280 1. {main}() /poweradmin/dnssec.php:0 Notice: Undefined variable: perm_view in /poweradmin/dnssec.php on line 61 Call Stack: 0.0380 367280 1. {main}() /poweradmin/dnssec.php:0

As long a zone is not owned by a user (after import) I also get:
Notice: Undefined variable: owners in /poweradmin/inc/record.inc.php on line 1612 Call Stack: 0.0000 330688 1. {main}() /poweradmin/edit.php:0 0.2204 815816 2. get_users_from_domain_id() /poweradmin/edit.php:386 Warning: Invalid argument supplied for foreach() in /poweradmin/edit.php on line 392 Call Stack: 0.0000 330688 1. {main}() /poweradmin/edit.php:0

**Comment by cmol** [comment]
I have the exact same issue with an upgraded installation. Adding the zone to be co-owned by a admin user let's me administer DNSSEC.

**Comment by edmondas** [comment]
You should check with the latest code (master or 2.1.9 release), because I cannot reproduce described behavior.
