### ISSUE TITLE
Powerdns how to deploy ". "root server

### ISSUE THREAD

**Issue by GGuiTang** [poweradmin/poweradmin#238]
Poweradmin - 2.7
When I use web pages to create ". "root zone at the following error:

Error: You have invalid characters in your hostname.
Error: failed - Invalid hostname.
![image](https://cloud.githubusercontent.com/assets/13144519/8469470/f5f47662-20ad-11e5-93f5-6ffe9b2288f8.png)

Please expert help, thank you

**Comment by SebTM** [comment]
What did you entered in "Zone name"?

**Comment by edmondas** [comment]
I think he added ".", but I'm not sure if Poweradmin should allow to create such root zone.

**Comment by JonahAragon** [comment]
Was about to report this same bug. PowerDNS supports adding a root zone (and adding it manually lets me view/edit it in Poweradmin) so there's no reason not to allow root zone creation from within Poweradmin. 

It's useful for example, if you add it as a slave zone so you have a local cached version of the DNS root.

**Comment by GGuiTang** [comment]
thanks!

**Comment by elagith** [comment]
I have an error on registration master zone with error:
Error: You have invalid characters in your hostname.
Error: insa.local failed - Invalid hostname.
please help guys.

**Comment by elagith** [comment]
I have error on registration master zone with the following error:
Error: You have invalid characters in your hostname.
Error: insa.local failed - Invalid hostname.
any solution...

**Comment by amadhusudhanan** [comment]
> Poweradmin - 2.7
> When I use web pages to create ". "root zone at the following error:
> 
> Error: You have invalid characters in your hostname.
> Error: failed - Invalid hostname.
> ![image](https://cloud.githubusercontent.com/assets/13144519/8469470/f5f47662-20ad-11e5-93f5-6ffe9b2288f8.png)
> 
> Please expert help, thank you

Can you please confirm, is this issue resolved. I am facing the same issue. Please advice

**Comment by amadhusudhanan** [comment]
> I have an error on registration master zone with error:
> Error: You have invalid characters in your hostname.
> Error: insa.local failed - Invalid hostname.
> please help guys.

Is this issue resolved for you. I am facing the same issue. Please advice.

**Comment by edmondas** [comment]
Make sure you have set `$dns_strict_tld_check = false;` in your configuration file.
