### ISSUE TITLE
Quotes in description get escaped and cause issues with zone data

### ISSUE THREAD

**Issue by phillipbergner** [poweradmin/poweradmin#242]
I use Poweradmin 2.1.7 with a MySQL backend. When entering in a TXT record, Poweradmin allows me to put a double quote character (") in the zone record's content field. The double quote gets escaped and entered into MySQL, which is technically not allowed and results in an invalid DNS record which will not work with AXFR. With no double quotes, the content text is correctly inserted into the database.

I'm not sure what else it would affect, but I would recommend not allowing double quotes to be inputted in the zone record's content field.

**Comment by ryandb** [comment]
I'm seeing this as well.   However, TXT records require quotes in the content field -- and DNS fails to replicate when created using a template with a TXT record (since quotes are removed).

**Comment by ryandb** [comment]
On further inspection I see the following behavior:

quotes are automacally added to text fields.  This is confusing, since it does not do the same for SDF records, for example.  However, the records appear identical in the GUI.

**Comment by edmondas** [comment]
This is the only code I found:
```php
        // Quotes are special for SPF and TXT
        $type = $record_prior_copy['type'];
        if ($type == "SPF" || $type == "TXT") {
            $record_prior_copy['content'] = trim($record_prior_copy['content'], '"');
            $record_copy['content'] = trim($record_copy['content'], '"');
        }
```
It removed quotes if records are updated, but according to specification those are required:
https://doc.powerdns.com/authoritative/appendices/types.html#txt
