### ISSUE TITLE
Failed to call function exec when $pdnssec_use = false

### ISSUE THREAD

**Issue by prupert** [poweradmin/poweradmin#246]
I have a couple of machines with PowerDNS and PowerAdmin that are NOT using DNSSEC. Therefore I have set `$pdnssec_use	= false;` in `inc/config.inc.php`. I have also disabled the exec() function in PHP because of security reasons. 

However, when removing a domain PowerAdmin still outputs an error message about not being able to use the exec() function to do DNSSEC stuff:

    Error: Failed to call function exec. Make sure that exec is not listed in
    disable_functions at php.ini
    Error: Failed to deactivate DNSSEC keys.
    Zone has been deleted successfully.

This looks like a bug to me and causes confusion to end-users.

**Comment by stsimb** [comment]
To fix this change line 103 of delete_domain.php (poweradmin 2.1.7) to ...
`        if ($pdnssec_use) dnssec_unsecure_zone($zone_name);`

**Comment by prupert** [comment]
Thanks for the suggested fix. In the 2.1.7 release this is line number 74 by the way. I see this is already fixed in master at https://github.com/poweradmin/poweradmin/blob/master/delete_domain.php

When can we expect release 2.1.8?
