### ISSUE TITLE
When deleting a record, sql is executed on the wrong table name

### ISSUE THREAD

**Issue by ryandb** [poweradmin/poweradmin#249]
While the record in the "records" table is successfully deleted, it appears to be attempting to delete from a template table as well.  I'm not sure if this is desired behavior (probably not?) -- but if it is, it is using the wrong table name in the SQL -- I get this error message:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pdns.records_zone_templ' doesn't exist

I believe the correct table name is:    pdns.zone_templ_records.

Either remove this behavior completely, or have it use the correct table name.

**Comment by edmondas** [comment]
@ryandb - this records_zone_templ table is correct name. Not sure which version of Poweradmin you are using, but maybe you forgot to run related migration file or it was not created successfully during installation.

**Comment by ryandb** [comment]
yup - that's it -- sorry.

**Comment by emcniece** [comment]
@ryandb what migration did you run to resolve this?
