### ISSUE TITLE
No SOA Record when creating Master Zone with a Template

### ISSUE THREAD

**Issue by benphelps** [poweradmin/poweradmin#259]
When you create a new Master Zone and use a Template, no SOA record is created.

Steps to recreate:

1. Add new master zone and use a template.
2. No SOA record is created.

Expected Behaviour:

A SOA record should be created even when a template is being used.  Creating an SOA record via a template does not work, see issue #260.

**Comment by SebTM** [comment]
As described in #260 it was working after following the required structure of a SOA records. For more see in #260 I will add a comment with my idea how to improve that. Also I will close this to have one ticket for this.

**Comment by SebTM** [comment]
Closed #259
