### ISSUE TITLE
Unable to bind to LDAP server

### ISSUE THREAD

**Issue by mkyrc** [poweradmin/poweradmin#261]
Hi,
I'd like to configure LDAP authentication against LDAP server, but without success.
in (apache error) log I can see:

```
<cut>
res_errno: 34, res_error: <invalid DN>, res_matched: <>
<cut>
[Thu Dec 03 09:42:32.081530 2015] [:error] [pid 19994] [client 10.254.254.4:1678] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid DN syntax in /var/www/poweradmin-2.1.7/inc/auth.inc.php on line 104, referer: http://ns1.hidden-server/poweradmin/index.php'
```

I can see there "Invalid DN syntax", but is it based on `binddn` or `basedn` syntax error?
I can see this log message also with `$ldap_debug = false`. Is it feature or bug? :)

my config:

```
$ldap_use       = true;
$ldap_debug     = true;
$ldap_uri       = 'ldap://ldap.hidden-server:389';
$ldap_basedn    = 'ou=users,dc=x,dc=y';
#$ldap_basedn   = 'dc=x,dc=y';
#$ldap_binddn   = 'cn=admin,dc=x,dc=y';
$ldap_binddn    = 'admin';
$ldap_bindpw    = 'hidden-pass';
$ldap_user_attribute = 'cn';
$ldap_proto     = 3;
```

structure of my LDAP:

```
base: dc=x,dc=y
admin: cn=admin,dc=x,dc=y
users tree: ou=users,dc=x,dc=y
user: cn=user1,ou=users,dc=x,dc=y; cn=user1,ou=users,dc=x,dc=y; etc
```

poweradmin: v2.1.7
OS: ubuntu 14.04LTS (last stable LTS)
php-ldap: 5.5.9+dfsg-1ubuntu4.14 (last stable from official repository)

when I try 'search' in LDAP using ldapsearch (with above settings) everything is working

**Comment by edmondas** [comment]
I am unable to reproduce this issue with the latest code.

**Comment by edmondas** [comment]
Sorry, I was wrong - I can't login as myself with LDAP.

**Comment by edmondas** [comment]
As you can see from the error, your config is wrong, your `binddn` is incorrect.

The configuration should be as follows based on the information you provided:
```
$ldap_use       = true;
$ldap_uri       = 'ldap://ldap.hidden-server'; // There is no need for a port number
$ldap_basedn    = 'ou=users,dc=x,dc=y'; // The place where all users are stored
$ldap_binddn   = 'cn=admin,dc=x,dc=y'; // The distinguished name of the admin user 
$ldap_bindpw    = 'hidden-pass'; // admin's password
$ldap_user_attribute = 'uid'; // LDAP pattern to use when searching for a user account (OpenLDAP)
$ldap_proto     = 3;
```
