### ISSUE TITLE
poweradmin slave not listing records

### ISSUE THREAD

**Issue by datasoftcomnet** [poweradmin/poweradmin#262]
Hi,
My poweradmin slave is not listing records. The master is listing fine.
versions are pdns-3.4.7-1.el5.MIND and poweradmin 2.1.7 and later in 2.1.8 also.
The config seems to be OK. the updates from master are synchronising into slave.
Only I cannot see the data in Slave -> under list zones if I click any zone it is showing blank records.
Rgds/DP

**Comment by SebTM** [comment]
I don't really understand the issue. Do you have two instances of poweradmin for master and slave?

**Comment by nerozero** [comment]
Hello, 
Have the same issue. Image attached
This happened right after adding slave zone. mysql database table "records" contains no records with appropriate domain id's

![powerdns-empty-slave](https://cloud.githubusercontent.com/assets/18283531/14278836/d9e03868-fb3a-11e5-878b-9d773db48fb7.png)

**Comment by nerozero** [comment]
Fixed, problem was not in poweradmin web interface, actually forget to enable slave zones in  "slave=yes" in "pdns.conf" file 

Sorry.

**Comment by SebTM** [comment]
Nice to hear that it's not a Poweradmin relating issue. I will close this :)
