### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by clanstyles** [poweradmin/poweradmin#264]
Can somebody upload images of the panel

**Comment by zzplab** [comment]
Take  look at: [demo.poweradmin.org](http://demo.poweradmin.org) and login.
You can login as a user using the username and password "demo". There is no PowerDNS instance running against this database, it is just the Poweradmin interface and a mysql backend. The database is regularly emptied. Please be respectful to other users checking out the demo - so don't change the password of the demo user, for example (and if you do, it will be reset within a couple of hours anyway).

**Comment by SebTM** [comment]
I'm thinking about improving our documentation / readme to promote the demo a little bit more. It's not really clear that there is a working demo. What do you mean?

**Comment by edmondas** [comment]
It seems that this demo is for an outdated version (2.1.6). What's bad, that I don't remember who's responsible for that server.

**Comment by SebTM** [comment]
As we discussed in IRC I have contacted a local German ISP. They agreed with sponsoring the Poweradmin project so I will get the credentials for web-interface of the vps in the next days. I would install the required services to install a new demo of v2.1.7 and master-branch afterwards I will forward you the email with the passwords.

**Comment by SebTM** [comment]
Pictures for the docs need to be done short before release to have current images. I'm installing the server at the moment so demo will be available within the next days.

**Comment by edmondas** [comment]
List of all available interface styles added to the wiki:
https://github.com/poweradmin/poweradmin/wiki/UI-Styles
