### ISSUE TITLE
 Failed to call pdnssec utility > renamed to pdnsutil

### ISSUE THREAD

**Issue by HLFH** [poweradmin/poweradmin#265]
Hi,

In PowerDNS 4.0, pdnssec utility has [been renamed to pdnsutil](http://blog.powerdns.com/2015/12/24/technical-preview-releases-of-authoritative-server-recursor-and-dnsdist/).

And I got the issue ' Failed to call pdnssec utility' when I want to delete a zone, because I'm using PowerDNS 4.0.

Thanks in advance to support the new pdnsutil command,
HLFH

**Comment by dmorley** [comment]
I think you can just specify $pdnssec_command='/usr/bin/pdnsutil';

**Comment by HLFH** [comment]
@dmorley Thanks. You're right. https://github.com/poweradmin/poweradmin/blob/master/inc/config-me.inc.php Too many bugs in PowerAdmin. I need to switch. https://github.com/PowerDNS/pdns/wiki/WebFrontends
