### ISSUE TITLE
Records deletion

### ISSUE THREAD

**Issue by izenk** [poweradmin/poweradmin#266]
Hello.
PowerAdmin version: v 2.1.7
OS: ubuntu 14.04
Mysql Ver 14.14 Distrib 5.5.44

Trying to edit DNS zone under administrator: delete one record.

In mysql log I see (ID of record is 58):
...
`DELETE FROM records WHERE id = '58'`
`DELETE FROM records WHERE id = '58'`
`Prepare	DELETE FROM records_zone_templ WHERE record_id = '58'`
`Execute	DELETE FROM records_zone_templ WHERE record_id = '58'`
...

But when I check records table, I see this record:
`SELECT id, domain_id, name, type, content, ttl, prio, change_date FROM records WHERE id='58';`
+----+-----------+------------+------+---------+------+------+-------------+
| id | domain_id | name       | type | content | ttl  | prio | change_date |
+----+-----------+------------+------+---------+------+------+-------------+
| 58 |        19 | test22.com | A    | 1.1.1.1 | 3600 | NULL |  1445957876 |
+----+-----------+------------+------+---------+------+------+-------------+

In apache log I can see one PHP warning:
`[:error] [pid 26589] [client x.x.x.x:54587] PHP Warning:  Invalid argument supplied for foreach() in /var/www/power/poweradmin/edit.php on line 386, referer: https://<poweradmin_domain>/poweradmin/list_zones.php`

and that's all.

I tried also click "Commit changes" link - result is the same.

**Comment by SebTM** [comment]
I can't reproduce this error. Since v2.1.7 is from 2012 I would recommend you to upgrade to latest version and try again.

**Comment by SebTM** [comment]
Can you please post the output of the following query:

> SELECT owner FROM zones WHERE domain_id =19

and also

> SELECT fullname FROM users WHERE id=<owner>

Where **<owner>** have to be the id from the previous query.

**Comment by edmondas** [comment]
I'm closing this because no response for long time. I tried to reproduce it locally with latest code but it works fine.
