### ISSUE TITLE
dynamic_update.php can only update either an IPv4 or an IPv6 entry, not both

### ISSUE THREAD

**Issue by puzich** [poweradmin/poweradmin#267]
Currently you get dual stack internet connection at home, so I think it's a good idea, that dynamic_update.php should update both IPs at once, if the user has an IPv4 and IPv6 address.

**Comment by SebTM** [comment]
It's only possible to update both if give by parameter. The Script can only detect the ip-address from that kind used for request. Would this also suit your requirements?

**Comment by puzich** [comment]
Yes! But because normally you get a complete IPv6 64bit network from you provider, I think the best solution is, that you can update a whole network at once.

**Comment by SebTM** [comment]
What do you mean with update whole network at once?

**Comment by SebTM** [comment]
Seems to be already fixed in this pull-request:
https://github.com/poweradmin/poweradmin/pull/224

Does this suites your needs?

**Comment by edmondas** [comment]
#224 was merged, so please check if you still have problems.

**Comment by SebTM** [comment]
Hi @puzich, can you test it and tell us if this full fill your requirements? If we don't get a feedback until the next seven days I will close this!

**Comment by puzich** [comment]
Hi @SebTM , can you leave it a little bit longer open? I'm going on holiday tomorrow for one week and haven't the time to test.

**Comment by SebTM** [comment]
@puzich Thanks for your reply. No Problem I will leave it open until 22.04.2016 so that you have will have time to test. Thanks for your support!

**Comment by puzich** [comment]
OK, a can't wait and I have done a fast test. Yes, it works. Thanks a lot!

**Comment by SebTM** [comment]
Thanks for your feedback - so I will close the issue!
