### ISSUE TITLE
Please provide a git branch for the latest stable version

### ISSUE THREAD

**Issue by captainark** [poweradmin/poweradmin#274]
Hi !

Could you please provide a git branch for the latest stable version ?

It makes it easier to keep it up-to-date than having to deal with tarballs.

Thanks !

**Comment by edmondas** [comment]
Sorry, but currently we are preparing for 2.1.8 release so master branch can be unstable from time to time. Of course there is 2.1.7 version, but it also has some issues. Please be patient.
I think that only after 2.1.8 release we will introduce maintenance (stable) branch.

**Comment by captainark** [comment]
No worries. Sometimes stuff breaks when you're trying to improve on it.

Thank you for hearing me out ! I'll patiently wait for the 2.1.8 version before migrating the the stable branch ;)
