### ISSUE TITLE
PHP Parse error, after the upgrade to the latest version

### ISSUE THREAD

**Issue by glardone** [poweradmin/poweradmin#276]
Hi,
I have updated my installation to the latest version (29a7e7c), but I get this error:

`PHP Parse error:  syntax error, unexpected '[' in /var/www/poweradmin-new/vendor/poweradmin/Password.php on line 61`

Any idea on why?

Thank you!

**Comment by edmondas** [comment]
@glardone can you try to change code in Password.php on line 61 from
```
return password_hash($password, PASSWORD_BCRYPT, ['cost' => $password_encryption_cost]);
```
to
```
return password_hash($password, PASSWORD_BCRYPT, array('cost' => $password_encryption_cost));
```
Does it work now?

**Comment by glardone** [comment]
Ok, but now I get another error:
PHP Parse error:  syntax error, unexpected '[' in [...]/inc/record.inc.php on line 1654

`$return = array('zones' => [], 'records' => []);`

Thanks for fix.

**Comment by edmondas** [comment]
@glardone I fixed another array initialization issue in master branch, update to it.

**Comment by edmondas** [comment]
@glardone btw which php version do you use?

**Comment by glardone** [comment]
My PHP version is 5.3.10

**Comment by edmondas** [comment]
I believe that there are other changes that could break compatibility with such old version.
Sorry but for Poweradmin 2.1.8 at least PHP version 5.5.0 required.

**Comment by glardone** [comment]
Ok, thank you for information: I upgrade my version of PHP.
