### ISSUE TITLE
Zone edit page, sorting by Id not sorting correctly

### ISSUE THREAD

**Issue by nerozero** [poweradmin/poweradmin#278]
Hello,
ID sorting on zone edit page not working correctly. 
Fixing: 
 add id sorting in inc/record.inc.php file, in function: order_domain_results

**Comment by SebTM** [comment]
Can you provide a pull-request for the bug?

**Comment by SebTM** [comment]
I've tested it and can confirm that the whole order-function in edit.php is not working for me!
