### ISSUE TITLE
Error: You have to install MDB2 library

### ISSUE THREAD

**Issue by Fritch** [poweradmin/poweradmin#281]
After running a PHP upgrade on cpanel (5.3 > 5.4) the poweradmin front page displays;-

"Error: You have to install MDB2 library!"

Have verified the MDB2_mysql driver is installed.  

Any assistance appreciated!

**Comment by SebTM** [comment]
Which Version of Poweradmin do you use?

**Comment by SebTM** [comment]
Could you try to install these:
`apt-get install php5-mysql php-db php-mdb2 php-mdb2-driver-mysql`

As I found on HowtoForge this should solve the problem.

**Comment by edmondas** [comment]
MDB2 dependency was removed in a recent release.
