### ISSUE TITLE
DNSSEC with PowerDNS 4.0.x doesn't work

### ISSUE THREAD

**Issue by galeido** [poweradmin/poweradmin#282]
After upgrade to the latest alpha release of PowerDNS 4.0.x. DNSSEC stopped working.
- Cannot create new keys through web interface

`Error: Failed to secure zone`
`Error: Failed to rectify zone`

The issue is related to the deprecated command `pdnssec`? The new command is `pdnsutil`. I tried to avoid this issue by using `$pdnssec_command = '/usr/bin/pndsutil'`; at `inc/config.inc.php`

Any ideas, how we should fix this issue? I'm willing to help for testing it out.

**Comment by SebTM** [comment]
I would be glad to help you but I'm currently not enough into DNSSEC. @edmondas can you help?

**Comment by prupert** [comment]
PowerDNS 4.0.0 has been released on 2016-07-11. I was wondering if PowerAdmin is already fully supporting PowerDNS 4.0.0, including support for DNSSEC. It appears at least a small change needs to be made to the`$pdnssec_command` variable. @galeido, perhaps you can file a pull request?

**Comment by wociscz** [comment]
Workaround:
add $pdnssec_command = '/usr/bin/pdnsutil' to your config as galeido spotted.
You must merge your pdns.conf together if you have sepparated config in /etc/powerdns/pdns.d/*
poweradmin not understand 'include' statement in pdns.conf, so it fail.

I just create one config /etc/powerdns/pdns.conf with all my settings and poweradmin start working with dnssec in some way (something seems broken).
Signing, rectify, unsigning zones works, key management not working

**Comment by galeido** [comment]
Unfortunately, haven't had time to deep dive into this yet. I have used the same workaround like @wociscz described. Maybe in few weeks, I have more time to figure this out.

**Comment by wociscz** [comment]
@galeido just made pull request with full functionality for new pdnsutil (pdns 4.0.0). Maybe bugged in some way, but in my environment everything works as i need (and added another .css with "nice" look)

**Comment by imtek** [comment]
Is there any progress on this, i already changed the configuration to:
$pdnssec_command = '/usr/bin/pdnsutil';

Still i get:
Failed to rectify zone.

I use PowerDNS 4.0.1

**Comment by hrefhref** [comment]
@imtek, you need to check the user running PowerAdmin has the rights on the pdnsutil command.

**Comment by HansVanEijsden** [comment]
@imtek and don't forget to make sure the powerdns config files in /etc are readable by PowerAdmin too.

**Comment by tswestendorp** [comment]
Some more information can be found at [here (DNSSEC Defaults)](https://doc.powerdns.com/md/authoritative/dnssec/#dnssec-defaults) and [here (Migration)](https://doc.powerdns.com/md/authoritative/dnssec/#migration)

In PowerDNS 4.0 they changed the default algorithm to 13 (ECDSAP256SHA256). Which doesn't generate a KSK/ZSK key. So this is why key management won't output keys other than KSK (see `dnssec_get_dnskey_record()`)

**Comment by louismclennan** [comment]
https://github.com/poweradmin/poweradmin/pull/284 is a good start.

**Comment by prupert** [comment]
@edmondas what is the status of compatibility with PowerDNS 4 in regards to DNSSEC?

**Comment by edmondas** [comment]
The pdnsutil application uses pdns.conf file, which must be accessible by www user.
For example on Ubuntu, there is the www-data user, and to run pdnsutil you need the following:
```
adduser www-data root
chmod 640 /etc/powerdns/pdns.conf
```
The latest code (master -> 2.1.9 release) adds the *$pdnssec_debug* flag to allow debugging of DNSSEC:
![image](https://user-images.githubusercontent.com/9033112/149627545-7a0469f8-27b5-4fad-84e8-21cc600305f6.png)
