### ISSUE TITLE
Problem with automatic 'ptr' record generation

### ISSUE THREAD

**Issue by hdemby** [poweradmin/poweradmin#283]
Fellow PowerAdmin users:

I can reproduce a bug we observed using the PowerAdmin front end for our PowerDNS instance. It appears that if a /24 exist of a /16 reverse DNS domain PowerAdmin can munge the PTR record if the automatic PTR generation feature is used when adding the forward record.

ex.
...
129.134.26.172.in-addr.arpa     PTR     0     rc-esxi-22.our.dns.dom    86400
130.134.26.172.in-addr.arpa     PTR     0     rc-esxi-23.our.dns.dom    86400
131.134.26.172.in-addr.arpa     PTR     0     rc-esxi-24.our.dns.dom    86400
...

I confirmed these records were all resolvable by our PDNS server. I removed and manually re-entered the 'rc-esxi-24.its.unc.edu' record and used the automated PTR record generation feature. 

PowerAdmin split the '.134.' into '.13.4.' possibly to match an existing /24 zone. The resulting PTR record found in a PowerAdmin search for the hostname was:

131.13.4.26.172.in-addr.arpa  in ptr rc-esxi-23.our.dns.dom

> $ host rc-esxi-23.our.dns.dom 152.xx.xx.xx
> rc-esxi-23.our.dns.domhas address 172.26.134.130
> 
> $ host 172.26.134.130 152.xx.xx.xx
> Host 130.134.26.172.in-addr.arpa. not found: 3(NXDOMAIN)

Note that the reverse record is no longer resolvable. 

DB representation of broken record:
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+
| id      | domain_id | name                        | type | content                | ttl   | prio | change_date | ordername | auth | disabled |
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+
| 2661751 |      8781 | 130.134.26.172.in-addr.arpa | PTR  | rc-esxi-23.our.dns.dom | 86400 |    0 |  1466008913 | NULL      | NULL |        0 |
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+

This appeared as '131.13.4.26.172.in-addr.arpa  in ptr rc-esxi-23.our.dns.dom' in a PowerAdmin search. This is an invalid PTR record representation, so of course:

> $ host 172.26.13.4.130 152.xx.xx.xx
> Host 172.26.13.4.130 not found: 5(REFUSED)
> 
> $ host -t ptr 130.4.13.26.172.in-addr.arpa 152.xx.xx.xx
> Host 130.4.13.26.172.in-addr.arpa not found: 3(NXDOMAIN)

I then removed this reverse record and a added it directly to the '26.172.in-addr.arpa' zone with the following result:

> $ host 172.26.134.130 152.xx.xx.xx
> 130.134.26.172.in-addr.arpa domain name pointer rc-esxi-23.our.dns.dom

DB representation of working record:
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+
| id      | domain_id | name                        | type | content                | ttl   | prio | change_date | ordername | auth | disabled |
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+
| 2661731 |      8781 | 130.134.26.172.in-addr.arpa | PTR  | rc-esxi-23.our.dns.dom| 86400 |    0 |  1466004934 | NULL      | NULL |        0 |
+---------+-----------+-----------------------------+------+------------------------+-------+------+-------------+-----------+------+----------+

The record now resolves again:

> $ host 172.26.134.130 152.xx.xx.xx
> 130.134.26.172.in-addr.arpa domain name pointer rc-esxi-23.its.unc.edu.

Note: both the '4.26.172.in-addr.arpa' and the '26.172.in-addr.arpa' domains exist in our production DNS.

Please verify this bug if you can. I have screen captures of the test above if those would help.

We like the automatic PTR generation feature and would really like to avoid re-engineering our subnets to use it if we don't have to do so. I have not checked for this error for forward domains but it's possible that the subnet issue may be a problem there as well.

We are currently using PowerAdmin 2.1.7 to manage a PowerDNS 3.4.8 instance with a MySQL 5.1.73 backend.

H. Demby

**Comment by edmondas** [comment]
I can't reproduce this with the latest code or I'm doing something wrong. In case the issue persists, please reopen.
