### ISSUE TITLE
Default value for use_ldap in MySQL 5.7 generates an error

### ISSUE THREAD

**Issue by Guyverix** [poweradmin/poweradmin#289]
Fresh install this morning using nginx, and PHP5.6 (non Ubuntu repo) On Ubuntu 16.  
Running MySQL 5.7.15.  (repo build)
PDNS 4.0.0~alpha2-3build1 (repo build)

Adding a backup user generated a MySQL error due to this value:
 `use_ldap` int(1) NOT NULL, in create table `users`

 describe users;
+-------------+---------------+------+-----+---------+----------------+
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+
| use_ldap    | int(1)        | NO   |     | NULL    |                |

Here is the exact insert statement that failed.  ( don’t care about the password hash, as I am going to nuke and reinstall again shortly after I understand the UI better)
INSERT INTO users (username,
    ->  password,
    ->  fullname,
    ->  email,
    ->  description,
    ->  perm_templ,
    ->  active) VALUES ('failSafe',
    ->  'b8bafc78c6808c4ca01132ea3313b4ae',
    ->  'Fail Safe',
    ->  'root@iwillfearnoevil.com',
    ->  'backup user due to not understanding this software very well yet.',
    ->  '1',
    ->  '1');
ERROR 1364 (HY000): Field 'use_ldap' doesn't have a default value

My fix for this was very heavy handed since I do not know your code well:
alter table users alter `use_ldap` SET DEFAULT 0;

**Comment by mzch** [comment]
I have a same problem.

-- for example
The following query generated an error:
INSERT INTO users (username,
 password,
 fullname,
 email,
 description,
 perm_templ,
 active) VALUES ('newuser',
 '9999999999999999999999999999',
 'XXXXXXXXXX',
 'example@example.jp',
 '',
 '2',
 '1')

SQLSTATE[HY000]: General error: 1364 Field 'use_ldap' doesn't have a default value

**Comment by houtknots** [comment]
Same problem here anyone does anyone have a fix for this?

**Comment by belgotux** [comment]
Hello,
I've got the same error with a fresh poweradmin v 2.1.8. Doesn't use LDAP, impossible to add a user :
```
The following query generated an error:

INSERT INTO users (username,
 password,
 fullname,
 email,
 description,
 perm_templ,
 active) VALUES ('toto',
 'da832c50e281fd1963a522c27c8ce2ca',
 'toto',
 'toto@tata.be',
 '.',
 '1',
 '1')

SQLSTATE[HY000]: General error: 1364 Field 'use_ldap' doesn't have a default value
```
When I see the describe on the table users, 'use_ldap' is required without default, it's missed on the creation request.

I've done manually this request and it works : 
```
INSERT INTO users (username,
 password,
 fullname,
 email,
 description,
 perm_templ,
 active,**use_ldap**) VALUES ('toto',
 'da832c50e281fd1963a522c27c8ce2ca',
 'toto',
 'toto@tata.be',
 '.',
 '1',
 '1',
 **'0'**);
Query OK, 1 row affected (0.01 sec)
```

**Comment by zod076** [comment]
I've the same problem with master v2.1.8 & MariaDB 5.10.11. The method @Guyverix posted above fixes it.

**Comment by Guyverix** [comment]
Sigh, 5 years and it is not fixed in the package yet.. At least we have a simple enough fix for the bug here when people google for this problem.

**Comment by lfasci** [comment]
A workaroud is to edit the table 
ALTER TABLE `users` CHANGE `use_ldap` `use_ldap` INT(1) NULL;
