### ISSUE TITLE
More Than One Underscore In Hostname Causes Creation Of Null Records In Records Table

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [poweradmin/poweradmin#290]
Anytime a new record is added, it creates a partial duplicate null record without the first underscore prefix if not already in the database.

![Example](https://s18.postimg.org/ogmw11815/image.png)

MariaDB 10.0.27
PowerDNS 4.0.1
PowerAdmin (latest git)

**Comment by shaundma** [comment]
I see something similar:
For records with more than 3 levels, like: level4.level3.domain.tld I see an extra NULL record level3.domain.tld
Just search the database for records with NULL as record.type, I have 300 NULL records
I havent had time to chase it down to the cause yet.

**Comment by edmondas** [comment]
I am unable to reproduce it with the latest code.
