### ISSUE TITLE
unable to delete records.

### ISSUE THREAD

**Issue by Amolmahajan7** [poweradmin/poweradmin#293]
Hello,

I am unable to delete the records with poweradmin-2.1.7, I have set full permissions to the admin still getting error as below.

Error: You do not have the permission to edit this record.

Is there any way to fix it.

Regards,
Amol

**Comment by SebTM** [comment]
Were you able to fix it? It seems to be an enviroment problem as you are the only one occuring this problem.

**Comment by edmondas** [comment]
Closing as no additional information was provided
