### ISSUE TITLE
Template ID for Admin is incorrect (completely new install)

### ISSUE THREAD

**Issue by madpsy** [poweradmin/poweradmin#297]
I just installed 2.1.8 for the first time, after running through the install I logged in as 'admin'.

Once logged in the user had no permissions to do anything (the list was literally Index, User Admin, Logout). Browsing to 'User administration' produced this error:

`PHP Notice:  Undefined variable: userlist in /var/www/html/poweradmin/inc/plugins/users_local/users_local.plugin.php on line 572`

After some debug it seemed the SQL query was expecting ID '1' in the `perm_templ` table. The following fixed it:

`UPDATE `perm_templ` SET `id` = '1' WHERE `perm_templ`.`id` = 2;`

Unsure if that's the correct fix but it seems to work.

**Comment by madpsy** [comment]
I believe the problem is caused by the Galera based SQL backend. 

https://mariadb.org/auto-increments-in-galera/

The workaround would be to not rely on auto increment for the admin user during install.

**Comment by edmondas** [comment]
I confirm that there are hardcoded ids in the queries used to create the new admin user and his permissions.
