### ISSUE TITLE
Are there any plans to support PHP7?

### ISSUE THREAD

**Issue by goocastro** [poweradmin/poweradmin#298]
I created a new ubuntu 16.04 instance to test PowerDNS and ended up with php7.0 + PowerAdmin. The installation process failed with some PHP7 backward incompatible code

````
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /usr/share/php/MDB2.php on line 390
````

Are there any plans to support PHP7?

**Comment by pnunn** [comment]
Just hit exactly the same thing.. managed to fix some things but now have hit a missing function in MDB2 so I've hit a wall.

**Comment by edmondas** [comment]
Not sure which version of PowerAdmin you are using but you should switch to PDO database access layer. Check what is the value of $db_layer variable in your configuration file (inc/config.inc.php). Set it to 'PDO' or remove this line.
```
$db_layer='PDO'
```

**Comment by pnunn** [comment]
Thank you Edmondas,

That now has it working just fine.

Peter

-- 
Peter Nunn
Director, InfoTeq Pty. Ltd.
pnunn@intq.it
0412 174 230
03 9017 2707


Edmondas Girkantas wrote:
