### ISSUE TITLE
Missing update info from older versions (2.1.3 -> 2.1.4)

### ISSUE THREAD

**Issue by cmol** [poweradmin/poweradmin#299]
Hi

I am missing the update info from 2.1.3 to 2.1.4 (so I can upgrade a installation to the latest). Is it possible to add this to the wiki?

/ Claus

**Comment by edmondas** [comment]
Just added migration steps for [2.1.4 release](../wiki/v2.1.4).
I hope they are correct.

**Comment by cmol** [comment]
Great! Thank you! I'll let you know if there is any problems when I get around to do the upgrade.
