### ISSUE TITLE
poweradmin stripping quotes (but only in web interface)

### ISSUE THREAD

**Issue by whohoho** [poweradmin/poweradmin#301]
When adding for ex. a TXT records which is already in quotes, and then editing it again (to add quotes). It will have multiple quotes in the powerdns database, like this:

[Warning] Parsed and original record content are not equal: _blablabla IN TXT '"""""0 5 25 blablabla."""""' (Content parsed as '"" "" "0 5 25 blablabla." "" ""')

**Comment by whohoho** [comment]
also:

[Error] Following record had a problem: test.test.com IN TXT ""testje""
[Error] Error was: Parsing record content: Data field in DNS should start with quote (") at position 2 of '""testje""'

**Comment by edmondas** [comment]
It cannot be reproduced with the latest code.
