### ISSUE TITLE
ERROR:  null value in column "zone_templ_id" violates not-null constraint (PgSQL)

### ISSUE THREAD

**Issue by louismclennan** [poweradmin/poweradmin#308]
Added poweradmin to an existing database.

The following query generated an error:
INSERT INTO zones (domain_id,
 owner,
 comment)
				VALUES('539',
1,
'')

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "zone_templ_id" violates not-null constraint
DETAIL:  Failing row contains (316, 539, 1, , null).

```
inc\record.inc.php Line 341
-            $query = "INSERT INTO zones (domain_id, owner, comment)
-				VALUES(" . $db->quote($zone_id, 'integer') . ",1," . $db->quote($comment, 'text') . ")";
+           $query = "INSERT INTO zones (domain_id, owner, comment, zone_templ_id)
+				VALUES(" . $db->quote($zone_id, 'integer') . ",1," . $db->quote($comment, 'text') . ",0)";
```

**Comment by almereyda** [comment]
Would you want to turn your patch into a PR?

**Comment by LeePorte** [comment]
I've created a PR https://github.com/poweradmin/poweradmin/pull/323
