### ISSUE TITLE
how to set up LDAP if you don't need a bind user/password?

### ISSUE THREAD

**Issue by c0t0d0s2** [poweradmin/poweradmin#310]
I hope this question isn't too stupid.

My ldap setup doesn't require a bind user/password.  Can i still use LDAP in a setting like this?  When I omit the bindpasswd/user it errors out.

**Comment by edmondas** [comment]
@c0t0d0s2 It might be possible to set those settings to null:
```
$ldap_binddn = null;
$ldap_bindpw = null;
```
Then I expect they will be handled as optional arguments within the ldap_bind function call.
