### ISSUE TITLE
Bug:  Performance Update For Template - Slow SQL

### ISSUE THREAD

**Issue by bbearman** [poweradmin/poweradmin#311]
// inc/record.inc.php  [1920]
// Dependent subquery way too slow for large recordsets
//$db->exec("DELETE FROM records WHERE id IN (SELECT record_id FROM records_zone_templ WHERE "
//        . "domain_id = " . $db->quote($zone_id, 'integer') . " AND "
//        . "zone_templ_id = " . $db->quote($zone_template_id, 'integer') . ")");
//$db->exec("DELETE FROM records_zone_templ WHERE domain_id = " . $db->quote($zone_id, 'integer'));

// Manually get the id from records_zone_templ
$result = $db->query("SELECT record_id FROM records_zone_templ WHERE domain_id = " . $db->quote($zone_id, 'integer') . " AND zone_templ_id = " . $db->quote($zone_template_id, 'integer'));
$record_ids = array();
while ($record = $result->fetchRow()) {
    $record_ids[]=$record['record_id'];
}

// Remove all template based records for the zone
$db->exec("DELETE FROM records WHERE id IN (" . implode(',', $record_ids) . ")");
$db->exec("DELETE FROM records_zone_templ WHERE domain_id = " . $db->quote($zone_id, 'integer'));

**Comment by ktims** [comment]
What RDBMS are you using? I can't imagine your optimization making any difference at all in the query plan, except that now it has to return the intermediate results to PHP first. I don't use zone templates so I don't really have test data for this, but I don't see why your way would be any faster.

However neither `records.record_id` nor any fields in `records_zone_templ` are indexed in my schema, so both the subselect and the delete would require sequence scans. If your `records` table is large, this could be a problem.

Can you run an `EXPLAIN` or `EXPLAIN ANALYZE` on the query in question in your DBMS?

**Comment by bbearman** [comment]
It will run on database instances with a lot of hardware, but still slower than it could be. The instance I am using is a development instance of mysql. It has low resources, but will still be a problem on my larger production datasets.

```
explain DELETE FROM records WHERE id IN (SELECT record_id FROM records_zone_templ WHERE domain_id = '659' AND zone_templ_id = '1');
+----+--------------------+--------------------+------+---------------+------+---------+------+--------+-------------+
| id | select_type        | table              | type | possible_keys | key  | key_len | ref  | rows   | Extra       |
+----+--------------------+--------------------+------+---------------+------+---------+------+--------+-------------+
|  1 | PRIMARY            | records            | ALL  | NULL          | NULL | NULL    | NULL | 176376 | Using where |
|  2 | DEPENDENT SUBQUERY | records_zone_templ | ALL  | NULL          | NULL | NULL    | NULL | 124602 | Using where |
+----+--------------------+--------------------+------+---------------+------+---------+------+--------+-------------+
```
When you change using the suggested code

```
explain SELECT record_id FROM records_zone_templ WHERE domain_id = '659' AND zone_templ_id = '1'
    -> ;
+----+-------------+--------------------+------+---------------+------+---------+------+--------+-------------+
| id | select_type | table              | type | possible_keys | key  | key_len | ref  | rows   | Extra       |
+----+-------------+--------------------+------+---------------+------+---------+------+--------+-------------+
|  1 | SIMPLE      | records_zone_templ | ALL  | NULL          | NULL | NULL    | NULL | 124602 | Using where |
+----+-------------+--------------------+------+---------------+------+---------+------+--------+-------------+
```
1 row in set (0.00 sec)

```
explain DELETE FROM records WHERE id IN (200061,200062,200063,200064,200065,200066,200067,200068);
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------------+
| id | select_type | table   | type  | possible_keys | key     | key_len | ref   | rows | Extra       |
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------------+
|  1 | SIMPLE      | records | range | PRIMARY       | PRIMARY | 4       | const |    8 | Using where |
+----+-------------+---------+-------+---------------+---------+---------+-------+------+-------------+
```

I also made another improvement to this issue by adding the index `search_templ` (`domain_id`,`zone_templ_id`) on records_zone_templ.

**Comment by ktims** [comment]
Have you tested and confirmed there is a real performance issue here? I know the MySQL query planner sucks with anything but naïve queries, but it should be smart enough to plan this pretty trivial one properly; it's a simple JOIN; in which case keeping it in SQL should actually be faster. If that's not the case (it appears to ignore the indexes with the subquery, which is...broken? can you hint it?), this isn't my project, but I would personally hesitate to kludge around in application logic to improve performance on a particular DBMS. As written, the query is clear and should perform slightly better on a competent DBMS. Rewriting it as an explicit JOIN might help the crappy MySQL query planner and not result in a kludge.

FWIW, I vote against this change, though indexing `records_zone_templ` might help and make sense, and if a performance issue is demonstrated and fixed with an explicit JOIN I would support that as well.

**Comment by bbearman** [comment]
Yes, it took over 10 minutes, I had to kill off nginx and the mysql thread. Wasting too much time waiting. A join would be fine.

$db->exec("DELETE r, rzt FROM records r LEFT JOIN records_zone_templ rzt ON r.id = rzt.record_id WHERE "
                        . "rzt.domain_id = " . $db->quote($zone_id, 'integer') . " AND "
                        . "rzt.zone_templ_id = " . $db->quote($zone_template_id, 'integer'));
$db->exec("DELETE FROM records_zone_templ WHERE domain_id = " . $db->quote($zone_id, 'integer'));

**Comment by clusterx** [comment]
thanks bbearman,
same here, an IP address update in a template took about 1 hour for 20 zones ...
your SQL JOIN has worked for for me (400 zones within 2 minutes)!
`$db->exec("DELETE r, rzt FROM records r LEFT JOIN records_zone_templ rzt ON r.id = rzt.record_id WHERE "
. "rzt.domain_id = " . $db->quote($zone_id, 'integer') . " AND "
. "rzt.zone_templ_id = " . $db->quote($zone_template_id, 'integer'));`
