### ISSUE TITLE
Poweradmin prevents to set a NULL MX (RFC 7505)

### ISSUE THREAD

**Issue by Darkspirit** [poweradmin/poweradmin#312]
According to the SMTP specification, it should be assumed that the host itself (AAAA/A) is willing to receive email if there aren't any MX records. One can set a NULL MX (RFC 7505) to indicate that receiving email is not wanted.
example.com IN MX 0 . (dot as hostname)

Such a dot to "deactivate" a service can also be set within SRV records.
https://tools.ietf.org/html/rfc7505#section-3

Poweradmin's red error message: "Error: You have invalid characters in your hostname."

**Comment by Darkspirit** [comment]
in `/inc/dns.inc.php`
under
`function is_valid_hostname_fqdn(&$hostname, $wildcard) {`
is
`$hostname = preg_replace("/\.$/", "", $hostname);`

You could make it so to fix this issue:
```
if ($hostname == ".") { return true; }
$hostname = preg_replace("/\.$/", "", $hostname);
```

**Comment by ktims** [comment]
Bump? We hit this today, it would be nice to have an in-tree fix.

**Comment by edmondas** [comment]
@Darkspirit thanks for the fix, code added to the master.
