### ISSUE TITLE
Can't edit SOA record

### ISSUE THREAD

**Issue by MehdiAmin** [poweradmin/poweradmin#313]
i can't edit SOA record at all. Even if I don't change anything and just click commit changes!.
I have tried both Poweradmin v2.1.7 and 2.1.8

Here is the error message.

Error: Your content field doesnt have a legit value.

And this is the value in content field
ns1.int.mydomain.com hostmaster 2017033030 300 600 86400 300

**Comment by kamilko** [comment]
You probably have wrong value `hostmaster`. It should be: hostmaster.int.mydomain.com (first dot after hostmaster represents @). Then commit changes would work.

**Comment by edmondas** [comment]
The *inc/config.inc.php* must have dns_hostmaster defined (it cannot be empty). A bug in the installer caused hostmaster settings to be lost.
