### ISSUE TITLE
SOA format seems wrong

### ISSUE THREAD

**Issue by MehdiAmin** [poweradmin/poweradmin#314]
We I create a new zone, the SOA records is like this:

98 	int.mydomain.com 	SOA 	2017033030 300 600 86400 300

Which is missing "name-server" and "responsible person" fields. It cause issues when using this zone as secondary or stub in Microsoft DNS server.

I think the correct format is something like :

primary hostmaster serial refresh retry expire default_ttl

I have tried both Poweradmin v2.1.7 and 2.1.8

**Comment by Moke** [comment]
Did you configure the dns server and email address in the config files properly?

**Comment by poustchi** [comment]
I don't know what exactly you're refering too. Can you please explain more?

**Comment by edmondas** [comment]
The *inc/config.inc.php* must have dns_hostmaster defined (it cannot be empty). A bug in the installer caused hostmaster settings to be lost.
