### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /usr/share/php/MDB2.php on line 390, referer: http://#/poweradmin/install/

### ISSUE THREAD

**Issue by GronbergInfo** [poweradmin/poweradmin#315]
I am using php 7 since it was the only available for ubuntu what i found.
This is at step 6, and the install gets stuck.

PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /usr/share/php/MDB2.php on line 390, referer: http://#/poweradmin/install/

**Comment by itvdonsk** [comment]
I also ran into this problem with php7

**Comment by yourchoice** [comment]
Warning: count(): Parameter must be an array or an object that implements Countable in \Php7\pear\MDB2.php on line 826

Notice: Only variables should be assigned by reference in \Php7\pear\MDB2.php on line 578
DB_DataObject Error: Connect failed, turn on debugging to 5 see why

**Comment by dynamicfun** [comment]
Same error for me 
Warning: count(): Parameter must be an array or an object that implements Countable in \Php7\pear\MDB2.php on line 826

any suggest?

**Comment by elangovanshanthi** [comment]
It will help to resolve the issue

```
pear upgrade
pear channel-update pear.php.net
```

**Comment by trecakov** [comment]
any updates on this?

**Comment by edmondas** [comment]
MDB2 dependency was removed in a recent release.

**Comment by bbslucky** [comment]
pear upgrade MDB2-beta 
is very slow ......
and no repond..

**Comment by bbslucky** [comment]
PHP 7.3.25 (cli) (built: Nov 24 2020 14:31:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group

**Comment by Rinaldini** [comment]
Downloaded the library on July 19. The problem is similar.
PHP Parse error: syntax error, unexpected 'new' (T_NEW) in .../php/MDB2.php on line 390

**Comment by edmondas** [comment]
@Rinaldini @bbslucky MDB2 library is no longer needed. The requirements can be found here https://github.com/poweradmin/poweradmin#requirements
