### ISSUE TITLE
 Uncaught Error: Call to undefined function _() in 'inc/error.inc.php' ?

### ISSUE THREAD

**Issue by Kahsolt** [poweradmin/poweradmin#316]
Thanks for your work but the time I try to install, I got this error in apache's log...

> [Mon Jun 19 11:15:23.171724 2017] [php7:error] [pid 31103] [client 60.207.237.78:7193] PHP Fatal error:  Uncaught Error: Call to undefined function _() in /srv/http/poweradmin/inc/error.inc.php:25\nStack trace:\n#0 /srv/http/poweradmin/inc/toolkit.inc.php(43): require_once()\n#1 /srv/http/poweradmin/index.php(32): require_once('/srv/http/power...')\n#2 {main}\n  thrown in /srv/http/poweradmin/inc/error.inc.php on line 25

I guess the function _() is meant to deal with annoying charsets, but cannot find where it is.
Did I miss any php extension? : )

ENV:
- arch linux
- apache2.4.25
- php7.1.6
- poweradmin2.1.7 release

**Comment by Kahsolt** [comment]
uhmm, I fixed it by accident after I installed php-mcrypt and php-gettext module...

**Comment by SebTM** [comment]
As you found out, the "_("-function is part of php-gettext (https://secure.php.net/_). The system-requirements for poweradmin (should) be checked at setup.

I'm not quite sure if it is "good practice" if we check it on every page-call?

**Comment by roffe** [comment]
Solved my problem when i was updating PHP and forgott --with-gettext as compile flag..

Thanks for excelent work on poweradmin!
