### ISSUE TITLE
upgrading from 2.1.7

### ISSUE THREAD

**Issue by fsantiago07044** [poweradmin/poweradmin#317]
if i wish to upgrade to the latest 2.1.8 dev version from 2.1.7, aside from cloning the git and copying the config file (or its pertinent contents), are there any other upgrade steps? 

any db changes or otherwise steps to complete as well? Thanks.

**Comment by SebTM** [comment]
I think you are right - this should do the job. I had a quick look into the migrations it seems that nothing changed here since 4 years.

**Comment by edmondas** [comment]
There is a requirement for PHP >=7.2.0. As for other changes, they relate to refactoring code and bug fixes.
