### ISSUE TITLE
Direct domain.com to www.domain.com using CNAME

### ISSUE THREAD

**Issue by seemakaloor** [poweradmin/poweradmin#318]
Hi,
I am not able to insert a CNAME record to direct domain.com requests to www.domain.com. I am using poweradmin to manage Powerdns. 
I try adding a new record, and in the name box I left blank. In the content box I provided 'www.domain.com', but it gives error saying 'blank CNAMES are not valid'.

How can I configure this?

Thanks,
Seema

**Comment by lbr88** [comment]
You can't have a CNAME as a root record for your domain. This is because a CNAME record can't co-exist with other records like SOA and NS which are rather important.

**Comment by Moke** [comment]
You should use "www.domain.com IN CNAME domain.com", and set "domain.com IN A 127.0.0.1"
