### ISSUE TITLE
command injection

### ISSUE THREAD

**Issue by setharnold** [poweradmin/poweradmin#319]
https://github.com/poweradmin/poweradmin/blob/772946ad40c765fece19aafbefd04fa23745e8ec/inc/dnssec.inc.php#L118

```
$command = $pdnssec_command . " rectify-zone " . $domain;
[...]
exec($command, $output, $return_code);
```

This sequence of code means all domain names are roughly root-equivalent. (Or whichever user is running this code.)

Are all domains on the system created by root? Or can 'untrusted' users create domains?

Thanks

**Comment by Moke** [comment]
I am not sure i understand this. Your web server should not be run as root, it should be run as apache/nginx/nobody/other. 

This code doesn't create the domain, it just generates the information needed to create it. The "domain owner" bit is stored in the SQL database. This process is entirely separate from the Linux system user that runs the command.

**Comment by edmondas** [comment]
Poweradmin runs pdnsutil as www user, so you need to grant access to the pdns.conf file for that. However, it is only required for DNSSEC operations. Poweradmin also includes user management, which enables you to control access rights. Untrusted users can create domains from the web interface.
