### ISSUE TITLE
SQLITE, Unable to connect to the database server.

### ISSUE THREAD

**Issue by ramiil-kun** [poweradmin/poweradmin#321]
Trying to install current version, PowerAdmin said:

Installation step 4

Updating database... Unable to connect to the database server. Please report the problem to an Administrator.

pdo_sqlite installed

**Comment by ramiil-kun** [comment]
SELinux should be disabled. My bad.

**Comment by BaseMax** [comment]
Hi,

Similar problem in FreeBsd:

PHPMyAdmin works as well for `root` and `powerdns` user. (PHPMyAdmin run on same PHP version and `php.ini`, nginx config)

Also `$ mySQL -u root -p` and `$ mySQL -u powerdns -p` works as well.
Buy PowerAdmin show:

```
Unable to connect to the database server. Please report the problem to an Administrator.
```

But in console:

##### root@base:/usr/local/www/nginx/pdns # php index.php
```
could not find driver
Unable to connect to the database server. Please report the problem to an Administrator.
```


I see `could not find driver`...

So finally, Solved by: `pkg install php74-pdo_sqlite php74-pdo_odbc php74-pdo_mysql`

Regards,
Max
