### ISSUE TITLE
I can not require_once the ('../inc/i18n.inc.php') file in the `poweradmin/install/index.php`

### ISSUE THREAD

**Issue by liaodalin19903** [poweradmin/poweradmin#327]
```
<?php
echo "liao-0";  # this line will echo to browser screen.
require_once('../inc/i18n.inc.php');
echo "liao-1";   # this line will not echo to browser screen.
require_once('../inc/error.inc.php');
```

You see, I add two test line in the front and behind of the line:
```
    require_once('../inc/i18n.inc.php');
```

why I can not require_once it?

**Comment by SebTM** [comment]
Please enable debugging in your php.ini-configuration (error_reporting = E_ALL | display_errors = "1"). We can only support you if you provide us an error - please check also the error logs.
