### ISSUE TITLE
RFE: reject / warn about inconsistent ttls

### ISSUE THREAD

**Issue by jsoref** [poweradmin/poweradmin#331]
If a user creates two records:
foo 60 IN TXT "hello"
foo 600 IN TXT "world"
poweradmin should warn the user that this isn't valid.

fwiw, I'm using 772946a

Specifically, whichever change the user is trying to make should be rejected with an explanation.

**Comment by edmondas** [comment]
The issue has been resolved after the pull request #334 has been merged.
