### ISSUE TITLE
RFE: reject/warn about any records in addition to a CNAME for a name

### ISSUE THREAD

**Issue by jsoref** [poweradmin/poweradmin#332]
If a user creates two records:
foo 600 IN CNAME "hello"
foo 600 IN TXT "world"
poweradmin should warn the user that this isn't valid.

fwiw, I'm using 772946a

Specifically, whichever change the user is trying to make should be rejected with an explanation.

For reference, `pdnsutil check-zone` would report:
`[Error] CNAME foo found, but other records with same label exist.`

**Comment by edmondas** [comment]
As a result of merging pull request #334, the issue has been resolved.
