### ISSUE TITLE
ldap bind failure

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#335]
Please, switch strings on 104-105 in inc/auth.inc.php. You set protocol version after binding. That's why it cannot bind and gets bind failure.

**Comment by SebTM** [comment]
Can you provide an PR?

**Comment by poluruh** [comment]
hi I am unable to authenticate ldap $ldap_use = true;
$ldap_debug = true;
$ldap_uri = 'ldap://ldap hostname:389';
$ldap_basedn = 'DC=dns,DC=com';
$ldap_binddn = 'uid=%s,cn=users,cn=compact,dc=dns,dc=com';
$ldap_bindpw = 'pasword';
$ldap_user_attribute = 'sAMAccountName';
$ldap_proto = 3;

**Comment by edmondas** [comment]
The configuration depends on the type of LDAP you use.

Using OpenLDAP, your config will be as follows:
```
$ldap_use = true;
$ldap_uri = 'ldap://ldap hostname'; // The port number is not required
$ldap_basedn = 'cn=users,cn=compact,dc=dns,dc=com; // the place where users are kept
$ldap_binddn = 'cn=admin,dc=dns,dc=com'; // full DN of admin user
$ldap_bindpw = 'pasword'; // admin's password
$ldap_user_attribute = 'uid'; // filter attribute
$ldap_proto = 3;
```
