### ISSUE TITLE
php 7.2 no mcrypt ext

### ISSUE THREAD

**Issue by j4Hu** [poweradmin/poweradmin#336]
mcrypt extension was removed from new php release.
poweradmin ends with error: "Error: You have to install PHP mcrypt extension!"

https://wiki.php.net/rfc/mcrypt-viking-funeral

deprecated in 7.1:
http://php.net/manual/en/migration71.deprecated.php
" The mcrypt extension has been abandonware for nearly a decade now, and was also fairly complex to use. It has therefore been deprecated in favour of OpenSSL, where it will be removed from the core and into PECL in PHP 7.2. "

**Comment by j4Hu** [comment]
i proposed PR https://github.com/poweradmin/poweradmin/pull/337

**Comment by tunage** [comment]
Same issue

**Comment by SebTM** [comment]
Fixed with PR #337
