### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by ogiraz** [poweradmin/poweradmin#338]
installed the latest version but unable to login.
tried $password_encryption='md5'; but no luck

i can successfully login mysql and query with same credentials through console 
any idea?

**Comment by ogiraz** [comment]
fyi, the version that comes with git clone has this problem. 2.1.7 from sourceforge works ok.
my environment details:
ubuntu 16.04
Server version: 5.7.20-0ubuntu0.16.04.1 (Ubuntu):
innodb_large_prefix=on
innodb_log_file_size = 64M
(rest default)
nginx/1.10.3 (Ubuntu)
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by SebTM** [comment]
It's hard to debug here - can you write me an email with your contact details - if you can give me access to the server, I would have a look at it.

**Comment by edmondas** [comment]
Closing as no additional information was provided.
