### ISSUE TITLE
Dynamic_Update.php only giving badauth2

### ISSUE THREAD

**Issue by citynetcomputing** [poweradmin/poweradmin#340]
Hello,

Trying to use the dynamic update script with ddclient but no matter what i do i get badauth2 returned. Am I using this wrong or something. Can someone shed some light on how to use this?

Server is apache2 with rewrites for /nic/update etc.
Tried on SSL and non SSL
Tried adding single quotes to username and password
heeelp... ;)

**Comment by edmondas** [comment]
Added documentation https://github.com/poweradmin/poweradmin/wiki/Dynamic-DNS
