### ISSUE TITLE
Warning: openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected

### ISSUE THREAD

**Issue by skeyby** [poweradmin/poweradmin#341]
Hello everybody.

I recently upgraded power admin and this warning started popping out:

Warning: openssl_decrypt(): IV passed is 32 bytes long which is longer than the 16 expected by selected cipher, truncating in [...]/inc/plugins/auth_local/auth_local.plugin.php on line 186

I've seen there's a recent commit on that file and have found some issues on other projects about switching from substr to mb_substr, but I'm not sure this is the case... Just an hint.

If I have some free time I'll try to fix it later and maybe commit something.

**Comment by pentacore** [comment]
any news?

**Comment by lcossin** [comment]
Hi,

A suggested fix in #353 

Regards,
Laurent

**Comment by edmondas** [comment]
@lcossin thanks for suggested fix.

**Comment by mubeenakhter27** [comment]
<?php
$plaintext = 'My secret message 1234';
$password = '3sc3RLrpd17';
$method = 'aes-256-cbc';

// Must be exact 32 chars (256 bit)
$password = "D9232D03775982FBE8C495EDA653883E4D2F088ECD9900F36DC71448AB90A3A5";
//echo "Password:" . $password . "n";
$str = $password;

$arr2 = str_split($str, 2);
$password_hex = NULL;
// print_r($arr2);
for($i = 0;$i < count($arr2); $i++ ){
 $password_hex = $password_hex . chr(hexdec($arr2[$i]));
}

// IV must be exact 16 chars (128 bit)
$iv = '3EF0DB92779DEF0A14CC556D97634C8F';

//echo "Password:" . $password . "n";
$str = $iv;

$arr2 = str_split($str, 2);
$iv_hex = NULL;
// print_r($arr2);
for($i = 0;$i < count($arr2); $i++ ){
 $iv_hex = $iv_hex . chr(hexdec($arr2[$i]));
}

// av3DYGLkwBsErphcyYp+imUW4QKs19hUnFyyYcXwURU=
$encrypted = "QlZfJeKA35SxWE9ZOdubTQ==";

// My secret message 1234
echo $decrypted = openssl_decrypt(base64_decode($encrypted), $method, $password_hex, OPENSSL_RAW_DATA, $iv_hex);

// echo 'plaintext=' . $plaintext . "n";
// echo 'cipher=' . $method . "n";
// echo 'encrypted to: ' . $encrypted . "n";
//echo 'decrypted to: ' . $decrypted . "n";
?>
