### ISSUE TITLE
cannot go beha

### ISSUE THREAD

**Issue by weishenaustralia** [poweradmin/poweradmin#342]
After poweradmin is configured. I 'can' login, but after login, i was still on the login page(the exact page before i login), cannot proceed to another page.
checking /var/log/messages, i can see "Feb 14 12:39:10 localhost poweradmin: Successful authentication attempt from [172.16.150.211] for user 'admin'"

anything extra logfiles i can check?

(following https://www.rosehosting.com/blog/install-powerdns-and-on-a-centos-7-vps/ to setup)

thanks.

**Comment by edmondas** [comment]
You should check your log files in the _/var/log/php-fpm/_ and _/var/log/nginx/_ folders. I tested installation of master branch under CentOS 8 and it should work.
