### ISSUE TITLE
Recommended commit / tag for use with PHP7.0

### ISSUE THREAD

**Issue by firthmj** [poweradmin/poweradmin#345]
Hi,

It has been a very long time since the V2.1.7 release, and though [this ](https://github.com/poweradmin/poweradmin/issues/274)thread said that V2.1.8 was being prepared for release two years ago, it doesn't seem to be out yet.

It seems that V2.1.7 requires the obsolete PHP "mysql" backend, rather than the newer "mysqli" version, so won't run on (at least some) platforms that now distribute PHP 7.0 (e.g. Ubuntu 16.04)

Is there a recommended semi-stable GIT commit or tag that will support PHP 7.0 (and recent versions of Ubuntu / Debian in particular), or is there a patch to V2.1.7 that will change the MySQL driver to the newer one?

**Comment by edmondas** [comment]
For PHP 7.0 compatibility, please use the master branch. It is expected that a new release will be made in the coming weeks.
