### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by yppei** [poweradmin/poweradmin#346]
As the title says, the demo on http://demo.poweradmin.org/ does not work.
Only getting an error saying:

> # Forbidden
> 
> ### You don't have permission to access /cgi-bin/smokeping.cgi on this server.

**Comment by genofire** [comment]
Over a year now :( - i wish there are some up to date screenshots or so ;(

**Comment by edmondas** [comment]
The UI hasn't changed too much (you can find pictures in Google search).

Since there are plans to rewrite entire system from the scratch, so now I see no point of demo environment.

**Comment by genofire** [comment]
Then delete it form README  ...

**Comment by edmondas** [comment]
Reference to demo environment removed, thanks.
