### ISSUE TITLE
FAIL TO INSTALL step 4

### ISSUE THREAD

**Issue by kaaaq** [poweradmin/poweradmin#354]
in the step4 of installation it stops installation and it writes "UPDATING DATABASE..."

**Comment by kaaaq** [comment]
how can i do for this problem???

**Comment by ps29** [comment]
Try to provide correct credential to mysql 
use root user of database and provide password of that root user too

**Comment by edmondas** [comment]
You can also check error log file of your HTTP server for more details.

**Comment by kapoorsarthak** [comment]
I have the same problem i am putting the correct details then also the same error

**Comment by edmondas** [comment]
Since no details were provided, I am closing this.
