### ISSUE TITLE
Issue with templates

### ISSUE THREAD

**Issue by houtknots** [poweradmin/poweradmin#355]
When I try to add an record to an template i get the following error

The following query generated an error:
INSERT INTO zone_templ_records (zone_templ_id,
 name,
 type,
 content,
 ttl,
 prio) VALUES ('1',
'test',
'A',
'1.1.1.1',
'86400',
'')

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'prio' at row 1

**Comment by bretton** [comment]
Make sure you have a value set in the priority field when adding an entry to a template. it fails with the error above if priority is empty
