### ISSUE TITLE
No default value for use_ldap.

### ISSUE THREAD

**Issue by kiwichrish** [poweradmin/poweradmin#356]
Hi-ho,

Moving my master to Ubuntu 18.04 and got the following on a clean install of pdns / poweradmin.

(php 7.2.10 mysql 5.7.24)

  SQLSTATE[HY000]: General error: 1364 Field 'use_ldap' doesn't have a default value

In file sql/poweradmin-mysql-db-structure.sql

Definition for the field needs to have a default.

Can't remember what version of SQL added the requirement but if you've got NOT NULL you have to have a default now...  I think Ubuntu 16.04 does the same.

**Comment by kiwichrish** [comment]
Actually.. Should have thought before I typed. :-)  There is a default, of NULL implicit but it can't be null as not-null is set.  Changed default to be '0';

**Comment by edmondas** [comment]
duplicate to #289
