### ISSUE TITLE
powerdns 4.2 records表没有change_date字段导致添加master zone失败

### ISSUE THREAD

**Issue by x-hezhang** [poweradmin/poweradmin#359]
问题：从powerdns 4.2开始，mysql的table scheme中records表缺少了change_date字段，导致poweradmin添加master zone失败。

解决方法: 手动添加change_date字段。

CREATE TABLE records (
  id                    BIGINT AUTO_INCREMENT,
  domain_id             INT DEFAULT NULL,
  name                  VARCHAR(255) DEFAULT NULL,
  type                  VARCHAR(10) DEFAULT NULL,
  content               VARCHAR(64000) DEFAULT NULL,
  ttl                   INT DEFAULT NULL,
  prio                  INT DEFAULT NULL,
  change_date           INT DEFAULT NULL,
  disabled              TINYINT(1) DEFAULT 0,
  ordername             VARCHAR(255) BINARY DEFAULT NULL,
  auth                  TINYINT(1) DEFAULT 1,
  PRIMARY KEY (id)
) Engine=InnoDB CHARACTER SET 'latin1';

**Comment by ps29** [comment]
Thanks for this hint , really helped me out

**Comment by rafis** [comment]
ALTER TABLE records ADD COLUMN change_date INT DEFAULT NULL;
