### ISSUE TITLE
no templates to install

### ISSUE THREAD

**Issue by exebits** [poweradmin/poweradmin#362]
When installing, I have the error "The 'templates' directory does not exist".
Tell me, please, where can I get these templates?
/templates
header.html
step1.html
step2.html
step3.html
step4.html
footer.html
....

**Comment by edmondas** [comment]
I restored installer templates that were removed by accident.

**Comment by exebits** [comment]
> I restored installer templates that were removed by accident.
Thank. The installation was successful. But after authorization I have a new error:
Fatal error: Class 'Twig_Loader_Filesystem' not found in /var/www/html/poweradmin/index.php on line 36
Help me please)

**Comment by edmondas** [comment]
@exebits are you sure that you're using the latest code, because based on the error message script fails on 36 line, but this is not possible - it's empty (check master):
https://github.com/poweradmin/poweradmin/blob/master/index.php#L36
