### ISSUE TITLE
Doesn't work with sqlite

### ISSUE THREAD

**Issue by screamingwalls** [poweradmin/poweradmin#364]
Ran the install successfully with sqllite backend, but after removing the install directory and trying to log in I get:

Error: No database file has been set in config.inc.php.

The config.inc.php that I copy/pasted from install was:
<?php
$db_host = '';
$db_name = '/opt/pdns/db/powerdns.sqlite3';
$db_user = '';
$db_pass = '';
$db_type = 'sqlite';

$session_key = 'fn(XwlWLC*4vT%rCXooyjfSPwV#m%j06rNqYFb(D2A@1ja';

$iface_lang = 'en_EN';

$dns_hostmaster = '';
$dns_ns1 = '';
$dns_ns2 = '';

**Comment by edmondas** [comment]
@screamingwalls are you sure that db_file variable is set in  configuration file?

**Comment by edmondas** [comment]
There isn't much documentation on how to use SQLite with Poweradmin. Additionally, the installer contained a small bug.

To begin, you need to create a SQLite database file containing the PowerDNS schema. You can use this script (or do similar steps): https://github.com/poweradmin/poweradmin-scripts/blob/master/create_sqlite_db.sh

Afterwards, run the installer and select SQLite as the database type, and then provide (the full path to the database file).
![image](https://user-images.githubusercontent.com/9033112/148675947-368f6919-590b-4fbe-bae5-d2dadcdfaefe.png)

Afterwards, copy generated configuration to inc.config.php.
![image](https://user-images.githubusercontent.com/9033112/148675965-92b17f96-d5dd-4107-ab67-b98f1564849e.png)
