### ISSUE TITLE
Error: You have invalid characters in your hostname (w/ PHP7.3 + PCRE2 / FreeBSD)

### ISSUE THREAD

**Issue by bengrimm528** [poweradmin/poweradmin#365]
Switching from PHP 7.2 to PHP 7.3 (which suddenly pulls in PCRE2) results in being unable to update or create records in any zones on PowerDNS using the PowerAdmin GUI. 

Errors (no php.ini loaded to get details):

Warning: preg_match(): Compilation failed: invalid range in character class at offset 8 in /usr/local/www/poweradmin-master/inc/dns.inc.php on line 347
Error: You have invalid characters in your hostname.
Error: Zone has not been updated successfully.

Switching back to PHP 7.2 (which removes the PCRE2 package pulled in by PHP 7.3) immediately solves the problem. Under any circumstance, the CLI tool (pdnsutil) has no problems modifying or creating records, so it's purely a GUI issue.

Environment in fail mode:
-----------------------------
FreeBSD 12, 32-bit
PowerDNS (powerdns-4.1.10) w/ poweradmin v2.1.8
PHP 7.3 (php73-7.3.6, mod_php73-7.3.6)
PCRE (pcre-8.43_1 and pcre2-10.32_1, pulled in by PHP 7.3)

Environment in success mode:
----------------------------------
FreeBSD 12, 32-bit
PowerDNS (powerdns-4.1.10) w/ poweradmin v2.1.8
PHP 7.2 (php72-7.2.19, mod_php72-7.2.19)
PCRE (pcre-8.43_1 only)

**Comment by bengrimm528** [comment]
I should add: PCRE2 has a toggle between LIBEDIT and READLINE support; neither one solves the issue.

**Comment by j4Hu** [comment]
https://github.com/poweradmin/poweradmin/pull/360
