### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kvanleeuwen** [poweradmin/poweradmin#366]
Hello,

I have installed powerdns (and mcrypt). When I try to add a domain (as master zone), called test.com, I get this error: You have invalid characters in your hostname. Error test.com Invalid hostname. Strange?

Does anyone have a clue?

Regards,
Kevin

**Comment by j4Hu** [comment]
https://github.com/poweradmin/poweradmin/pull/360

**Comment by kvanleeuwen** [comment]
Thanks! It works. But the same error occurs when you try to edit/modify an e-mail address (user account settings). Is here a solution for available?

**Comment by edmondas** [comment]
The master branch contains a fix for this problem.
