### ISSUE TITLE
DNSSEC errors?

### ISSUE THREAD

**Issue by kvanleeuwen** [poweradmin/poweradmin#367]
Hello,

When I try to add a master zone or try to delete a master zone, I get this erorr: Error: Failed to rectify zone. I've tried to fix this with https://github.com/poweradmin/poweradmin/issues/282 

Any clue?

**Comment by kvanleeuwen** [comment]
I still get Error: Failed to rectify zone; how do I fix this?

**Comment by asert** [comment]
I think you use PowerDNS 4.
Change file config.inc.php (or config-me.inc.php) like this:
//$pdnssec_command = '/usr/bin/pdnssec';
$pdnssec_command = '/usr/bin/pdnsutil';

You can read about it at https://github.com/poweradmin/poweradmin/issues/282

**Comment by edmondas** [comment]
Duplicate to #282
