### ISSUE TITLE
DNS error?

### ISSUE THREAD

**Issue by kvanleeuwen** [poweradmin/poweradmin#368]
Hello,

After one hour the powerdns crashes:
Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail

Backend reported condition which prevented lookup (GSQLBackend lookup query: Could not execute mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: Lost connection to MySQL server during query) sending out servfail

Does anyone have a clue?

Regards,
Kevin

**Comment by edmondas** [comment]
I'm not sure if this is related to Poweradmin, so closing the issue. Please reopen if you have more information and it's not a configuration problem.
