### ISSUE TITLE
PowerAdmin doesn't show the DNSKey

### ISSUE THREAD

**Issue by ServerionNL** [poweradmin/poweradmin#371]
Hi,

We have running poweradmin for many years and we enable DNSSEC but on the button 'Show DS and DNSKEY' we only see the DS Records and not the DNSKEY records?

The setting in config is good:
$pdnssec_command='/usr/bin/pdnsutil';

When I run it in ssh, I get the DNSKEY and DS Records so that works.

It just doesn't show in the poweradmin webinterface. Anyone else this problem?

Desmond

**Comment by edmondas** [comment]
With PowerDNS 4.x.x, some changes were introduced that were not supported by older versions or Poweradmin. With 2.1.9, these changes should work.
