### ISSUE TITLE
Error: You have invalid characters in your hostname.

### ISSUE THREAD

**Issue by renarios** [poweradmin/poweradmin#372]
Hi,

I just installed poweradmin on Centos 7 with Apache 2.4, but every record I want to add I get the error 

> Error: You have invalid characters in your hostname.

How can I fix this?

**Comment by shaundma** [comment]
What does php -v give ?

**Comment by renarios** [comment]
php -v gives PHP 7.3.12 (cli) (built: Nov 19 2019 10:24:51) ( NTS ).

**Comment by renarios** [comment]
Should PHP 7.4 be the solution?

**Comment by shaundma** [comment]
I'm using php7.1 and I believe php7.2 will also work, but php7.3 and above may give these kinds of problems. So my advise try php7.2 and if it doesnt fix the issue try php7.1

**Comment by edmondas** [comment]
Can you check your Apache error logs and paste here those lines, that would help to understand what kind of issues you have.

**Comment by renarios** [comment]
There are no errors in the error_log.
If I try to add a zone, the access_log says:`xxx.xxx.xxx.xxx  - - [05/Dec/2019:10:40:13 +0100] "POST /poweradmin/add_zone_master.php HTTP/1.1" 200 1065`

In the "Add master zone" screen, the following error occurs:
```
Error: You have invalid characters in your hostname.
Error: domain.local failed - Invalid hostname.
```

**Comment by edmondas** [comment]
Could you try to set `$dns_strict_tld_check = false;` in your configuration file and check then if you still have such problems.

**Comment by renarios** [comment]
That's not the solution. Still the same problem.
It happens with any record I'd like to add or change, also with users.

**Comment by j4Hu** [comment]
pls always check older issues
https://github.com/j4Hu/poweradmin/commit/df7ec01d41ca2dfa74a9a22fa7398d2f1a2dec70

**Comment by renarios** [comment]
Thanks J4Hu, that seems the solution. 
I searched for answers, but didn't find yours.
