### ISSUE TITLE
( ! ) Deprecated: Function mcrypt_decrypt() is deprecated

### ISSUE THREAD

**Issue by istiyakaminsanto** [poweradmin/poweradmin#373]
I'm trying to install Poweradmin also ensure you that i'm able to successfully install php-mcrypt module but when i'm trying to login always facing an error

**( ! ) Deprecated: Function mcrypt_decrypt() is deprecated in /var/www/html/poweradmin/inc/auth.inc.php on line 180**

**Comment by edmondas** [comment]
Fixed with PR #337

**Comment by istiyakaminsanto** [comment]
Thank you
