### ISSUE TITLE
php 7.3 add zone give this error :  PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 4 in /var/www/html/inc/dns.inc.php on line 321,

### ISSUE THREAD

**Issue by geonetsoft** [poweradmin/poweradmin#375]
the bug is solved because in 7.3 hyphen need to be escaped 

https://stackoverflow.com/questions/24764212/preg-match-compilation-failed-invalid-range-in-character-class-at-offset

so at line 315 and  321 in /inc/dns.inc.php you need to escape with \     the hyphen after w

preg_match('/[\w-\/...     will be preg_match('/[\w\-\/...

**Comment by nodenineinc** [comment]
I believe you meant to type:

OLD:
preg_match('/[\w-/

NEW:
preg_match('/[\w\-/

Correct?

The two strings you list as examples are identical.

**Comment by nodenineinc** [comment]
Also, thank you for the tip for resolution on this.  Having just modified several 2.1.8 installations and tested, this does appear to be the simple resolve to this issue.


`# diff dns.inc.php dns.inc.php-ORIG
347c347
<             if (!preg_match('/^(\*|[\w\-\/]+)$/', $hostname_label)) {
---
>             if (!preg_match('/^(\*|[\w-\/]+)$/', $hostname_label)) {
353c353
<             if (!preg_match('/^[\w\-\/]+$/', $hostname_label)) {
---
>             if (!preg_match('/^[\w-\/]+$/', $hostname_label)) {
744c744
<     if (!preg_match('/^_[\w\-]+$/i', $fields[0])) {
---
>     if (!preg_match('/^_[\w-]+$/i', $fields[0])) {
`

**Comment by edmondas** [comment]
The fixes have already been applied to the master branch.
