### ISSUE TITLE
Does not work with PHP 7.3

### ISSUE THREAD

**Issue by hostingnuggets** [poweradmin/poweradmin#376]
PowerAdmin does not seem to work with PHP 7.3 because the mcrypt PHP module does not exist anymore. I get the following error:

```
Error: You have to install PHP mcrypt extension!
```

Any workarounds or solutions?

**Comment by mislav-eu** [comment]
It works, I've installed it under debian 10 few days ago.

Simply compile from source mcrypt
https://stackoverflow.com/questions/55678023/how-to-install-mcrypt-on-php-7-3-3-ubuntu

add extension to php.ini, install php7.3-mysql package and it will work!

**Comment by hostingnuggets** [comment]
I see, thanks for the workaround!

**Comment by nodenineinc** [comment]
Hello.  I actually have a PHP 7.3 issue, but it is not related to the mcrypt module.  I was able to get that portion working following recently upgrading the node that poweradmin is running on.

My trouble appears to be related to internal changes between PHP 7.3 and lower versions and possibly how poweradmin is leveraging certain var types.

Whenever I try to enter in a new hostname or zone name, I now receive the following error from poweradmin:
=====[ In the web-UI 
Error: You have invalid characters in your hostname.

=====[ Apache2 error_log 
[Wed Jun 03 15:40:48.681113 2020] [php7:warn] [pid 31790] [client xxxx] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/poweradmin/inc/record.inc.php on line 1504
[Wed Jun 03 15:40:48.726944 2020] [php7:notice] [pid 31790] [client xxxx] PHP Notice:  Undefined index: userlogin in /var/www/html/poweradmin/inc/plugins/auth_local/auth_local.plugin.php on line 76
[Wed Jun 03 15:41:46.025016 2020] [php7:warn] [pid 31796] [client xxxx] PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 4 in /var/www/html/poweradmin/inc/dns.inc.php on line 353, referer: https://xxxx.com/add_zone_master.php


Looking at line 353 in the mentioned file, is the following stanza:

```
            if (!preg_match('/^[\w-\/]+$/', $hostname_label)) {
                error(ERR_DNS_HN_INV_CHARS);
                return false;
            }
```


Perhaps related to this PHP bug?  [https://bugs.php.net/bug.php?id=76975](https://bugs.php.net/bug.php?id=76975)

**Comment by nodenineinc** [comment]
Hello - just checking in to see if this should move to a new bug report, or if this has been examined yet?  I'm happy to create a new case, but thought it perhaps appropriate to retain since the topic is the same cause.  PHP 7.3 and poweradmin are no workie.

**Comment by edmondas** [comment]
Master branch should contain a fix for this. Please retest.
