### ISSUE TITLE
Column not found: 1054 Unknown column 'change_date' in 'field list' on powerdns 4.2.1

### ISSUE THREAD

**Issue by custom82** [poweradmin/poweradmin#379]
The following query generated an error:

SELECT id,
 domain_id,
 name,
 type,
 content,
 ttl,
 prio,
 change_date
                                    
FROM records 
                                    
WHERE domain_id='290' 
AND type IS NOT NULL
                                    
ORDER BY type = 'SOA' DESC,
 type = 'NS' DESC,
records.name+0<>0 DESC,
 records.name+0,
 records.name 
LIMIT 50

**Comment by geek4unix** [comment]
This seems to happen to me using master and pdns-4.4 versions, I managed to get it working with the following sql statement ( using SQLITE ) : 

`ALTER TABLE records ADD COLUMN change_data timestamp DEFAULT NULL;`

**Comment by edmondas** [comment]
PowerDNS 4.2.0 removes support for automatic serialization, and the code related to it is removed from the master branch.
https://doc.powerdns.com/authoritative/upgrading.html#x-to-4-2-0

**Comment by johnwc** [comment]
@edmondas so does that mean one of the devs need to remove `change_data` from the code everywhere it is referenced and push out updated release? We decided to turn the PDNS integration on, and we are getting this same error as well.

**Comment by edmondas** [comment]
@johnwc In release 2.1.9, all references to the `change_data` field were removed. Please back up your files and database and switch to the newest version.
