### ISSUE TITLE
Cannot create new user in 2.1.7 and 2.1.8 release 

### ISSUE THREAD

**Issue by ognjen011** [poweradmin/poweradmin#380]
I cannot add a new user there is an error about the missing use_ldap setting which is not in the gui. 

INSERT INTO users (username,
 password,
 fullname,
 email,
 description,
 perm_templ,
 active) VALUES ('ddd',
 '11ddbaf3386aea1f2974eee984542152',
 'dddd',
 'dddl@ddd.com',
 '',
 '1',
 '1')

SQLSTATE[HY000]: General error: 1364 Field 'use_ldap' doesn't have a default value

If i manually add use_ldap  into a sql statement i can create a user but then that user is not shown in the gui.  Also if i add a default value to use_ldap as 0 or 1 i can manually create a user as in above but the gui still fails to display the new user

**Comment by zod076** [comment]
I just installed using the master.zip and I'm having the same problem too.

**Comment by edmondas** [comment]
duplicate to #289
