### ISSUE TITLE
Bug with PHP 7.3

### ISSUE THREAD

**Issue by nodenineinc** [poweradmin/poweradmin#381]
Starting a new bug report since replying to https://github.com/poweradmin/poweradmin/issues/376 seems stalled with no responses.

I actually have a PHP 7.3 issue, but it is not related to the mcrypt module. I was able to get that portion working following recently upgrading the node that poweradmin is running on.

My trouble appears to be related to internal changes between PHP 7.3 and lower versions and possibly how poweradmin is leveraging certain var types.

Whenever I try to enter in a new hostname or zone name, I now receive the following error from poweradmin:
=====[ In the web-UI
Error: You have invalid characters in your hostname.

=====[ Apache2 error_log
[Wed Jun 03 15:40:48.681113 2020] [php7:warn] [pid 31790] [client xxxx] PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/poweradmin/inc/record.inc.php on line 1504
[Wed Jun 03 15:40:48.726944 2020] [php7:notice] [pid 31790] [client xxxx] PHP Notice: Undefined index: userlogin in /var/www/html/poweradmin/inc/plugins/auth_local/auth_local.plugin.php on line 76
[Wed Jun 03 15:41:46.025016 2020] [php7:warn] [pid 31796] [client xxxx] PHP Warning: preg_match(): Compilation failed: invalid range in character class at offset 4 in /var/www/html/poweradmin/inc/dns.inc.php on line 353, referer: https://xxxx.com/add_zone_master.php

Looking at line 353 in the mentioned file, is the following stanza:

            if (!preg_match('/^[\w-\/]+$/', $hostname_label)) {
                error(ERR_DNS_HN_INV_CHARS);
                return false;
            }

Perhaps related to this PHP bug? https://bugs.php.net/bug.php?id=76975

**Comment by nodenineinc** [comment]
Based off a suggested code edit mentioned in https://github.com/poweradmin/poweradmin/issues/375

The thus-far-functioning fix looks like this on a 2.1.8 install:

    # diff dns.inc.php dns.inc.php-ORIG

    347c347
    <             if (!preg_match('/^(\*|[\w\-\/]+)$/', $hostname_label)) {
    ---
    >             if (!preg_match('/^(\*|[\w-\/]+)$/', $hostname_label)) {
    353c353
    <             if (!preg_match('/^[\w\-\/]+$/', $hostname_label)) {
    ---
    >             if (!preg_match('/^[\w-\/]+$/', $hostname_label)) {
    744c744
    <     if (!preg_match('/^_[\w\-]+$/i', $fields[0])) {
    ---
    >     if (!preg_match('/^_[\w-]+$/i', $fields[0])) {

**Comment by edmondas** [comment]
The fixes have already been applied to the master branch.
