### ISSUE TITLE
Warning: php7.4 "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by BaseMax** [poweradmin/poweradmin#382]
Hi,

I face to a warning in **PowerAdmin**.

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/www/nginx-dist/pdns/inc/record.inc.php on line 1504
```

![demo](https://user-images.githubusercontent.com/2658040/90630711-c9cd2e80-e236-11ea-9f1f-ce6dde34a752.jpg)

Bug:
https://github.com/poweradmin/poweradmin/blob/master/inc/record.inc.php#L1504

Regards,
Max

**Comment by edmondas** [comment]
Thanks, this was merged to the master.
