### ISSUE TITLE
 2.1.7 to  2.1.8 upgrade path

### ISSUE THREAD

**Issue by sirati** [poweradmin/poweradmin#387]
Hello,
i am looking to set CAA records for my domains. This was addressed by #302 #291, but there does not seem like 2.1.8 has been released yet

Could there please be documentation akin to 2.1.6 to 2.1.7. I would like avoiding accadentally breaking by nameserver

**Comment by edmondas** [comment]
You can read more about the migration from 2.1.6 to 2.1.7 here https://github.com/poweradmin/poweradmin/wiki/v2.1.7#upgrading

As soon as possible, I will try to prepare migration notes for 2.1.8.
