### ISSUE TITLE
Issues with adding 2048 DKIM key

### ISSUE THREAD

**Issue by nvmng** [poweradmin/poweradmin#396]
I am trying a 2048 DKIM key from one of my providers to a zone template. Each time I try this, it throws up the error

INSERT INTO zone_templ_records (zone_templ_id,
 name,
 type,
 content,
 ttl,
 prio) VALUES ('4',
'mail._domainkey.[ZONE]',
'TXT',
'v=DKIM1; h=sha256; k=rsa; s=email; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0hYhzYx/JUVvauLAtX2Qtot2PGZgcz6UotCqjB8Ss57U1UEnTPP8nl8uaLziI3iwnKGqIg/lGAPZxKXNXa8JaVUBVYgkhYFJMVEH6xSbko6yGY+RCah8KwnRueJt/p+a823GNqoOV0O1ISIrsnN9cA6W8PVnfd5p+DZoUNlVHsbu75QKBeroEIUEmgP/RPe1s3s66TF/d37qqx5/uIEm5WuT2IkAOlvvkjVGuyvuy9Hl86rl0xayKYueGPyJphmoP0aa27F/u4fUzP0SV/xpe5iD8+B8bDubWKj8H7uQnsjvrt5KSAydkJA28lQTZMfkQdAjzM7yyxlH7OQxtPwAkQIDAQAB',
'86400',
'8')

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1

However it works when I try with a 1024 DKIM Key, but shows the error above when I try creating it with the 2048 key.

I have changed the content column in Mysql to Text, LongText and the error still persists. It is currently set to VARCHAR(64000)

I would appreciate any solving this problem.

Thanks

**Comment by nvmng** [comment]
Incase anyone experience this problem, I fixed mine by logging to mysql and accessing the database using the command "use databasename; and run the command below.

**Comment by rroethof** [comment]
run the command below.: what command ? :)

**Comment by edmondas** [comment]
@rroethof I think something like this (MySQL)
```
ALTER TABLE zone_templ_records
MODIFY COLUMN content varchar(2048);
```

**Comment by edmondas** [comment]
For PostgreSQL

```
ALTER TABLE zone_templ_records
    ALTER COLUMN content TYPE varchar(2048),
    ALTER COLUMN content SET NOT NULL;
```

Unfortunately, there is no direct way to rename columns in SQLite. I need some time to think about and test this solution.

**Comment by edmondas** [comment]
Here are instructions for SQLite:

```
BEGIN;
CREATE TABLE zone_templ_records_new (
    "id"            integer NULL PRIMARY KEY AUTOINCREMENT,
    "zone_templ_id" integer NOT NULL,
    "name"          text    NOT NULL,
    "type"          text    NOT NULL,
    "content"       text(2048) NOT NULL,
    "ttl"           integer NOT NULL,
    "prio"          integer NOT NULL
);

INSERT INTO zone_templ_records_new SELECT * FROM zone_templ_records;
DROP TABLE zone_templ_records;
ALTER TABLE zone_templ_records_new RENAME TO zone_templ_records;
COMMIT;
```
