### ISSUE TITLE
Pull merg #395 breaks adding new zones

### ISSUE THREAD

**Issue by Niwreg** [poweradmin/poweradmin#397]
Hi,

I ran into an issue with the latest version while adding a new zone

```
INSERT INTO records (domain_id,
 name,
 content,
 type,
 ttl,
 prio) VALUES ('115',
'example.net',
'ns1.example.net',
'NS',
'7200',
'0',
'1613329093')

SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1
```

the Changedate may be removed, but it is still in the SQL itself. I'll not that good with GitHub so i'll try to fix it and do a merge request but like i said i'm not that good with the whole github concept

**Comment by Niwreg** [comment]
that was easier than expected, i did a pull request: #398

**Comment by edmondas** [comment]
Thank you for contribution @Niwreg
