### ISSUE TITLE
upgrade questions

### ISSUE THREAD

**Issue by clusterx** [poweradmin/poweradmin#400]
Debian9
php7.1-fpm
mariadb 7.1
poweradmin v2.1.8
PDNS 4.2.3

yesterday I upgraded PDNS from 4.1.14 to 4.2.3 now I have some questions about preparations for further upgrade to debian 10
I guess I have to run this first for PDNS 4.2.3, is that correct?
ALTER TABLE records ADD COLUMN change_date INT DEFAULT NULL;

I will then replace all changed files with the new one from poweradmin master ... can I change the PHP version afterwards (7.1 to 7.3) before I upgrade to buster?

Which PDNS version is recommend (supported) by the current poweradmin master?

**Comment by Bungalow74** [comment]
Am currently with

AlmaLinux 8.4
PHP 7.3.29
Apache 2.4.37
MariaDB 10.3.28
PowerAdmin v2.1.8
PDNS-4.5.1

**Comment by edmondas** [comment]
My recent testing was done with PowerDNS 4.5.2 on CentOS 8.5 and the latest code from the master branch should work. Check the PowerDNS changelog as well https://doc.powerdns.com/authoritative/changelog/
