### ISSUE TITLE
TXT record content taking only 265 characters string

### ISSUE THREAD

**Issue by coper1973** [poweradmin/poweradmin#406]
We are trying to add a very long Content string DKIM in the TXT record and is taking only 265 characters.  
We are using  poweradmin v 2.1.6 

Thanks in advance for your help.

**Comment by mzch** [comment]
You should modify `content` column using `ALTER TABLE records MODIFY content VARCHAR(64000)`.

**Comment by edmondas** [comment]
This is related to #192

**Comment by edmondas** [comment]
The tables should also be in latin1 encoding if you get an error that the length column field is too large.

Please check database schema of PowerDNS 4.5.x for MySQL https://raw.githubusercontent.com/PowerDNS/pdns/rel/auth-4.5.x/modules/gmysqlbackend/schema.mysql.sql
