### ISSUE TITLE
Regression v2.1.9 - search now uses invalid SQL

### ISSUE THREAD

**Issue by ktims** [poweradmin/poweradmin#411]
Introduced by #307 , the search query now adds `GROUP BY records.id`, which is trying to GROUP BY only one of the requested columns, which is nonsense and not valid SQL, and therefore fails on PostgreSQL (and likely anything other than MySQL, though I am not sure about SQLite).

I see a couple ways to fix this:

* List all the desired return fields as part of the group by
* Use a subselect and select only `records.id` in the subquery, using either group by or select distinct

I'm not sure which works / would be more optimal on MySQL.

For my installation I have just removed the GROUP BY clause entirely for now.

If development is restarting, I'd appreciate patches being tested on Postgres.

**Comment by edmondas** [comment]
This grouping by records.id makes no sense to me either. Therefore, I am not sure if it is necessary to list the fields that are part of grouping or if it is necessary to make other changes. The simplest could be to remove this grouping statement, which you have already done.
