### ISSUE TITLE
[Blocker] Call to undefined function idn_to_utf8()

### ISSUE THREAD

**Issue by itys** [poweradmin/poweradmin#412]
Hello,
I'm running into the below error when trying to do anything with zones, specifically list them. As you can see: 
php7.4-fpm  w/ FastCGI

Based on some searching, I checked php.ini and enabled pgsql and intl but the issue persists. I'll continue troubleshooting but if there is a quick fix please let me know. 

Cheers.

==> error.log <==
2022/02/23 10:35:24 [error] 349830#349830: *116 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function idn_to_utf8() in /var/www/html/pdns/list_zones.php:175
Stack trace:
#0 {main}
  thrown in /var/www/html/pdns/list_zones.php on line 175" while reading response header from upstream, client: ::1, server: localhost, request: "GET /list_zones.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "localhost", referrer: "http://localhost/index.php"

**Comment by itys** [comment]
Related: Oddly, if I do a Search Zones my zones are listed and appear editable. I will continue troubleshooting. Thanks for the gift of PowerAdmin.

**Comment by edmondas** [comment]
@itys Have you restarted the php-fpm service? Also, check that you have enabled the intl extension in your php.ini file.
