### ISSUE TITLE
Poweradmin 2.2.1 / PowerDNS 4.6 not showing some dialogs (list zone, add zone, etc)

### ISSUE THREAD

**Issue by irishman59** [poweradmin/poweradmin#414]
Hello.

I've got a problem -- fresh installation of Poweradmin 2.2.1 / PowerDNS 4.6 not showing some dialogs (list zone, add zone)

List zones - empty
![image](https://user-images.githubusercontent.com/92012812/157610908-ed700fa5-d42f-4c02-80ec-921691e1eb94.png)

Add master zone - first step looks ok, but after pressing 'add zone' - empty screen with nothing to do
![image](https://user-images.githubusercontent.com/92012812/157611053-b86130a8-1441-4eb7-9353-59d8adcb1ced.png)
![image](https://user-images.githubusercontent.com/92012812/157611076-c6ac8188-015e-4e45-a673-24da0cc847a7.png)

Search zones and records working fine
![image](https://user-images.githubusercontent.com/92012812/157610854-19dd8119-3e09-4ca9-81a6-d079f155bc42.png)

PowerDNS database is working fine too
![image](https://user-images.githubusercontent.com/92012812/157611200-6769092b-15ff-44f1-a4be-3ae6a466eea3.png)

NB: tested in different browsers (Chrome/Egde/Firefox) + used incognito mode = same problem everywhere

**Comment by edmondas** [comment]
Make sure that the `php-intl` extension is installed

**Comment by irishman59** [comment]
Yeah, thanks, I'm pretty sure it's duplicate of this closed bug https://github.com/poweradmin/poweradmin/issues/412

Enabled displayerrors in php.ini and now it's showing:

`Fatal error: Uncaught Error: Call to undefined function idn_to_utf8() in /var/www/html/poweradmin/list_zones.php:143 Stack trace: #0 {main} thrown in /var/www/html/poweradmin/list_zones.php on line 143`

Install php-intl and now it`s working 

![image](https://user-images.githubusercontent.com/92012812/157614032-ed19e89f-3613-42c9-bb8f-5414056dd839.png)

Thanks for great product and great support!

P.S. But it's very bad, that you have no complete documentation for installation :(

**Comment by edmondas** [comment]
Thank you for your feedback. I have added a check for PHP extensions.
Later I will add minimal installation instructions to the readme.

**Comment by edmondas** [comment]
@irishman59 The readme file now contains a brief description of the steps required during installation. Check if it's okay.

**Comment by irishman59** [comment]
Thanks, it's fine now!
