### ISSUE TITLE
Request: select and delete  multiple records  at once (Search and zone view)

### ISSUE THREAD

**Issue by hvisage** [poweradmin/poweradmin#423]
Have cases of multiple entries to delete, especially after searching for them, and this option would make it easier.

**Comment by logger55** [comment]
![2022-03-26 14 53 21](https://user-images.githubusercontent.com/1895214/160238183-bdd6154c-cec8-4454-a203-f0474ce5a066.png)
please  add checkbox  to select all zones of one button in List zones

to remove a thousand zones, I have to select each zone a thousand times

**Comment by logger55** [comment]
hello! 
and please add  in List zones total number of domains - for example 123 domains fild somewhere above

**Comment by edmondas** [comment]
@hvisage @logger55 I think it should be fine.
Do not want to spend too much time before modern UI components will be used.

![image](https://user-images.githubusercontent.com/9033112/161807603-016982b1-1812-4156-ba48-ce92bc70ddc7.png)
