### ISSUE TITLE
Zones Loaded into pdns via alternate methods like pdns_util load-zone are semi-hidden

### ISSUE THREAD

**Issue by networkjackbb** [poweradmin/poweradmin#427]
I am converting from BIND to PDNS and as such I am loading almost 100% of my zones via pdns_util load-zone

This is a change that is most evident in the List Zones UI where the show_letters function is being called to produce the letter discriminator links.

In between 2.2.2 and 2.2.3 the SQL query was altered in such a way that only domains that have an attached zones record are found and then a letter is generated for the list html that is generated in list_zones.php

Almost none of my "domains" records have an attached "zones" record to join against.

The query is semi-broken anyway as it will only produce letter links for zone owners. It needs to ALSO end up producing links if I'm the superuser, not just the zone owner.

So this is a query bug and also a architectural bug in that that are multiple ways that PDNS is built so that domains can get entered into the system without PowerAdmin's knowledge. PowerAdmin needs to work around that inevitability.

**Comment by edmondas** [comment]
@networkjackbb check out the latest 3.0.0 release. This version contains a fix.
