### ISSUE TITLE
Add support for CERT records (and all currently supported record types)

### ISSUE THREAD

**Issue by wlovins** [poweradmin/poweradmin#44]
The CERT record type is something we need to be able to create records for and it is not currently available from the list of record types.

The trac ticketing instance had a similar ticket from a few years ago ( https://www.poweradmin.org/trac/ticket/89 ).

**Comment by SebTM** [comment]
What is needed to get CERT-Records working?

**Comment by edmondas** [comment]
A CERT record type is already supported.
