### ISSUE TITLE
DS record type should strip comments from content field on input/update operations

### ISSUE THREAD

**Issue by netravnen** [poweradmin/poweradmin#445]
https://github.com/poweradmin/poweradmin/blob/7322593016a551cae35540c595138dbe8e21a819/lib/Dns.php#L158-L160

**ISSUE**

Editing a zone with comments contained in the DS records results in an error when trying to edit it via the `pdnsutil` tool. Removing the comments field the DS record contents resolves the issue.

**SUMMARY**

DS records should validate on input and/or update operatios, that the field does **not** contain a comments after the DS record field (e.g. strip comments after end of valid record: `sed -E -e 's/^([0-9]+) ([0-9]+) ([0-9]+) ([a-f0-9]+) .*/\1 \2 \3 \4/'`).

**COMMAND**

```
dns-a ~ % sudo pdnsutil edit-zone X.X.X.X.Y.Y.Y.Y.ip6.arpa                                         
Aug 18 08:45:13 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Error: Parsing record content (try 'pdnsutil check-zone'): Unknown hexadecimal character '83'
```

**VERSION**

```
dns-a ~ % sudo pdnsutil --version
pdnsutil 4.6.3
```

**INVALID**

```
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 1 3ed47c388821zzzzzzzzfd1397c3zzzzzz26768 ; ( SHA1 digest )
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 2 d5fa3238635fzzzzzzb72bdf4f9162bf8431zzzzzzz7fa163264af5245b223a ; ( SHA256 digest ) 
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 4 2ac95d65cfdcbd3zzzzzzz67825529b8dd81686099aa4f0azzzzzzzzzzzzza465fd1730bd34554442c8248e264ba ; ( SHA-384 digest )
```

**VALID**

```
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 1 3ed47c388821zzzzzzzzfd1397c3zzzzzz26768
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 2 d5fa3238635fzzzzzzb72bdf4f9162bf8431zzzzzzz7fa163264af5245b223a
3.2.0.a.X.X.X.X.Y.Y.Y.Y.ip6.arpa	86400	IN	DS	30612 13 4 2ac95d65cfdcbd3zzzzzzz67825529b8dd81686099aa4f0azzzzzzzzzzzzza465fd1730bd34554442c8248e264ba
```

**Comment by edmondas** [comment]
Record validation has been added. There are many factors that can affect how content is stripped and whether it works properly.
