### ISSUE TITLE
New install: Cannot write to sqlite3 database

### ISSUE THREAD

**Issue by lifeboy** [poweradmin/poweradmin#449]
I am trying to install poweradmin on the same server as pdns, but the installation script doesn't proceed past installation step 4 "updating database".
I see in nginx error.log "General error: 8 attempt to write a readonly database in /var/lib/poweradmin/inc/PDOLayer.php:197"
I have /var/lib/poweradmin owned by www-data, but /var/log/powerdns owned by pdns

Should I run nginx as pdns user then as well or is there a config file in which I can give poweradmin rights to read/write the sqlite db?

**Comment by edmondas** [comment]
> Should I run nginx as pdns user then as well or is there a config file in which I can give poweradmin rights to read/write the sqlite db?

This can't be done through a config file. It might not be a good idea to run nginx as a pdns user. It's more related to the user groups and access rights. One option is to make database world writable, which doesn't sound perfect solution. Alternately, you can add nginx to the pdns group and allow group members to write to a sqlite database.

**Comment by lifeboy** [comment]
I have added www-data (which is the nginx user) to the group pdns and made the sqlite db group writable.

It now works.
