### ISSUE TITLE
Per-User Record-Rights as in PowerAdmin v1.0

### ISSUE THREAD

**Issue by Fusl** [poweradmin/poweradmin#45]
Hello,

it's a really big problem to us, because we are an isp in austria. So whats the problem? Our customers need to edit their subdomains and IPv4-PTR-Records without our help or anything else. In PowerAdmin v1.0 there was the opportunity to give a user only rights to some records in a zone. Why i cant do this in 2.1.6? Is there a workaround to do this as in the old version? Thank you very much and sorry for my bad english (austria, u knw?).

**Comment by SebTM** [comment]
Duplicate of #73
