### ISSUE TITLE
Deactivating and deleting a zone key don't work

### ISSUE THREAD

**Issue by kto2038** [poweradmin/poweradmin#463]
With poweradmin 3.1.0, when I tried to deactivate a zone key from "Edit zone key", the zone key wasn't deactivated.
"$pdnssec_debug = true;" says:

```
Command: /usr/bin/pdnsutil deactivate-zone-key 'example.net 6' 2>&1
Output: Syntax: pdnsutil deactivate-zone-key ZONE KEY-ID
```

"Delete zone key" doesn't work too, "$pdnssec_debug = true;" says:

```
Command: /usr/bin/pdnsutil remove-zone-key 'example.net 6' 2>&1
Output: Syntax: pdnsutil remove-zone-key ZONE KEY-ID
```

When I removed ``escapeshellarg(`` ``)`` from ``dnssec_call_pdnssec()`` in ``lib/Dnssec.php``, they worked.

**Comment by edmondas** [comment]
#461 should have resolved that.

**Comment by kto2038** [comment]
Thank you, it worked.
