### ISSUE TITLE
SOA Serial value is reset when Serial value is two (or more) days after today

### ISSUE THREAD

**Issue by kto2038** [poweradmin/poweradmin#472]
When SOA Serial value is two days (or more) after today (ex. today: 2022/10/21, Serial: 2022102300), Serial incrementation fails and Serial is reset to today's value (ex. 2022102100).

On my environment (Ubuntu 22.04, PHP 8.1.2), `strncmp("20221021", "20221023", 8);` returns -2, so it doesn't match this line.
 https://github.com/poweradmin/poweradmin/blob/5dd55b39c59f2dfc8fa3c36f6bc64dfc7976449c/lib/DnsRecord.php#L168

**Comment by edmondas** [comment]
@kto2038 What's your suggestion? Just increment the revision and use the same date from the future?
