### ISSUE TITLE
No zone edit with PHP 8.0/8.1

### ISSUE THREAD

**Issue by rkutschi** [poweradmin/poweradmin#474]
I tried poweradmin versions 2.2.2, 3.2.0, 3.3.0. If i want to edit a Zone, the page is only white/blank. Everythink works with PHP 7.2 and 7.3. Tried in different browsers, PHP error reporting and logs don´t give any error except:

FastCGI sent in stderr: "PHP message: PHP Warning:  Division by zero in .../poweradmin/inc/pagination.inc.php on line 38" while reading upstream, client: IP, server: SERVER, request: "GET /poweradmin/edit.php?name=DOMAIN.COM&id=2443 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "SERVER", referrer: "https://DOMAIN.COM/poweradmin/search.php

But this error occurs everytime i edit a zone, even with the older PHP versions where it works. Does poweradmin don´t support PHP8 ?

**Comment by edmondas** [comment]
@rkutschi Is it possible that $iface_rowamount is set to 0 in your config file?

**Comment by rkutschi** [comment]
Thats correct! $iface_rowamount was 0 in the config, i removed it and it´s working now. Thx for the good support.
