### ISSUE TITLE
Template: show link to go back to the zone template

### ISSUE THREAD

**Issue by bugoff** [poweradmin/poweradmin#478]
When you add or edit a record to a zone template, you're redirected to the same form to add a record, but there is no link to go back to the zone template.

Most of the times when you add or edit a record to a zone template, you want to go back to the template to refresh the zone, but there is no direct link to template.

Can we add a hyperlink to the "X-plose" part in the line where it says Edit record in zone template?

![Screenshot 2022-12-11 at 22 56 59](https://user-images.githubusercontent.com/1258672/206931229-ab3ed58c-3b02-4acc-b30a-f7016d5bb67f.png)

**Comment by edmondas** [comment]
@bugoff So maybe going back to the zone template with updated records would be better than using the same form again? I incorporated this behavior into other pages now.
