### ISSUE TITLE
Comment Info show on a Hover when i go over the Zone

### ISSUE THREAD

**Issue by tuvok81** [poweradmin/poweradmin#479]
Hello,
is this possible to show the entry on the Comment field on a hover when i go with the mouse over the Zone?
this was very nice

**Comment by edmondas** [comment]
@tuvok81 sorry it's difficult to understand where exactly you want to see comment. You mean in the zone list?

![image](https://user-images.githubusercontent.com/9033112/208568940-1f883f47-2591-467e-a632-0d40852614b8.png)

**Comment by tuvok81** [comment]
@edmondas correct ... when i write in the zone a comment .. than i will show the comment with a hover.. 
its very strong when i have many ipv6 zones.. to identify it :)
