### ISSUE TITLE
update a Zone gives some Errors

### ISSUE THREAD

**Issue by tuvok81** [poweradmin/poweradmin#484]
Hello, i have change on my comment Field a little bit Text and push the "change Button" than i get the errors on the screen

![grafik](https://user-images.githubusercontent.com/30367063/209830062-b222e4f5-ac2b-467e-9652-6d176037e28a.png)
![grafik](https://user-images.githubusercontent.com/30367063/209830159-9b7db260-258d-411c-b6a9-bcafe8b698e7.png)

i have move my old poweradmin folder to poweradmin-old and rename the new poweradmin-3.4.0 to poweradmin and remove the install folder and copy the config.inc.php from the inc folder to the new..

is that not correct?

**Comment by edmondas** [comment]
@tuvok81 Unfortunately, I am unable to reproduce this issue. My question is whether you logged out and logged back in after the update. Can you tell me if it's an administrator or a restricted user?

**Comment by tuvok81** [comment]
iam a administrator

**Comment by edmondas** [comment]
The problem was reproduced after adding more records. A quick fix will be provided as soon as possible.

**Comment by edmondas** [comment]
@tuvok81 Thank you for reporting the bug. A new version of the software is now available for download.
