### ISSUE TITLE
Permission error from edit.php in v3.4.2

### ISSUE THREAD

**Issue by Chiramium** [poweradmin/poweradmin#487]
Hello. 
I am a college student studying Computer Science, and now I'm using PowerAdmin during my internship. Thank you for keeping it developing!
Speaking of PowerAdmin, when I installed it v3.4.2 and added the master zone, I occurred a 500 error about denying access to "edit.php" in it.

<details><summary>The error in /var/log/php-fpm/www-error.log</summary>
[10-Jan-2023 00:18:06 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  

permission denied for table cryptokeys in /usr/share/nginx/html/lib/Dnssec.php:223
Stack trace:
<span>#</span>0 /usr/share/nginx/html/lib/Dnssec.php(223): PDOStatement->execute()
<span>#</span>1 /usr/share/nginx/html/edit.php(245): Poweradmin\Dnssec::dnssec_is_zone_secured()
<span>#</span>2 /usr/share/nginx/html/edit.php(272): EditController->run()
<span>#</span>3 {main}
  thrown in /usr/share/nginx/html/lib/Dnssec.php on line 223
</details>

Probably it's caused by permission to access tables and sequences without "cryptokeys", "domainmetadata", and both of its sequences. 
To add it, I think the file install/database-structure.inc.php could be like this:
[on line 560]
```diff_tables
- $grantTables = array('supermasters', 'domains', 'records');
+ $grantTables = array('supermasters', 'domains', 'domainmetadata', 'cryptokeys', 'records');
```
[on line 567]
```diff_sequences
- $grantSequences = array('domains_id_seq', 'records_id_seq');
+ $grantSequences = array('domains_id_seq', 'domainmetadata_id_seq', 'cryptokeys_id_seq', 'records_id_seq');
```

And in my env, it worked correctly.
<details><summary>My env</summary>
RockyLinux 9.1

[DBServer]
PowerAdmin v3.4.2
PHP 8.1.8
NGINX 1.20.1
PostgreSQL 13.7
[AuthServer]
PowerDNS 4.7.3
</details>

I apologize beforehand for the poor English because I am not a native speaker. 

Thank you for your consideration :).

**Comment by edmondas** [comment]
@Chiramium can you check if the latest code from the master branch has the same issue? There were a few changes regarding permission checks, so I am not sure if it was not already fixed. Thanks.

**Comment by edmondas** [comment]
I think I misread and misunderstood the problem itself (referring to my comment above). Your change may be correct, I need to check with a similar configuration later when I have a chance.

**Comment by Chiramium** [comment]
Thank you for replying!

I tried to validate on the master branch, but an error about I18nExtension made it impossible. If possible, I would like to check that error as well.

P.S. I would like to rework a Japanese translation of Poweradmin and will probably update a translation file soon.

**Comment by edmondas** [comment]
Thank you for your help, all issues have been resolved.
