### ISSUE TITLE
Postgresql install issues

### ISSUE THREAD

**Issue by parszab** [poweradmin/poweradmin#489]
Just installed Poweradmin 3.4.2 on Ubuntu 22.04 with pdns provided in the distro. I used the web installer and experienced the following issues:

1. The SQL command to create the user with `createuser` didn't prompt for permission confirmations, simply the name and password -- not sure why, but was fundamentally okay as the new user didn't have those wider privileges.

2. When trying to create the first zone I had issues with missing privileges, these also had to be run: 
```
GRANT SELECT, INSERT, DELETE, UPDATE ON cryptokeys TO poweradmin_limited;
GRANT SELECT, INSERT, DELETE, UPDATE ON domainmetadata TO poweradmin_limited;
GRANT USAGE, SELECT ON SEQUENCE cryptokeys_id_seq TO poweradmin_limited;
GRANT USAGE, SELECT ON SEQUENCE domainmetadata_id_seq TO poweradmin_limited;
```

**Comment by edmondas** [comment]
Thanks for the report, it has been fixed in master. In addition, it was similar to #487.

**Comment by edmondas** [comment]
> 1. The SQL command to create the user with `createuser` didn't prompt for permission confirmations, simply the name and password -- not sure why, but was fundamentally okay as the new user didn't have those wider privileges.

Maybe that's related to the changes to the tool itself. Previously it asked for additional privileges, but now you can pass those settings via the command line.
