### ISSUE TITLE
Unexpected behaviour with zone_meta_edit_own permission

### ISSUE THREAD

**Issue by rnilssen** [poweradmin/poweradmin#49]
Two unexpected behaviours here;
- User cannot change a native domain and set it up as a slave domain, perhaps this should be possible? If  I also add zone_slave_add, then the user can set a pre-existing domain as slave, but then the user also can create new slave zones, this is not desireable. I am trying to create a poweruser template that let users mostly freely edit their own zones, including changing it to slave from their own master server.
- In addition, users are allowed to add additional owners to their zone when meta_edit_own is set, this makes little sense to me unless user also has some privilege that lets them manipulate users. Reason beeing that user can add themselves or remove themselves from the zone metadata, but nothing much else. They are infact allowed to remove themselves and thus "orphaning" the zone.
- Further it seems that they can change the template of the zone, however as they are unable to create or maintain templates this ability also seems unreasonable without additional privileges.

Please consider changing the behaviour. Thanks,
Rune

**Comment by edmondas** [comment]
Despite the fact that this ticket is fairly old, I did attempt to change some behaviours.

- The user can now change the zone type without requiring additional permissions
- The zone can't be orphaned by the user, one owner is required
- As you pointed out, template management is incomplete without additional rights; therefore, this use case needs to be rethought. For example, a user may have some created templates and some global templates. Separate ticket created for that #477
