### ISSUE TITLE
The priority of DNS records can not be updated.

### ISSUE THREAD

**Issue by nazerise** [poweradmin/poweradmin#494]
The priority of DNS records can not be updated.
After changing prio to priority, the problem was solved.
vi lib/DnsRecord.php
line 357
if (Dns::validate_input($record['rid'], $record['zid'], $record['type'], $record['content'], $record['name'], $record['priority'], $record['ttl']))

**Comment by edmondas** [comment]
Thank you for reporting the bug. I made some modifications, as the field name was accurate. You just bypassed the validation of that field. The display of errors will be improved in the coming weeks.
