### ISSUE TITLE
Poweradmin Authentication failed!

### ISSUE THREAD

**Issue by AlexNikolovLON** [poweradmin/poweradmin#499]
Hi Guys,

I'm getting error  Authentication failed! after install

reinstall / same

cant see any error in log file that related to it

Install Poweradmin from github v3.4.2.tar.gz on 
CentOS8 4.18.0-448.el8.x86_
PHP 7.4.33-4.el8.remi 
10.11.2-MariaDB MariaDB Server
httpd.x86_64 2.4.37-54.module

HELP :)

**Comment by AlexNikolovLON** [comment]
No unfortunately , checked all dependencies all fine 

tried to use password without @ symbol but no

**Comment by AlexNikolovLON** [comment]
No unfortunately , checked all dependencies all fine 

tried to use password without @ symbol but no

**Comment by edmondas** [comment]
Poweradmin 3.5.0 (and master branch) supports only PHP 8.1 and higher, but older versions should work fine with PHP 7.4. The older PHP version is no longer supported by the PHP project and has reached end of life. Moreover, some external dependencies moved to 8.1+ requirement, making it difficult to keep support for multiple PHP versions.

It's still unclear what is causing the authentication issue. There was only one similar issue where the user did not have any permissions https://github.com/poweradmin/poweradmin/issues/273

**Comment by edmondas** [comment]
@AlexNikolovLON Maybe you can share the configuration file `inc/config.inc.php` with obfuscated values (passwords, credit card numbers, or other sensitive information).

**Comment by edmondas** [comment]
@AlexNikolovLON Would you be able to review a few items described in another similar issue in order to fix this one?
https://github.com/poweradmin/poweradmin/issues/507#issuecomment-1505692833

**Comment by edmondas** [comment]
I am closing this ticket and moving the discussion to #507.
