### ISSUE TITLE
Content fields corrupt with double quotes (")

### ISSUE THREAD

**Issue by dzs** [poweradmin/poweradmin#50]
TXT records don't seem to be edited or saved correctly with double-quotes ". This is a problem with SPF records imported as TXT from bind. A TXT field in the database with content like this:

"spf2.0/pra,mfrom +ip4:1.2.3.0/24 +ip4:4.5.6.0/24 ?all"

Will be displayed in PowerDNS "edit" with backslashes, although sometimes the ending double-quote will be missing.

\"spf2.0/pra,mfrom +ip4:1.2.3.0/24 +ip4:4.5.6.0/24 ?all\"

Saving this causes duplicate backslashes to appear the next time it's edited:

\\\"spf2.0/pra,mfrom +ip4:1.2.3.0/24 +ip4:4.5.6.0/24 ?all\\\"

And worse, a query to PowerDNS returns embedded \'s:

example.org. 3600  IN TXT "\"spf2.0/pra,mfrom +ip4:1.2.3.0/24 +ip4:4.5.6.0/24 ?all\""

Test environment: 
Safari 6.0.2 OSX 10.8.2
PowerDNS 3.1 mysql backend
PowerAdmin 2.1.6 
Php 5.3.20

**Comment by edmondas** [comment]
@dzs can you check if you still have this issue with latest code?
