### ISSUE TITLE
Search results are limited to 10 entries - missing "show more" or pagination of results

### ISSUE THREAD

**Issue by fuco809** [poweradmin/poweradmin#501]
how can other search results be shown, wenn more than 10 entries are found and i am not able to do a more restrictive search.

a load more results oder pagination of the search results would be nice.

**Comment by edmondas** [comment]
Adding `$iface_rowamount = 20;` to your config will increase the number of rows visible, but I agree that all those tables need pagination / entries per page.

**Comment by edmondas** [comment]
The next release will include pagination for search results:

![image](https://user-images.githubusercontent.com/9033112/232325718-3858dfc5-2a3f-4f26-8637-5b531b6ca274.png)
