### ISSUE TITLE
Error: Add quotes around TXT record content

### ISSUE THREAD

**Issue by clusterx** [poweradmin/poweradmin#510]
I'm trying a migration from PDNS 4.3.2 to another server, updated Poweradmin from 2.1.9 to 3.3.0 ... PDNS will be upgraded afterwards.
After importing the database, I can't change zones which contain TXT records or add new ones.

poweradmin panel shows:
Error: Add quotes around TXT record content.

Do I now have to change all my TXT records (there are about 1500 entries) or what can I do?
pdnsutil check does not show any problems with the existing TXT records without quotes ...

**Comment by clusterx** [comment]
hm, is there a query which can be used to update and fix all missing quotes in TXT records?

**Comment by edmondas** [comment]
RFC specifies that TXT and SPF records should be enclosed in quotes, but PowerDNS appears to understand content that is not enclosed in quotes. It's likely that this behavior was added in some version.

**Comment by edmondas** [comment]
Thank you for pointing out the bug and sorry for the delay in resolving it. A validation check for surrounding quotes has been removed, but a check for backslashing has been added. The following is based on the PowerDNS documentation: https://doc.powerdns.com/authoritative/appendices/types.html#txt

**Comment by edmondas** [comment]
I wanted to provide an update on the quoting functionality in DNS record management.

I found that removing quoting actually caused unexpected issues for some users. To address this, I've implemented an "autoquoting" flag that gives you control over this behavior.

You can read more details about this change in release notes: https://www.poweradmin.org/i/158689980/improved-dns-record-management

This should offer a good balance - maintaining compatibility for existing workflows while providing flexibility for those who need it. Let me know if you encounter any issues with this implementation!
