### ISSUE TITLE
How to make @ record of x.com support cname record?

### ISSUE THREAD

**Issue by wong** [poweradmin/poweradmin#511]
How to make @ record of x.com support cname record?

**Comment by edmondas** [comment]
@wong The @ record is the root record of a zone, and it must be an A or AAAA record. According Alternatively, you can use an ALIAS record. That allows you to point the root of your domain to another domain, and the DNS provider will resolve the target domain to its IP address(es) and return those IP addresses as A or AAAA records for the root of your domain.

**Comment by edmondas** [comment]
Closing as no response has been received. Please reopen if something has not been addressed.
