### ISSUE TITLE
installer and app ignore db_name in container (build by your Dockerfile)

### ISSUE THREAD

**Issue by lagunary** [poweradmin/poweradmin#512]
Hello,

I try to use your product, and I have issues with them.
This one is so annoying. The inc/config.inc.php file has this variable: $db_name but it will be never used again. The code is checking the powerdns db on the server. After I renamed my db to powerdns from pdns it is starting to work.

Please check it.
Thanks.
V

**Comment by edmondas** [comment]
SQLite, which is used in Dockerfile, does not have such a concept as a database name. The provided file is considered a database, and it consists of only PowerDNS and Poweradmin tables.
