### ISSUE TITLE
Unable to connect to postgresql

### ISSUE THREAD

**Issue by cadevra** [poweradmin/poweradmin#513]
Good day

I'm trying to install powerdns admin on centos 7 and experiencing issues with: 
 "Updating database... Unable to connect to the database server. SQLSTATE[08006] [7] could not connect to server: Permission denied Is the server running on host "10.XX.XX.121" and accepting TCP/IP connections on port 5432?"
the ip is private and remote to the powerdns-admin server. Except am able to remote login to the server when i use another server.

Please assist

**Comment by cadevra** [comment]
Okay found the issue: 
 PHP Parse error:  syntax error, unexpected identifier "XXXXXXXXXXX" in /var/www/html/poweradmin-3.5.1/inc/config.inc.php on line 21

**Comment by edmondas** [comment]
@cadevra Sorry, but it's hard to answer without knowing what's on line 21, maybe there's some syntax error, maybe you did some manual editing and forgot to make it a valid PHP file. As an alternative, we can have a remote debugging session to figure out what the problem is.

**Comment by edmondas** [comment]
Closing as no response has been received. Please reopen if something has not been addressed.
