### ISSUE TITLE
version not on the website for 3.5.1

### ISSUE THREAD

**Issue by tuvok81** [poweradmin/poweradmin#514]
Hi, i have update to the version 3.5.1 but i see on the login page 3.5.0 hm i have delete cache..
hm is this a issue on my site or on your?

ähm i see the Master will not transfer the comment field to the slave?

**Comment by tuvok81** [comment]
ah oke .. and the comment field transfer?

**Comment by edmondas** [comment]
Would you be able to provide more details about that comment field? The textbox in Poweradmin UI uses a different database field and table than PowerDNS. The comments table is available starting from Powerdns 3.x, but there was no such table when Poweradmin was started (PDNS 2.x at that time), so another location was created. Perhaps I should rethink how it might be changed.

**Comment by edmondas** [comment]
Closing this since the main topic has been clarified. I have created a separate ticket for possible improvements.
