### ISSUE TITLE
Error: Invalid configuration: syslog_facility with latest v3.5.1

### ISSUE THREAD

**Issue by MajorFault** [poweradmin/poweradmin#515]
OS: Debian 11.7
PHP: 8.1
Poweradmin: v3.5.1 (commit: 12cdfff3698ec92944c5e80e9aa7f4f5981e1778)

**Problem description:**
When enabling syslog ($syslog_use = true) and keeping all other settings related to syslog at their default values the following error is displayed:

_Error: Invalid configuration: syslog_facility must be an unquoted value and one of the following values: LOG_USER, LOG_LOCAL0, LOG_LOCAL1, LOG_LOCAL2, LOG_LOCAL3, LOG_LOCAL4, LOG_LOCAL5, LOG_LOCAL6, LOG_LOCAL7_

config.inc.php:
```
$syslog_use = true;
$syslog_ident = 'poweradmin';
$syslog_facility = LOG_USER;
```

I've tried setting syslog_facility to any other of the valid facilities and the result is the same.

However, setting $syslog_facility to a deliberately invalid value like LOG_1234 results in "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "LOG_1234"

So it looks like the function validateSyslogFacility() in lib/Infrastructure/Config/ConfigValidator.php is not working as intended.

**Comment by edmondas** [comment]
Thank you for reporting the bug.
Fixed in 10e7fbdb5632cd5c64e70be21632a0348cbd6356
