### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: Rule 'integer' has not been registered with Valitron\Validator::addRule(). i

### ISSUE THREAD

**Issue by djsami** [poweradmin/poweradmin#517]
Hello

3.4.0 to 3.5.1 update promlem.

Fatal error: Uncaught InvalidArgumentException: Rule 'integer' has not been registered with Valitron\Validator::addRule(). in /var/www/html/poweradmin/vendor/vlucas/valitron/src/Valitron/Validator.php:1422 Stack trace: #0 [internal function]: Valitron\Validator->rule() #1 /var/www/html/poweradmin/vendor/vlucas/valitron/src/Valitron/Validator.php(1522): call_user_func_array() #2 /var/www/html/poweradmin/add_record.php(131): Valitron\Validator->rules() #3 /var/www/html/poweradmin/add_record.php(53): AddRecordController->checkId() #4 /var/www/html/poweradmin/add_record.php(193): AddRecordController->run() #5 {main} thrown in /var/www/html/poweradmin/vendor/vlucas/valitron/src/Valitron/Validator.php on line 1422

Add zone error help.

**Comment by edmondas** [comment]
Thank you for the report. The issue has been fixed in the master branch. Soon, there will be a release.
