### ISSUE TITLE
unable to use $iface_templates in config.inc.php

### ISSUE THREAD

**Issue by Jerks1988** [poweradmin/poweradmin#523]
Hi,

i made a copy of the "footer.html", named it "template_footer.html" and customized it for my needs.
How can i now use it through the  $iface_templates parameter in config.inc.php?

I tried it with:
`$iface_templates = 'template_footer';`
and also with
`$iface_templates = 'template_footer.html';`

Both doesn't work. Further explanation with example in your documentation would be really helpful.

Thanks a lot!

Kind regards,

Nico

**Comment by edmondas** [comment]
`$iface_templates` defines the location of a folder where all templates can be customized after copying the originals.

Your goal seems to be to change just one file. Solution:
1. Create folder named custom under templates
2. Create file footer.html
3. Fill out that file with your own content
---
<img width="501" alt="image" src="https://github.com/poweradmin/poweradmin/assets/9033112/652efc5f-c397-4068-98d0-7e954cea45c7">

---
This will result in the following footer change:
<img width="715" alt="image" src="https://github.com/poweradmin/poweradmin/assets/9033112/8e7afb26-5768-4be3-a6b2-c2ca51e0ab59">

**Comment by edmondas** [comment]
Closing this since the main topic has been clarified.
