### ISSUE TITLE
pagination not working

### ISSUE THREAD

**Issue by Zombiefleischer** [poweradmin/poweradmin#526]
![image](https://github.com/poweradmin/poweradmin/assets/44850408/582c9452-0c09-48ee-883c-2764d13c9aa0)
The search finds 450 records, but only shows 10 and the pagination is not working.
The workaround in #501 is only a temporary solution, so a fix would be nice

**Comment by Zombiefleischer** [comment]
Okay, I think the pagination is only for zones and not for records, which is odd. So for folks with only a handful of zones and hundreds of records, it would be nice to also have pagination for that.

**Comment by edmondas** [comment]
Thank you for reporting the bug. I can confirm that it exists and will work on a fix as soon as possible.

**Comment by edmondas** [comment]
Based on my review of this bug report, pagination for found records should work, only minor issue has been fixed.
