### ISSUE TITLE
"List zones"   not show all zones when press any "Show zones beginning with"  letter example h

### ISSUE THREAD

**Issue by kaesjuma** [poweradmin/poweradmin#527]
It that bug or something else?

"List zones"  does not display  all zones when press any "Show zones beginning with"  letter example h
"Show all" display all zones.

**Comment by edmondas** [comment]
Thanks for the bug report. However, I haven't been able to reproduce the problem, so maybe you can check what the result is? Could some domains have a different type or be different in some way?

```sql
SELECT domains.id,
       domains.name,
       domains.type,
       COUNT(records.id) AS count_records,
       users.username,
       users.fullname,
       zones.comment
FROM domains
         LEFT JOIN zones ON domains.id = zones.domain_id
         LEFT JOIN records ON records.domain_id = domains.id AND records.type IS NOT NULL
         LEFT JOIN users ON users.id = zones.owner
WHERE 1 = 1
  AND SUBSTRING(domains.name, 1, 1) = 'h'
GROUP BY domains.name, domains.id, domains.type, users.username, users.fullname, zones.comment
ORDER BY domains.name + 0 <> 0 DESC, domains.name + 0, domains.name
```
Compare the domains that were not returned by this query and see how they differ

**Comment by edmondas** [comment]
I can't reproduce the bug. I am closing this since there has been no response, but I have made an adjustment in the UI so that it shows a more detailed count of available zones by criteria and the total number of zones available. Please reopen if you can provide more details on how to reproduce it.
