### ISSUE TITLE
poweradmin under OpenBSD's chroot - DNSSEC fails badly

### ISSUE THREAD

**Issue by ozgurkazancci** [poweradmin/poweradmin#529]
Hello.

Under OpenBSD OS, since the web server software (both OpenBSD's native 'httpd' and nginx as well) is locked and chrooted to the **/var/www/** directory by the default, my poweradmin installation cannot access the **/usr/local/bin/pdnsutil** tool on the system. Anything out of the chroot folder (/var/www) is unreachable.

Thus, just to try things, I copied the /usr/local/bin/pdnsutil to have one more copy located within the chroot, being; **/var/www/usr/local/bin/pdnsutil**

I then ran "ldd" to query what libraries that binary calls/needs, and added all the libraries and .so files on the system to /var/www/, in their respective folders, like (/var/www)/usr/lib, (/var/www)/usr/local/lib, placed them all.

But none of these helped me use the DNSSEC feature of poweradmin through it's web interface;

![Here](https://i.ibb.co/rQG0z9F/dnssec.png)

Is there any workaround for such a case? Any clue would be much appreciated.

Best.

**Comment by edmondas** [comment]
In my mind, I only have these ideas:
- Try running the same command as in your screenshot without error redirection and with verbose flag enabled
- Possibly, you forgot to copy the pdns configuration with credentials used by `pdnsutil`

**Comment by ozgurkazancci** [comment]
Well, the command was executed by poweradmin itself, enabled dnssec and dnssec debug in config file.

Sqlite3 database file is also within the chroot (/var/www/var/db) and it does works for poweradmin&pdns. The only thing left outside chroot is /etc/pdns/pdns.conf file. Would that matter?

**Comment by edmondas** [comment]
It matters, at least pdsnutil reads the database credentials from this file.

**Comment by ozgurkazancci** [comment]
> It matters, at least pdsnutil reads the database credentials from this file.

Didn't help, ended up by disabling the chroot feature completely from the httpd.
Thanks.

**Comment by edmondas** [comment]
@ozgurkazancci Are you interested in testing experimental code that makes DNSSEC calls via API? It would allow use of chrooted environments without requiring external utility.

**Comment by ozgurkazancci** [comment]
> @ozgurkazancci Are you interested in testing experimental code that makes DNSSEC calls via API? It would allow use of chrooted environments without requiring external utility.

Hi Edmondas, yes sure, why not. I'd love to give it a try&test.

**Comment by edmondas** [comment]
Get the alpha version here and learn how to activate it in the description
https://github.com/poweradmin/poweradmin/releases/tag/v3.7.0-alpha.1
