### ISSUE TITLE
Prepopulate "Add record to zone template" fields

### ISSUE THREAD

**Issue by johnmill** [poweradmin/poweradmin#53]
For zone templates, since they most often contain SOA records, NS records, and MX records--stuff where the left side of the record is implied, why not prepopulate the "Name" field with [ZONE] and the "TTL" field with whatever the system's default is?  This'll save some typing, and will remind people what they've set their default TTL to.

**Comment by GGuiTang** [comment]
Poweradmin - 2.7
When I use web pages to create ". "root zone at the following error:

Error: You have invalid characters in your hostname.
Error: failed - Invalid hostname.
image

Please expert help, thank you

**Comment by GGuiTang** [comment]
zone2sql --gmysql --named-conf named.conf  --zone=root.zone.signed  --zone-name='.' > root.zone.sql

more root.zone.sql
insert into domains (name,type) values ('','NATIVE');

Zone2sql command to generate the SQL language is not correct, also don't know how to solve, please give directions.Thank you very much!!
