### ISSUE TITLE
Use Comments table from PowerDNS original schema instead of custom fields.

### ISSUE THREAD

**Issue by edmondas** [poweradmin/poweradmin#532]
The comments textbox in Poweradmin UI uses a different database field and table than PowerDNS. The comments table is available starting from Powerdns 3.x, but there was no such table when Poweradmin was started (PDNS 2.x at that time), so another location was created. Perhaps I should rethink how it might be changed.

_Originally posted by @edmondas in https://github.com/poweradmin/poweradmin/issues/514#issuecomment-1594091495_

**Comment by mkriegs** [comment]
Doing some upgrade script to copy conntent from old schema to PowerDNS Schema ? 
UI needs to use new Content after upgrade

**Comment by darknight7** [comment]
I'm new here and I'm impressed by how polished poweradmin looks and feels. Comments are key to keep track of what is what without external tools, notebooks and so on, with poweradmin I can only write comments about zones right now while I understand powerdns supports per-record comments. I'm quite surprised that this issue doesn't attract much more traffic.
Thank you for your work so far.

**Comment by edmondas** [comment]
@darknight7 Thanks for pointing this out, but I couldn't find PowerDNS to have this feature, i.e. to store additional information (e.g. a comment) for each record. I even looked at the latest database schema and couldn't find a similar field.
https://github.com/PowerDNS/pdns/blob/master/modules/gmysqlbackend/schema.mysql.sql

**Comment by darknight7** [comment]
Seems you are right unfortunately, the schema speaks clearly.
So I have to assume that's a "hack". A colleague says he's using [PowerDNS-Admin](https://github.com/PowerDNS-Admin/PowerDNS-Admin) (which is WAY too much for me) and can do so. I cannot confirm or deny the claim, assuming the colleague's claim is true they may encapsulate a reference in the comment string then decode it before displaying the entry and the comment.
I'm not saying you should follow suit (though you may think about something similar) but I felt I owed you at least an explanation for my original post. :)

**Comment by edmondas** [comment]
Thank you for bringing this up. I've investigated further and can confirm that PowerDNS does indeed support per-record comments via the comments table in the schema - I apologize for my previous oversight.

A few notes on the implementation:

- While the schema allows multiple comments per record, my implementation currently only supports the first comment for simplicity.

- Existing zone comments will remain in their current location, as this new comments table is specifically designed for record-level comments.

I've added the feature to the master branch. To enable record comments, add the following to your configuration:
```
$iface_record_comments = true
```

Since this doesn't require any schema migrations, I believe this is the most straightforward approach. I'll close this issue, but please open new issues if you encounter any problems with the implementation.

**Comment by mkriegs** [comment]
@edmondas thanks for your effort i will test this for 3.9.0 release!
