### ISSUE TITLE
Bug? The SOA serial is updated but the content was not, on secondary server.

### ISSUE THREAD

**Issue by ozgurkazancci** [poweradmin/poweradmin#533]
Greetings.

A while ago, I edited my zone's SOA records on poweradmin web interface, making it like;
"ns1.mydomain.com info.mydomain.com 2023110500 **14400** 7200 1209600 86400" (updated refresh value from **7200** to **14400**)

Afterwards, both primary&secondary servers have updated their SOA serial number, automatically.

However, even though the secondary server has up-to-date SOA serial nr., it still carries the old SOA values. Like;

```
on primary server: ns1.mydomain.com info.mydomain.com 2023110500 14400 7200 1209600 86400
on secondary server: ns1.mydomain.com info.mydomain.com 2023110500 7200 7200 1209600 86400
```

As it can be seen above, the SOA serial on both servers matches, however the refresh value is **14400** on primary, but it's still **7200** (old value) on the secondary, even though the serial was updated on secondary.. got confused, any clue on that, please?

How could such thing happen, the secondary server updated its SOA serial, getting the same serial from the primary one successfully, but did not update the new SOA Refresh value that I set on primary?

Poweradmin version: 3.6.1
Best,
Özgür.

**Comment by ozgurkazancci** [comment]
The bug is reproducible. Any update on this?

**Comment by edmondas** [comment]
Changing refresh time in this case requires manually incrementing serial. Otherwise, if you only update the refresh time, PowerDNS won't find any differences, and your secondary server will have old records.

**Comment by edmondas** [comment]
@ozgurkazancci Has the change of serial helped you in your case?

Considering possible solutions, I guess I could add more logic to determine if serial was adjusted, but it adds more boilerplate and makes code more complicated.

**Comment by ozgurkazancci** [comment]
I'd like to inform that manually changing the serial (increased it one digit on the primary server) helped.

The secondary server has adjusted the refresh value (14400) from primary server now.

**Comment by edmondas** [comment]
Thank you for your response. Next version will include a fix for it.
