### ISSUE TITLE
poweradmin (latest) fails on 'list all zones' as iface_rowamount is hardcoded to 'all'

### ISSUE THREAD

**Issue by ichdasich** [poweradmin/poweradmin#536]
Moin,

poweradmin (current git head) starts 500ing when selecting 'list all zones' when clicking on 'list all zones' as `DnsRecord->get_zones()`' signature does not accept the hardcoded string type 'all' that is set there.

```
110         } elseif ($letter_start == 'all') {                                     
111             $zones = $dnsRecord->get_zones($perm_view, $_SESSION['userid'], "all", $row_start, 'all', $zone_sort_by);                                       
112         } else {  
```

I guess this broke in the recent pagination refactoring?

**Comment by edmondas** [comment]
Thank you for pointing this out, the code base is undergoing massive refactoring, so not everything may work. Now it should be fixed.

**Comment by ichdasich** [comment]
Thanks, noticed and switched away from head. ;-)

**Comment by edmondas** [comment]
Anyway, if you have time, I would really appreciate if you could test functionality again. For now, the most drastic changes have been made.
