### ISSUE TITLE
bug: Validate TXT records on wrong quotes

### ISSUE THREAD

**Issue by cobyteskb** [poweradmin/poweradmin#544]
Hi There,

When you add / update a TXT record with the wrong double quotes, the whole zone will break and PowerDNS cannot resolve anything anything of the entire zone.

**Good quotes:**
`0 issuewild "digicert.com"`

**Wrong quotes:**
`0 issuewild “digicert.com”`

Error message from PowerDNS when wrong quotes are used:
`Exception building answer packet for xxx.mydomain.com/A (Parsing record content (try 'pdnsutil check-zone'): Data field in DNS should start with quote (") at position 12 of '0 issuewild “digicert.com”') sending out servfail`

**Fix:**
Validate TXT records on these wrong quotes.

**Comment by edmondas** [comment]
@cobyteskb Thanks for the bug report, but I cannot reproduce the issue with the latest release, which includes additional TXT/SPF validation. See #510.

<img width="629" alt="image" src="https://github.com/poweradmin/poweradmin/assets/9033112/bb86701d-8279-4efa-b8e3-be32d78134e0">

**Comment by edmondas** [comment]
Closed because I can't reproduce it with the latest changes and there's no response from the bug submitter. In any case, feel free to reopen and provide more details.

**Comment by edmondas** [comment]
Another observation - for the record "0 issue digicert.com", you should use the CAA (Certification Authority Authorization) DNS resource record type.

https://docs.digicert.com/en/certcentral/manage-certificates/dns-caa-resource-record-check.html#authorize-digicert-to-issue-wildcard-certificates-for-a-domain
