### ISSUE TITLE
Duplicate search results when a zone has multiple Owners

### ISSUE THREAD

**Issue by cobyteskb** [poweradmin/poweradmin#545]
When a zone has multiple owners (By default only one in our environment) the search results show multiple records. One for every owner.

This is really confusing because it implies that there are duplicate records within the same zone. If you remove one, they are all removed.

**Comment by edmondas** [comment]
@cobyteskb Try adding this line to group records (`inc/config.inc.php`):
```
$iface_search_group_records = true;
```
Would it be better to make this the default behavior?

**Comment by cobyteskb** [comment]
Cool, that worked!

For me it makes sense to make this the default behavior yes.
