### ISSUE TITLE
Can't add DNSSEC to Zone

### ISSUE THREAD

**Issue by pomland-94** [poweradmin/poweradmin#546]
Hey,
when I try to add DNSSEC to a Zone I get a Blank Site and my Apache2 error log Says:

```shell
[Sun Feb 18 21:10:55.520577 2024] [proxy_fcgi:error] [pid 15633:tid 281473106833696] [remote 217.83.0.222:50111] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Poweradmin\\Domain\\Exception\\ApiErrorException: file_get_contents(http://127.0.0.1:8081/api/v1/servers/localhost/zones/elastic-dns.org): Failed to open stream: HTTP request failed! HTTP/1.1 422 Unprocessable Entity\r\n in /var/www/dns.elastic-cloud.org/public_html/lib/Infrastructure/Api/HttpClient.php:55\nStack trace:\n#0 /var/www/dns.elastic-cloud.org/public_html/lib/Infrastructure/Api/PowerdnsApiClient.php(59): Poweradmin\\Infrastructure\\Api\\HttpClient->makeRequest()\n#1 /var/www/dns.elastic-cloud.org/public_html/lib/Infrastructure/Dnssec/DnsSecApiProvider.php(73): Poweradmin\\Infrastructure\\Api\\PowerdnsApiClient->secureZone()\n#2 /var/www/dns.elastic-cloud.org/public_html/edit.php(136): Poweradmin\\Infrastructure\\Dnssec\\DnsSecApiProvider->secureZone()\n#3 /var/www/dns.elastic-cloud.org/public_html/edit.php(338): EditController->run()\n#4 {main}\n  thrown in /var/www/dns.elastic-cloud.org/public_html/lib/Infrastructure/Api/HttpClient.php on line 55', referer: https://dns.elastic-dns.org/edit.php?name=elastic-dns.org&id=1
```

My PowerDNS Server is reachable and the API is configured, when I make Requests with curl everything is working fine.

Anyone who ha san Idea?

**Comment by SkySai1** [comment]
Well, as say in [wiki](https://github.com/poweradmin/poweradmin/wiki/DNSSEC) of the project:
>Note: There's no real support in Poweradmin for DNSSEC record signing, key management and rollover."

I'm using pdnsutil:
`pdnsutil secure-zone powerdnssec.org`

Or signing zone by existing keys:
`pdnsutil import-zone-key ZONE FILENAME`

**Comment by edmondas** [comment]
@pomland-94 I can only confirm that the problem does exist, it's currently under investigation and I'll get back to you with a solution as soon as possible.

**Comment by edmondas** [comment]
OK, it seems that in my case the PowerDNS server was not configured properly (SQL schema was missing, so it refused to return anything of value). Could you check with curl if the PowerDNS API returns any information?

```
curl --header "X-API-Key: YOUR_API_KEY" http://127.0.0.1:8081/api/v1/servers
```

**Comment by edmondas** [comment]
Also check if there's response for your domain
```
curl --header "X-API-Key: YOUR_API_KEY" http://127.0.0.1:8081/api/v1/servers/localhost/zones/elastic-dns.org
```

**Comment by pomland-94** [comment]
Thank's found the Solution. I forgot to activate DNSSEC in the mysql conf.

```conf
launch=gmysql

gmysql-host=HOST
gmysql-dbname=DBNAME
gmysql-user=USER
gmysql-password=PASSWORD

# This was missing
gmysql-dnssec=yes

```

**Comment by edmondas** [comment]
Thank you for your reply. I have made a small improvement - added a check to see if DNSSEC is enabled on the server side.
