### ISSUE TITLE
cp install/htaccess.dist .htaccess doesn't exist file in installer

### ISSUE THREAD

**Issue by APIVersa** [poweradmin/poweradmin#549]
Installer on final page say:

> If you want support for the URLs used by other dynamic DNS providers, run "cp install/htaccess.dist .htaccess" and enable mod_rewrite in Apache.

However said file does not exist. At least if using github here. I will check the ZIP, but the github seems to be missing it.

If you go on the github repo and go to install folder, there is no htaccess.dist there.

Thanks,
API VERSA OU

UPDATE: I checked the zips on the website also, bleeding edge and release, there is no such file.

**Comment by edmondas** [comment]
Good catch. Thanks for reporting it. It seems that this file was removed a long time ago, as it contained custom rewrite rules created by someone, but not needed for regular installation. To avoid confusing other users, I will remove this message from the installer.

**Comment by edmondas** [comment]
If you still wonder what was in it, you can check out the 3.2.0 version. https://github.com/poweradmin/poweradmin/blob/v3.2.0/install/htaccess.dist
