### ISSUE TITLE
Unable to find template "index_.html" (looked into: templates). After login

### ISSUE THREAD

**Issue by Sephiroth80** [poweradmin/poweradmin#551]
Hi, i have this problem after login
Unable to find template "index_.html" (looked into: templates).
I don't find index_.html in template folder
i have configure in config.inc.php this line
$iface_templates = 'templates';
can you help me with this problem
Thanks

**Comment by Sephiroth80** [comment]
resolved

**Comment by edmondas** [comment]
@Sephiroth80 I'm just wondering what the problem was, did you remove the default config or did you set the $iface_index to ""?

**Comment by Sephiroth80** [comment]
is the first time i installed this so, i start to figurate all the instalation
so i put this lines
$iface_zonelist_template = true;
$iface_zone_comments = true;
$iface_index = 'cards';
and works
