### ISSUE TITLE
User input in SearchController.php record_sort_by and zone_sort_by not sanitized

### ISSUE THREAD

**Issue by MasterTaffer** [poweradmin/poweradmin#553]
Sort by inputs `record_sort_by` and `zone_sort_by` in zone/record search queries are not sanitized and used in SQL queries as-is. SearchController.php doesn't use any kind of validation for the user input:

https://github.com/poweradmin/poweradmin/blob/4af0a7d1e35891f7d3d5e8580de9085b3e85a0e8/lib/Application/Controller/SearchController.php#L59-L62

https://github.com/poweradmin/poweradmin/blob/4af0a7d1e35891f7d3d5e8580de9085b3e85a0e8/lib/Application/Controller/SearchController.php#L135-L145

These variables are then passed to ZoneSearch and RecordSearch objects and used in the SQL queries

https://github.com/poweradmin/poweradmin/blob/4af0a7d1e35891f7d3d5e8580de9085b3e85a0e8/lib/Application/Query/ZoneSearch.php#L122
https://github.com/poweradmin/poweradmin/blob/4af0a7d1e35891f7d3d5e8580de9085b3e85a0e8/lib/Application/Query/RecordSearch.php#L97

**Comment by edmondas** [comment]
Thanks for the good find, some time ago I'd seen it a bit suspiciously, but spent time fixing other problems.
