### ISSUE TITLE
Uncaught Exception of class naming in BasicRouter.php on line 104

### ISSUE THREAD

**Issue by SkySai1** [poweradmin/poweradmin#554]
Hello catch some errors in main page:

**At "Add supermaster" pressing:**
Fatal error: Uncaught Exception: Class \Poweradmin\Application\Controller\ListSupermastersController not found in /app/lib/Application/Routing/BasicRouter.php:104 Stack trace: #0 /app/index.php(76): Poweradmin\Application\Routing\BasicRouter->process() #1 {main} thrown in /app/lib/Application/Routing/BasicRouter.php on line 104

**At "List supermasters" pressing:**
Fatal error: Uncaught Exception: Class \Poweradmin\Application\Controller\ListSupermastersController not found in /app/lib/Application/Routing/BasicRouter.php:104 Stack trace: #0 /app/index.php(76): Poweradmin\Application\Routing\BasicRouter->process() #1 {main} thrown in /app/lib/Application/Routing/BasicRouter.php on line 104

**At deleteing supermaster:**
Fatal error: Uncaught Exception: Class \Poweradmin\Application\Controller\DeleteSupermasterController not found in /app/lib/Application/Routing/BasicRouter.php:104 Stack trace: #0 /app/index.php(76): Poweradmin\Application\Routing\BasicRouter->process() #1 {main} thrown in /app/lib/Application/Routing/BasicRouter.php on line 104

I bad in frontend development so my workaround is renaming few files in poweradmin/lib/Application/Controller:
AddSuper**M**asterController.php -> AddSuper**m**asterController.php
ListSuper**M**astersController -> ListSuper**m**astersController
DeleteSuper**M**asterController.php -> DeleteSuper**m**asterController.php

**Comment by edmondas** [comment]
@SkySai1 Thanks for the bug report, I'm still wondering why I can't reproduce it on my local machine, maybe my file system is not case sensitive, but anyway the filenames have been adjusted.
