### ISSUE TITLE
Error 500 add supermaster on the gui

### ISSUE THREAD

**Issue by Sephiroth80** [poweradmin/poweradmin#555]
Hi, i have this issue when i click on the add supermaster botom on the gui
show me http error 500
this is the result of the tail -f

tail -f www-error.log
[25-Apr-2024 18:27:00 UTC] PHP Fatal error:  Uncaught Exception: Class \Poweradmin\Application\Controller\AddSupermasterController not found in /opt/poweradmin-master/lib/Application/Routing/BasicRouter.php:104
Stack trace:
#0 /opt/poweradmin-master/index.php(76): Poweradmin\Application\Routing\BasicRouter->process()
#1 {main}
  thrown in /opt/poweradmin-master/lib/Application/Routing/BasicRouter.php on line 104
[25-Apr-2024 18:28:49 UTC] PHP Fatal error:  Uncaught Exception: Class \Poweradmin\Application\Controller\ListSupermastersController not found in /opt/poweradmin-master/lib/Application/Routing/BasicRouter.php:104
Stack trace:
#0 /opt/poweradmin-master/index.php(76): Poweradmin\Application\Routing\BasicRouter->process()
#1 {main}
  thrown in /opt/poweradmin-master/lib/Application/Routing/BasicRouter.php on line 104

is a problem with /etc/pdns/pdns.conf ? or in /opt/poweradmin-master/inc/config.inc.php

Thanks a lot

**Comment by edmondas** [comment]
@Sephiroth80 this seems to be duplicate to #554. The solution is to change the filenames, but in any case I will be making updates to the master branch soon.

By the way, which PHP version and operating system are you using? By the way, which PHP version and operating system are you using? It's interesting that I can't reproduce it on my local machine, perhaps because my file system is not case-sensitive.

**Comment by SkySai1** [comment]
> by the way, which PHP version and operating system are you using?
Hello, im from #554, in my case i using Docker image as is from master branch

**Comment by edmondas** [comment]
@SkySai1 Thanks for the info. I'm still not sure why I can't reproduce the filename case problem, but it's now fixed in the master. Still, keep in mind that the docker image is mostly for testing, it needs to be more polished for production use. I recently switched from an apache-based image, which had far too many vulnerable packages, to an alpine-based image with php running as the http server, so not sure how this might affect your use.

**Comment by edmondas** [comment]
@Sephiroth80 Please get the latest code and see if it works now. Closing this ticket as it should be resolved.

**Comment by Sephiroth80** [comment]
Hi
PHP 8.1.28 (cli) (built: Apr 10 2024 05:53:50) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.28, Copyright (c) Zend Technologies

Red Hat Enterprise Linux release 8.9 (Ootpa)

i was change the files name like https://github.com/poweradmin/poweradmin/issues/554
but i stil have error 500, i was restar everything but nothing.
 465  cp AddSuperMasterController.php AddSupermasterController.php
  466  cp ListSuperMastersController.php ListSupermastersController.php
  467  cp DeleteSuperMasterController.php DeleteSupermasterController.php
  then i was renamed the old files with 1

**Comment by Sephiroth80** [comment]
> Hi PHP 8.1.28 (cli) (built: Apr 10 2024 05:53:50) (NTS gcc x86_64) Copyright (c) The PHP Group Zend Engine v4.1.28, Copyright (c) Zend Technologies
> 
> Red Hat Enterprise Linux release 8.9 (Ootpa)
> 
> i was change the files name like #554 but i stil have error 500, i was restar everything but nothing. 465 cp AddSuperMasterController.php AddSupermasterController.php 466 cp ListSuperMastersController.php ListSupermastersController.php 467 cp DeleteSuperMasterController.php DeleteSupermasterController.php then i was renamed the old files with 1

Btw, i make the modification just like this link
https://github.com/poweradmin/poweradmin/commit/722af4b7b001a5a18a85619de44a55c00d034c24

**Comment by edmondas** [comment]
Could you check your http server logs again because if you did everything correctly renamed files and class names then it should work, I tested it on a custom docker image:
```
sh-5.1$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.3 (Plow)

sh-5.1$ php -v
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS gcc aarch64)

git reflog
ede6db45 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/poweradmin/poweradmin.git
```

**Comment by Sephiroth80** [comment]
> git reflog

httpd]# tail -f error_log
[Fri Apr 26 11:57:53.586267 2024] [lbmethod_heartbeat:notice] [pid 3497361:tid 140493005789504] AH02282: No slotmem from mod_heartmonitor
[Fri Apr 26 11:57:53.586926 2024] [http2:warn] [pid 3497361:tid 140493005789504] AH02951: mod_ssl does not seem to be enabled
[Fri Apr 26 11:57:53.589584 2024] [mpm_event:notice] [pid 3497361:tid 140493005789504] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) configured -- resuming normal operations
[Fri Apr 26 11:57:53.589608 2024] [core:notice] [pid 3497361:tid 140493005789504] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Apr 26 12:08:48.053143 2024] [mpm_event:notice] [pid 3497361:tid 140493005789504] AH00492: caught SIGWINCH, shutting down gracefully
[Fri Apr 26 12:08:49.106726 2024] [suexec:notice] [pid 3502918:tid 140393726363968] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Apr 26 12:08:49.119677 2024] [lbmethod_heartbeat:notice] [pid 3502918:tid 140393726363968] AH02282: No slotmem from mod_heartmonitor
[Fri Apr 26 12:08:49.120377 2024] [http2:warn] [pid 3502918:tid 140393726363968] AH02951: mod_ssl does not seem to be enabled
[Fri Apr 26 12:08:49.123296 2024] [mpm_event:notice] [pid 3502918:tid 140393726363968] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) configured -- resuming normal operations
[Fri Apr 26 12:08:49.123318 2024] [core:notice] [pid 3502918:tid 140393726363968] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by edmondas** [comment]
Apart from a few warnings, there are no errors in this log.

**Comment by Sephiroth80** [comment]
Hi there, you can close the report, i don't know but now is working
