### ISSUE TITLE
Text errors in locale/i18n-template-php.pot 

### ISSUE THREAD

**Issue by tokul** [poweradmin/poweradmin#569]
#: /install/templates/step3.html
msgid "Provide the name username"

#: /lib/Dnssec.php
msgid "Failed to active DNSSEC key."

Maybe locations in .pot are not correct or locale/i18n-template-php.pot is out of date.

poweradmin 3.7.0

**Comment by edmondas** [comment]
Yes, it seems to be out of date. I was using a special script for this, but now we also have translations in twig template files, so I need to rethink the solution, maybe I reuse something from the Symphony framework.

**Comment by edmondas** [comment]
@tokul I've updated the translation file in the master branch, but it may not be perfect, in general this needs more checking, but I have limited time. However, if you find any inconsistencies, please file a bug.
