### ISSUE TITLE
[php:error]

### ISSUE THREAD

**Issue by rricker1** [poweradmin/poweradmin#571]
FreeBSD-13.3
PHP-8.1
Apache-24
PowerAdmin-3.7

Php is throwing an error on first run/install:
[php:error] [pid 3231] [client xxx.xxx.xxx.xxx:55946] PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /usr/local/www/poweradmin/index.php:27\nStack trace:\n#0 {main}\n  thrown in /usr/local/www/poweradmin/index.php on line 27

Randy

**Comment by rricker1** [comment]
Indeed... Thanks for the pointer. I also needed php-filter and php-tokenizer. Not thouoghly tested on php82 but php81 is obsoleted for FreeBSD-13.3.

For FreeBSD + MySQL
pkg install php82 php82-gettext php82-intl php82-pdo php82-pdo_mysql php82-session php82-filter php82-tokenizer

Randy

**Comment by edmondas** [comment]
Anyway, thanks. I updated the documentation and added some checks for these PHP extensions.
