### ISSUE TITLE
dnssec with poweradmin on a different server

### ISSUE THREAD

**Issue by tbhbestdevman** [poweradmin/poweradmin#573]
I have poweradmin on a webserver apart from my DNS server as it allows me to use less resources on one server or another, I'm unable to turn DNSsec on because it required a file outside of the webserver that I believe would be on my powerdns server. is there any bypass just so it says a domain is secured or not?

**Comment by edmondas** [comment]
DNSSEC functionality can be accessed via the API by adding this type of configuration:
```
$pdnssec_use = true;
$pdns_api_url = 'http://127.0.0.1:8081'; // Replace the PowerDNS API URL with your own
$pdns_api_key = '65b5dea9-dcfd-4a81-89dd-9f7a1afb0f10'; // Enter your API key here.
```

**Comment by edmondas** [comment]
@tbhbestdevman Did the proposed solution meet what you needed, and did it work?
