### ISSUE TITLE
Tag v3.8.0 wrong: v.3.8.0

### ISSUE THREAD

**Issue by rh-org** [poweradmin/poweradmin#575]
Hey @edmondas. Thanks for all the effort you're putting into this project.

While doing an upgrade, I've realized, that there's an additional `.` in the tag, between `v` and `3`. This results in the tag `v.3.8.0`.

Mind changing the tag to `v3.8.0`?

Thanks!

**Comment by edmondas** [comment]
@rh-org Thanks, good catch, it's so easy to make funny mistakes when I'm in a hurry.
