### ISSUE TITLE
Forgot admin username&password?

### ISSUE THREAD

**Issue by ozgurkazancci** [poweradmin/poweradmin#576]
Hi there.

Since I haven't used the poweradmin installed on my system for a long time, I forgot my administration username and password.
Is there a way to recover/reset them?

Db: sqlite3

Regards.

**Comment by edmondas** [comment]
Perhaps the easiest way would be to update the stored hash in the database. Not sure which password encryption method you use, theoretically you could also enter an MD5 password and later change it via the web interface to match your system settings.

```
htpasswd -nbBC 12 "" your_password | tr -d ':\n'
```

Use same cost factor as defined in your config in `$password_encryption_cost` (or default 12).

Connect to your database (in your case sqlite3 DB_FILE):
```
UPDATE users
SET password = 'new_hashed_password'
WHERE username = 'target_username';
```

**Comment by ozgurkazancci** [comment]
My encryption method is bcrypt, tried both generating bcrypt, also md5, none of them worked at all.
changed to: $password_encryption = 'md5'; and generated md5, nothing changed.
I got correct username as well, doing WHERE username ='admin'; but nothing works so far..

**Comment by edmondas** [comment]
Hard to say what you are doing wrong, use this way multiple times, even with MD5. By the way there's no need to change password encryption, password hash is automatically detected. So if your system is using bcrypt, you will still be able to use the MD5 hash.

```
echo -n "supersecret" | md5
9a618248b64db62d15b300a07b00580b
```

then
```
UPDATE users
SET password = '9a618248b64db62d15b300a07b00580b'
WHERE username = 'admin';
```

Could you be using special characters in your password? Or maybe when you copy/paste, the trailing end line is added invisibly.

**Comment by ozgurkazancci** [comment]
Step 1:

ns1# sqlite3 /var/www/var/db/powerdns/powerdns.sqlite3
SQLite version 3.44.2 2023-11-24 11:41:44
Enter ".help" for usage hints.

Step 2:
sqlite> UPDATE users
   ...> SET password = '1b3231655cebb7a1f783eddf27d254ca'
   ...> WHERE username = 'admin';
sqlite> .exit

Step 3 (to verify the change):

sqlite> select * from users;
1|admin|1b3231655cebb7a1f783eddf27d254ca|Administrator|admin@example.net|Administrator with full rights.|1|1|0

Still doesn't work.

**Comment by edmondas** [comment]
Could you have a look if your user has any permissions?
```
SELECT *
FROM perm_templ_items
WHERE templ_id = 1;
```
Otherwise, I have no idea what could be wrong with your installation.

**Comment by ozgurkazancci** [comment]
Here it is;
```
select * from perm_templ_items where templ_id=1;
1|1|53
```

**Comment by edmondas** [comment]
@ozgurkazancci That's weird! This is not the first time I have seen or had users report such a mysterious problem, so it would be great to finally understand it. Or maybe we can find another way to debug it further? Theoretically, you could add some print statements to the LegacyAuthenticateSession class to see which code branch it fails on, maybe that could help us understand the root cause.

Maybe there is a secure way to share your configuration and database for analysis? It would also be good to know more details about the operating system, PHP version and it's extensions?

**Comment by ozgurkazancci** [comment]
Thanks so much for your effort and interest on this issue @edmondas , surely I would love to share entire server access for your check. Simply drop here an email address please.

Regards.

**Comment by edmondas** [comment]
> Thanks so much for your effort and interest on this issue @edmondas , surely I would love to share entire server access for your check. Simply drop here an email address please.
> 
> Regards.

You can use the same email address as in my GitHub profile.

**Comment by ozgurkazancci** [comment]
Done, sent you an email with credentials.

**Comment by edmondas** [comment]
The main problem was that the installation wasn't protected by an SSL certificate, so the connection wasn't secure, and the recently added cookie protection caused this weird problem.

@ozgurkazancci Thank you for providing the access to the server.

Link to the solution
https://github.com/poweradmin/poweradmin/issues/577#issuecomment-2291116264

**Comment by cmaurand** [comment]
update users set password = md5('desired_password') where username = 'admin'; 
This worked for me.

**Comment by edmondas** [comment]
Password recovery functionality has been implemented. See #90 for implementation details. This feature will be included in the next release.
