### ISSUE TITLE
I can't sign in after the initial installation.

### ISSUE THREAD

**Issue by ohs1018** [poweradmin/poweradmin#577]
Hi. I recently discovered PowerDNS and tried to use PowerAdmin with it, but no matter how many times I tried to log in after installing it, I keep getting the login page with no success or failure message.

Here's what I've tried to do

1. check PHP session folder permissions
2. check DB permissions
3. check web folder permissions
4. change the encryption method
5. reinstalled

I can't log in even after trying the above methods.

The server operation information is as follows.

OS : Ubuntu 22.04.4 LTS
Web : nginx/1.18.0
PHP : PHP 8.1.2

Translated with DeepL.com (free version)

**Comment by edmondas** [comment]
Hi, thanks for the report, at the moment what I know is that session handling with fpm and php works kinda weird, therefore csrf protection fails. I'm currently investigating and looking into possible solutions.

**Comment by edmondas** [comment]
Can you check if this resolves your issue? Edit main index.php and change parameter for secure to false in session_set_cookie_params.

```
session_set_cookie_params([
    'secure' => false,
    'httponly' => true,
]);
```

Could it be that your installation does not have a proper https connection? Is it using http (without SSL)?

**Comment by ohs1018** [comment]
@edmondas

I changed that option as you suggested and it worked!

Thank you very much.
