### ISSUE TITLE
What is the default admin password.

### ISSUE THREAD

**Issue by mikevipe** [poweradmin/poweradmin#580]
Hello,

I cant seem to find any documentation on the default admin password.

I went through the installer and when manually querying the database, it appears to be the same default from the sql installer.

admin
$2y$12$10ei/WGJPcUY9Ea8/eVage9zBbxr0xxW82qJF/cfSyev/jX84WHQe

Please help.

I see no way to reset this for myself.

**Comment by XenoPhage** [comment]
Have you tried admin/admin or admin/password?  Or maybe admin/poweradmin?  Those would be my immediate guesses..

---------------------------
Jason 'XenoPhage' Frisvold
***@***.***
http://blog.godshell.com
---------------------------
"There is an art to flying, or rather a knack. Its knack lies in
learning to throw yourself at the ground and miss. ... Clearly, it is
this second part, the missing, that presents the difficulties."
- Hitchhiker's Guide to the Galaxy

**Comment by mikevipe** [comment]
have tried admin/admin admin/password

**Comment by mikevipe** [comment]
I just removed and reinstalled and its working now. Not sure why it never updated the default password the first time.

Thank you

**Comment by edmondas** [comment]
@mikevipe There's no default password, you create it and specify it during installation.

**Comment by edmondas** [comment]
Some information on how to reset the password using CLI tools and SQL can be found here: #576
