### ISSUE TITLE
display the DISABLED flag in search result

### ISSUE THREAD

**Issue by sblanchet** [poweradmin/poweradmin#591]
It would be very convenient if the flag **Disabled** could be displayed in the search result

![poweradmin_display_disabled_flag_in_search](https://github.com/user-attachments/assets/f399cc41-c304-40a3-85cc-e73feb9d3ba1)

otherwise we have to click on the Edit button to see the flag status.

**Comment by edmondas** [comment]
Added the requested column to the search results, but to maintain consistency between views it will be at the end of the row. The next release 3.9.0 will include this improvement.

<img width="1321" alt="Screenshot 2024-10-05 at 10 42 30" src="https://github.com/user-attachments/assets/6f84e1d6-8716-4e0f-b11e-98ff1080b26f">
