### ISSUE TITLE
Switch theme generate error while in edit zone page

### ISSUE THREAD

**Issue by glnengineer** [poweradmin/poweradmin#593]
Switch theme works everywhere but when in edit zone page.

:  Error: Invalid or unexpected input given.

OS: Rocky 9.4
Version: : Git clone 2 days ago
PHP: 8.2.13
MariaDB: 10.11.6
Nginx: 1.20.1

**Comment by edmondas** [comment]
@glnengineer I can confirm that this problem occurs on all pages where there are additional parameters other than the page name.

**Comment by edmondas** [comment]
@glnengineer Master branch now has a fix. Theme switching uses JavaScript, no full page reload needed. Can you check if it works?

**Comment by glnengineer** [comment]
Issue resolved. You can close this bug ticket. Thanks.
