### ISSUE TITLE
Remove "Add also reverse record" when edit reverse zone.

### ISSUE THREAD

**Issue by glnengineer** [poweradmin/poweradmin#594]
Hello,

I noticed that there is an option for "Add also reverse record" when edit  x.x.x..in-addr.arpa zone.

This should be removed for PTR record creation.

OS: Rocky 9.4
Version: : Git clone 3 days ago
PHP: 8.2.13
MariaDB: 10.11.6
Nginx: 1.20.1

**Comment by edmondas** [comment]
Thanks for report, issue fixed.
