### ISSUE TITLE
LDAP Display Bug

### ISSUE THREAD

**Issue by glnengineer** [poweradmin/poweradmin#596]
OS: Rocky 9.4
Version: : Git cloned 4 hrs agp. (3.9.0)
PHP: 8.2.13
MariaDB: 10.11.6
Nginx: 1.20.1

Minor display issue under "User administration" :

The default local "admin" account shows as LDAP "checkbox" enabled when log in as non-admin account using a custom permission template with "user_view_others" option enabled. 

Issue disappear if login as admin or another user (Local/LDAP) with "Administrator" template permission.

**Comment by glnengineer** [comment]
Our Poweradmin is configured to use OpenLDAP config. settings.

**Comment by edmondas** [comment]
Thanks as always, the visual discrepancy has been fixed.
