### ISSUE TITLE
Current install instructions do not install. (Debian)

### ISSUE THREAD

**Issue by DaanSelen** [poweradmin/poweradmin#598]
Hello PowerAdmin,

I am not known with this front-end specifically. But following the current installation steps did not produce a functional front-end. Can you please elaborate on the packages needed, and the steps that need to be taken.

**Comment by DaanSelen** [comment]
What i meant is I copied the instructions on the README.md and then it skips to "Go to URL" without ever mentioning how to front this front-end specifically. And the packages listed in the apt install (first one) are not available in the Debian default repositories. So are they now included in the standards or unnecessary?

**Comment by edmondas** [comment]
It's hard to keep up with these package names, as I see they've moved most modules to php8.2-common. In general you're right, if you're not familiar with php or such old codebases then I agree that it's not clear how the frontend is served and there are no ways to use apache with mod_php or nginx with php-fpm.

Installation and setup might be different so not sure. I know I do not have enough time to write proper documentation, maybe I should spend some evenings on it. Otherwise, if you could be more specific about what's not clear, I'll try to answer that.

PS. Thanks for pointing out the problem with the documentation, I'll try to review the steps.

**Comment by DaanSelen** [comment]
Just for my personal context, I need to research PowerDNS front-ends. And I am unfamiliar with PHP itself. I do not know how to deploy this, and configure the parameters. I would love to help but I would first need asomething... even if its only a script.

**Comment by edmondas** [comment]
The easiest way to evaluate Poweradmin without actually connecting to PowerDNS is to use a docker image.
1. Get the source code (download release file or with git)
2. Change to the directory where the files are located and run the following commands
```
docker build --no-cache -t poweradmin .
docker run -d --name poweradmin -p 8080:80 poweradmin
```
3. Open your browser and go to http://localhost:8080
4. Login with the credentials provided: username - admin, password - testadmin

This installation uses SQLite to store all the data.

**Comment by DaanSelen** [comment]
I can also fork the repo and add the Debian install instructions. Give me some time!

**Comment by edmondas** [comment]
@DaanSelen I really appreciate your input and time, so please do what is easiest for you.

I also have another vision - to move all the existing information from the wiki and other places to a more friendly documentation site based on mkdocs. It currently only contains a draft navigation and no information.

If you're interested, the repo is https://github.com/poweradmin/poweradmin-docs and the result will be visible at https://docs.poweradmin.org/.

**Comment by DaanSelen** [comment]
https://github.com/poweradmin/poweradmin/pull/601

Currently working on here.

**Comment by dirkwa** [comment]
Good morning, 

I also thought to deploy poweradmin on debian 12. As I read here the current release 3.8.1 is not working, correct? 
Thanks.

**Comment by edmondas** [comment]
@dirkwa  It should work fine, maybe only the installation steps in the readme are wrong, but check what @DaanSelen has done, in any case please be more specific about what error you have.

**Comment by edmondas** [comment]
Closing, as the changes were merged and README was updated accordingly.
