### ISSUE TITLE
Installer & SQLite - Step 5 - Unable to continue

### ISSUE THREAD

**Issue by whisperzer0** [poweradmin/poweradmin#599]
FreeBSD 14.1
Apache 24
PHP 8.4
SQLite 
Git cloned from master
No errors are thrown

---

When proceeding with the installer, this ends up looping upon the following message when attempting to continue to the next step.

> Step 5: Create limited-rights user
> You now want to give limited rights to Poweradmin so it can update the data in the tables. To do this, you should create a new user and give it rights to select, delete, insert, and update records in the PowerDNS database.
> 
> Execute the following commands based on your database:
> 
> After you have added the new user, proceed with this installation procedure.
> You now want to give limited rights to Poweradmin so it can update the data in the tables. To do this, you should create a new user and give it rights to select, delete, insert, and update records in the PowerDNS database.

I've attempted the guide via: https://github.com/poweradmin/poweradmin/wiki/SQLite and still when I click the button to proceed to Step 6 but it just refreshes Step 5 with the same message.

The SQLite DB is being created and appears to be filled with some schema. 
The same occurs with the SQLite created via the script providing: schema.sqlite3.sql and running the installer.

However if I create the config.inc.php manually, it works, minus PHP warnings which I've submitted a PR fix to.

**Comment by edmondas** [comment]
@whisperzer0 Thank you for catching this issue. Due to ongoing major refactoring of the installer code, I accidentally specified an incorrect step for the SQLite database. This has been fixed, though please note that the master branch may experience temporary instability during this refactoring period.
