### ISSUE TITLE
Sorting of records in zone is weird after checkout of latest commit in master

### ISSUE THREAD

**Issue by michielvisser** [poweradmin/poweradmin#605]
I've checked out commit 322b7ba today which is in the master branch. When I look at the sorting of the records in my zones I notice that this has changed (which I expected based on commit 0e85a5d6 and 30978a4), but it looks weird to me - when listing all records in the zone for editing, all records that end in a number ends up at the bottom of the list. As an example, a screenshot of the new ordering of the records (only showing the first part of the record names):

![image](https://github.com/user-attachments/assets/347071d1-3af0-4a84-a9d4-3c5bf411ca0f)

So, it is basically two lists after eachother:
1. All records in alphabetical order that do not have any numbers in the name.
2. All records that end in a number
 
FYI - all the records ending in a number are part of a structured naming schema for servers (server function, first digit is site number, second digit is server number) it keeps them all nice together. But I thought to at least mention this in an issue as I cannot change it back to how it was (unless there is a config option for it - haven't checked?). 

When reversing the sort order on name with the arrows it just reverses the lists and then all records ending in a number end up at the top of the list in reverse alpha-order and then the other records in reverse order...

This might be intentional based on the commits, not sure.

**Comment by edmondas** [comment]
Closing ticket - sorting issues resolved. Please reopen if sort order problems persist.
