### ISSUE TITLE
php error Data too long

### ISSUE THREAD

**Issue by gav-de-2** [poweradmin/poweradmin#608]
I cannot save a certain zone as template.
If I try, i run into this error:
[Wed Nov 20 10:28:15.223911 2024] [php:error] [pid 12206] [client 213.216.0.236:63972] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1 in /var/www/html/poweradmin-3.8.1/lib/ZoneTemplate.php:457\nStack trace:\n#0 /var/www/html/poweradmin-3.8.1/lib/ZoneTemplate.php(457): PDO->exec()\n#1 /var/www/html/poweradmin-3.8.1/lib/Application/Controller/EditController.php(353): Poweradmin\\ZoneTemplate::add_zone_templ_save_as()\n#2 /var/www/html/poweradmin-3.8.1/lib/Application/Controller/EditController.php(78): Poweradmin\\Application\\Controller\\EditController->saveTemplateAs()\n#3 /var/www/html/poweradmin-3.8.1/lib/Application/Routing/BasicRouter.php(108): Poweradmin\\Application\\Controller\\EditController->run()\n#4 /var/www/html/poweradmin-3.8.1/index.php(86): Poweradmin\\Application\\Routing\\BasicRouter->process()\n#5 {main}\n  thrown in /var/www/html/poweradmin-3.8.1/lib/ZoneTemplate.php on line 457, referer: https://poweradmin.x.x/index.php?page=edit&name=volp.com&id=9

Other zones can be saved as template.
This one contains a DKIM record, which is long. This may cause "Data too long"

**Comment by edmondas** [comment]
Seems related to #396
In your case, I would suggest manually increasing the field size.

For MySQL/MariaDB
```
ALTER TABLE zone_templ_records
MODIFY COLUMN content varchar(2048) NOT NULL;
```

For PostgreSQL
```
ALTER TABLE zone_templ_records
    ALTER COLUMN content TYPE varchar(2048),
    ALTER COLUMN content SET NOT NULL;
```
