### ISSUE TITLE
3.9.0 can not create A record.

### ISSUE THREAD

**Issue by dirkwa** [poweradmin/poweradmin#609]
Hello Team,

I installed poweradmin v3.9.0 and have the following error when adding a A record to a master zone:

![image](https://github.com/user-attachments/assets/844f2ace-a255-4cce-87b8-825c4824dda3)

An error occurred while processing the request: The domain `185.40.132.12` is invalid: this is an IPv4 host.

The related PTR record was created. 

![image](https://github.com/user-attachments/assets/175fcdfa-9c86-480b-87e8-671bbdeab050)

What can I do/change?

Thanks,
Dirk

**Comment by dirkwa** [comment]
this works


**pdnsutil add-record digmedia.net ns1 A 185.40.132.12**
Nov 21 23:46:32 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
New rrset:
ns1.digmedia.net. 3600 IN A 185.40.132.12

**Comment by dirkwa** [comment]
I could even edit this record in PowerAdmin (i changed the TTL). 

Seems like the IN [ZONE] is ignored by 3,9.0 when adding a A record.

![image](https://github.com/user-attachments/assets/4333d3a0-f62d-4425-9c2a-548a1013fc07)

**Comment by dirkwa** [comment]
I understand now that the git repo in the readme was pointing towards the latest dev commits of unfinished 3.8.1 and not the latest release. I downgraded to 3.8.1 and all is fine now with the A record creation. Hope my findig above helps you. Thanks for bringing this project back to live. It's a great addon for PDNS. 🙏

**Comment by lgwapnitsky** [comment]
just installed 3.9 and the issue remains. Any chance of a fix, or do I have to downgrade?

**Comment by dirkwa** [comment]
I made the same issue. Their git tree seems to be dev. downgrade was easy. In in is the config.inc.php, save that. once 3.8.1 is unzipped restore it and delete folder install.

**Comment by edmondas** [comment]
Thanks for reporting the issue. I made a small mistake during the last refactoring, which triggered this problem.
