### ISSUE TITLE
move default zone template to database

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#71]
The records template should no longer be defined in the config file, it should be in the databases. Preferably, there should be support for multiple templates, which can be created and used by users themselves (or delegated from an admin to a user).

One kind of database implementation is like PowerDNS Administration ( http://sourceforge.net/projects/powerdnsadmin).

**Comment by edmondas** [comment]
This ticket is being closed as the requested functionality has already been implemented.
