### ISSUE TITLE
Privileges granularity

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#73]
Reported by:    tonix   Owned by:  
Priority:   major   Milestone:  Later
Component:  core    Version:  
Keywords:   privileges granularity  Cc:  
Description

It would be great if we could assign to groups permission with higher granularity. As example, we'd love our users could change any record except NS and MX. So it could be good to add other permission on NS or MX data(like the metadata privilege existing now), or simple permissions for each type of record (it would solve any kind of assign). Thanks, Tonino

**Comment by anthonysomerset** [comment]
it would be great from the groups perspective to have domains assignable to groups so that all users within that group can edit those domains but no others - right now the only way we can do that is if all those users share a single login

**Comment by SebTM** [comment]
To have a record based permission-system we need to refactor the whole permission-system.

**Comment by edmondas** [comment]
I am closing this ticket because there is another one https://github.com/poweradmin/poweradmin/issues/480.
