### ISSUE TITLE
Highlighting of linked template zones

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#75]
Template zones which have linked zones should be highlighted in listing.

Ideally, linked template zones should have a different menu entry, and total number of linked zones should be associated to each template zone.

We could call the "active templates" or whatever better, but I suggest to make clear thay have zones linked and depending on them.

**Comment by SebTM** [comment]
What are "linked zones"?

**Comment by edmondas** [comment]
@SebTM I thinke "linked zones" are those zones, that use templates and currently such zones are not highlighted or there's no column which shows which template is used. I'm moving it to next release.  Despite that it looks simple (for example adding a column in zone list) but without refactored code base we just adding more boilerplate.

**Comment by edmondas** [comment]
There is now a column for "in use" and a count of linked zones, along with a highlight for templates that have no linked zones. It is not clear whether we need another menu item or another term like active templates, so let's keep it simple.

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/9033112/211145315-c35751b9-19bf-43bf-9407-86924a31eebd.png">
