### ISSUE TITLE
Add more default DNS servers

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#86]
I would like to have 3 or more default DNS servers defined in the config.inc.php file. We use 3 primary DNS servers for all of our zones.

Interesting thing - I can't find that dns_ns2 is used anywhere in source code (excluding installer and config file). dns_ns1 is used for SOA record creation.

My question - how defined dns servers should be reused? Maybe to create NS records?

**Comment by edmondas** [comment]
Added in 6a38a08d747a76c57919c5cc08e9193954e84761
