### ISSUE TITLE
SQL error creating a zone with Pg and PDO

### ISSUE THREAD

**Issue by thowe** [poweradmin/poweradmin#9]
After successfully creating a zone template, I tried to add a test zone and got the following error:

The following query generated an error:

<pre>
INSERT INTO zones (domain_id,
 owner,
 zone_templ_id) VALUES ('',
 '1',
 '1')

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
LINE 1: ...O zones (domain_id, owner, zone_templ_id) VALUES ('', '1', '...
                                                             ^
</pre>

**Comment by picometer** [comment]
This issue has not solved yet.
the same error appears in 1.7.3 with Postgresql 9.4.

**Comment by picometer** [comment]
This issue has not solved yet.
the same error appears in 1.7.3 with Postgresql 9.4.
