### ISSUE TITLE
Slightly faster display of zone ( for pgsql )

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#94]
Reported by: 	rocker 	Owned by: 	eg
Priority: 	trivial 	Milestone: 	Later
Component: 	core 	Version: 	
Keywords: 		Cc: 	
Description

Hi, I made a minor modification to some files in poweradmin to help display zones quicker for my pdns installation. modified: record.inc.php

added function:

/*
 * Get a record from a query.
 * Assuming the query was 
 * 'SELECT id, domain_id, name, type, content, ttl, prio, change_date FROM records WHERE id='
 * Retrieve all fields of the record and send it back to the function caller.
 * return values: the array with information, or -1 is nothing is found.
 */
function get_record_from_query($result)
{
    if (isset($result))
    {
//      $result = $db->query("SELECT id, domain_id, name, type, content, ttl, prio, change_date FROM records WHERE id=".$db->quote($id, 'integer'));
            $ret = array(
                "id"            =>      $result["id"],
                "domain_id"     =>      $result["domain_id"],
                "name"          =>      $result["name"],
                "type"          =>      $result["type"],
                "content"       =>      $result["content"],
                "ttl"           =>      $result["ttl"],
                "prio"          =>      $result["prio"],
                "change_date"   =>      $result["change_date"]
                );
            return $ret;
    }
    else
    {
        error(sprintf(ERR_INV_ARG, "get_record_from_id"));
    }
}

 Modified this function:

/*
 * Get all records from a domain id.
 * Retrieve all fields of the records and send it back to the function caller.
 * return values: the array with information, or -1 is nothing is found.
 */
function get_records_from_domain_id($id,$rowstart=0,$rowamount=999999) {
    global $db;
    if (is_numeric($id)) {
        if ((isset($_SESSION[$id."_ispartial"])) && ($_SESSION[$id."_ispartial"] == 1)) {
            $db->setLimit($rowamount, $rowstart);
            $result = $db->query("SELECT record_owners.record_id as id
                    FROM record_owners,domains,records
                    WHERE record_owners.user_id = " . $db->quote($_SESSION["userid"], 'integer') . "
                    AND record_owners.record_id = records.id
                    AND records.domain_id = " . $db->quote($id, 'integer') . "
                    GROUP BY record_owners.record_id");

            $ret = array();
            if($result->numRows() == 0) {
                return -1;
            } else {
                $ret[] = array();
                $retcount = 0;
                while($r = $result->fetchRow())
                {
                    // Call get_record_from_id for each row.
                    $ret[$retcount] = get_record_from_id($r["id"]);
                    $retcount++;
                }
                return $ret;
            }

        } else {
            $db->setLimit($rowamount, $rowstart);
            $result = $db->query("SELECT id, domain_id, name, type, content, ttl, prio, change_date FROM records WHERE domain_id=".$db->quote($id, 'integer'));
            $ret = array();
            if($result->numRows() == 0)
            {
                return -1;
            }
            else
            {
                $ret[] = array();
                $retcount = 0;
                while($r = $result->fetchRow())
                {
                    // Call get_record_from_id for each row.
                    $ret[$retcount] = get_record_from_query($r);
                    $retcount++;
                }
                return $ret;
            }

        }
    }
    else
    {
        error(sprintf(ERR_INV_ARG, "get_records_from_domain_id"));
    }
}

Having the database prepare the list in one query instead of doing multiple selects significantly improved performance for me on my installation of poweradmin ( with pdns ) that uses a PostgreSQL backend.

Just thought I'd mention it. -Rocker

**Comment by SebTM** [comment]
Since the issue is from 2013 and we want to cleanup the code in the next releases we will also check how to optimize queries. So this ticket is obsolete as the mentioned changes doesn't fit for the current code.
