### ISSUE TITLE
Dynamic Update (DynDNS) refactoring and IPv4/IPv6 support

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#95]
- Refactored the DynDNS support to properly return status, so that ddclient etc. won't constantly hammer the script
- Added support for IPv4/IPv6 addresses (auto detection)
- Made use of built in is_valid_hostname_fqdn in inc/dns.inc.php for hostname validation
- Updated change_date in MySQL database on successful update of DynDNS record

I am not sure if we should add more indexes to handle the JOIN, but it seems to be okay with my system.

**Comment by SebTM** [comment]
Needs to be checked what is still todo after merge of #203
