### ISSUE TITLE
DNSSEC support?

### ISSUE THREAD

**Issue by ghost** [poweradmin/poweradmin#96]
Hello, Pdns announced DNSSEC support:  http://www.powerdns.com/news/powerdns-3.0-with-dnssec.aspx

Should we expect support in PowerAdmin??

It's quite big feature and requires time for analysis and development, therefore I'm asking for your help - it would be great to have user cases/stories or simply task backlog. If someone has time to create that then it will help a lot.

User story: \* ability to sign zones with the BIND signer scripts (implementing signing would be needlessly hard) \* toggle presigning (serving of presigned records) or on-the-fly signing (signatures aren't stored in the database/zone) \* ability to set DS records

hello, i just converted some of my zones to use the PowerDNS-DNSSEC feature (including updateing the pdns server). i then had to update the database according to  http://doc.powerdns.com/gsqlite.html#id447610 (7.2. Setting up the database), setting up the zones from command line no problem.

however i did not check all the zones in the system and a few hours later i had some problems with the zones not being transfed to bind servers and i got ZERO reply from the pdns server the the domains not using DNSSEC.

i located the problem to be that the data inserted and updated in the records table needed values in the to new columns add. (ordername and auth)

my first instinct whas to run "pdnssec rectify-zone [ZONE-NAME]" with a cron job went away from that quickly and edit the file "record.inc.php" to insert the data that should by there so the zone's would work again.

i'v then created a path for the file i like to share with you guys. IT'S important to that you DO some testing before using this on your production server/admin, AND i use pdns as master and bind as slave in my dns system and can't say that these problems will occur on pdns to pdns only systems

!DO NOT USE THIS PATCH IF YOU DONT HAVE THE DATA BASE SET UP FOR DNSSEC! i will continue developing this as i get time for it as i like to this feature in PowerAdmin? :)

OH!

forgot to say i tested this with. ipv4 and ipv6 arpa master zones including adding them ADD Master Domain with themplate ADD Master Domain no themplate Edit RR (+PTR)

https://gist.github.com/eg/3dd3a87042b06aaacaa6

**Comment by pumpal** [comment]
As an addition, for 'pdnssec' binary to work as expected when executed from PHP,  disable_funcions in php.ini should not limit the 'exec()'  function, and, the powerdns config files should be readable by the user that PHP executes as! If possible try 'su' as the user PHP runs as and then try to 'pdnssec rectify-zone example.net' with some zone to see if it works. In Debian 7.x it wasn't working by default  and I lost couple of hours investigating why adding/editing records does not work without manually calling pdnssec rectify-zone .

**Comment by edmondas** [comment]
Support for DNSSEC was updated in the latest release (2.1.9 or master).
